### ISSUE TITLE
Cannot read property 'lang' of null

### ISSUE THREAD

**Issue by idealley** [teambit/bit#1093]
## Expected Behavior
By running `bit status` I expect to see the status of all the components I just added

## Actual Behavior
It does an error:

```
Cannot read property 'lang' of null
TypeError: Cannot read property 'lang' of null
    at module.exports (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/lookups/vue-lookup/index.js:24:28)
    at cabinet (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/filing-cabinet/index.js:69:16)
    at Function.module.exports._getDependencies (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/dependency-tree/index.js:129:18)
    at traverse (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/dependency-tree/index.js:185:37)
    at traverse (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/dependency-tree/index.js:209:20)
    at traverse (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/dependency-tree/index.js:209:20)
    at traverse (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/dependency-tree/index.js:209:20)
    at traverse (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/dependency-tree/index.js:209:20)
    at traverse (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/dependency-tree/index.js:209:20)
    at traverse (/Users/samuel/.nvm/versions/node/v10.5.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/dependency-tree/index.js:209:20)
```
and does not print anything.

## Steps to Reproduce the Problem
To reproduce my environment, you can use this working progress repo: https://github.com/EuropeanRespiratorySociety/ers-web-app
  1. in a project (vue in my case) `bit init`
  2.  `bit add src/components/**/*.vue` or bit add src/components/**/* 
  3. `bit status`

## Specifications

  - Bit version: 13.0.0
  - Node version: 10.5.0
  - npm / yarn version: npm 6.1.0
  - Platform: Mac
  - Bit compiler (include version): ??
  - Bit tester (include version): ??

**Comment by GiladShoham** [comment]
Hi @idealley ,
Thanks for reporting this.
I'm able to reproduce the problem on my dev environment and working to solve it.
I'll keep you updated.
Thanks.

**Comment by itaymendel** [comment]
PR waiting for merge (thanks David ;) )
https://github.com/teambit/bit-javascript/pull/62

**Comment by gustavorodarte** [comment]
I'm having the same issue, has it been fixed? 

Specifications:

Bit version: 13.0.1
Node version: 8.11.2
npm / yarn version: npm 6.1.0
Platform: Linux(Fedora)

**Comment by GiladShoham** [comment]
it's fixed but not yet in production. will be part of the next version.
