### ISSUE TITLE
Better error reporting when file dependencies are missing

### ISSUE THREAD

**Issue by xurei** [teambit/bit#1167]
## Expected Behavior
Show the component that triggered the error.

## Actual Behavior
```
Error: Unknown object type "window"
    at Object._object (/home/olivier/.npm_bin/node_modules/object-hash/index.js:218:17)
    at Object.dispatch (/home/olivier/.npm_bin/node_modules/object-hash/index.js:185:30)
    at /home/olivier/.npm_bin/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
    at Object._object (/home/olivier/.npm_bin/node_modules/object-hash/index.js:242:21)
    at Object.dispatch (/home/olivier/.npm_bin/node_modules/object-hash/index.js:185:30)
    at /home/olivier/.npm_bin/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
    at Object._object (/home/olivier/.npm_bin/node_modules/object-hash/index.js:242:21)
    at Object.dispatch (/home/olivier/.npm_bin/node_modules/object-hash/index.js:185:30)
```

## Steps to Reproduce the Problem
1. mycomponent.js :
```
//OtherComponent is not added in the bit repository
import { OtherComponent } from './some/other/component';
export FaultyComponent = props => (<div>Hello World <OtherComponent/></div>)
```
2. `bit add mycomponent && bit tag mycomponent`

## Specifications
  - Bit version: 13.0.4
  - Node version: 8.11.3
  - npm / yarn version: 5.6.0
  - Platform: Linux
  - Bit compiler (include version): bit.envs/compilers/react@0.0.14
  - Bit tester (include version): bit.envs/testers/mocha@0.0.12

**Comment by itaymendel** [comment]
hi @xurei , sorry for the long response time.
The error you got is probably generated from Bit trying to run component's tests (bit runs all tests when tagging a new version).
To validate if there are any isolation errors, please run `bit status` prior to tagging a component.

can you run `bit status` after the add and validate that this is the case?

**Comment by davidfirst** [comment]
@xurei, there were many version releases since then, please reopen if you still experience the issue.
