### ISSUE TITLE
"Unexpected token <"

### ISSUE THREAD

**Issue by ThomasKientz** [teambit/bit#1232]
Importing a component from "@bit/.." from another sourced component produce the following error :

```
nuxt:render Rendering url /offre/publier +1s
{ /Users/thomas/Documents/Dev/jc/vc/node_modules/@bit/thomaskientz.vc.components.jc-autocomplete/jc-autocomplete.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              
SyntaxError: Unexpected token <
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at r (/Users/thomas/Documents/Dev/jc/vc/node_modules/vue-server-renderer/build.js:8341:16)
    at Object.379 (server-bundle.js:2651:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 657ab68e8621be2d38ee:25:0)
    at Object.183 (components/mission-infos.vue?0429:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 657ab68e8621be2d38ee:25:0)
    at Object.222 (components/mission-infos.vue:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 657ab68e8621be2d38ee:25:0)
    at Object.252 (pages/offre/publier.vue?960d:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 657ab68e8621be2d38ee:25:0)
    at Object.108 (pages/offre/publier.vue:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 657ab68e8621be2d38ee:25:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) statusCode: 500, name: 'SyntaxError' }
```

It a [Nuxt](https://nuxtjs.org/) project.

## Steps to Reproduce the Problem

  1. Track component A
  2. Track component B
  3. Import B from A with "@bit/.../B"

## Specifications

  - Bit version: 13.0.4
  - Node version: 10.8.0
  - npm / yarn version: 6.3.0
  - Platform: Mac OS
  - Bit compiler (include version): ?
  - Bit tester (include version): ?

**Comment by ThomasKientz** [comment]
looks similar to https://github.com/teambit/bit/issues/1225

**Comment by ThomasKientz** [comment]
Was due to Nuxt 2 https://cmty.app/nuxt/nuxt.js/issues/c7808#comment-5ba78c482d1cfd001482f526
