### ISSUE TITLE
bit import compiler fails with "Unexpected end of JSON input while parsing"

### ISSUE THREAD

**Issue by hirviid** [teambit/bit#1274]
## Expected Behavior
When I add a compiler with `bit import bit.envs/compilers/react -c`, it should not throw an error.

## Actual Behavior
`bit import bit.envs/compilers/react -c` returns following error:
```
failed running npm install at path-to-workspace/.bit/components/compilers/react/bit.envs/0.0.14/components/.dependencies/internal/babel-base-compiler/bit.envs/0.0.1   
npm ERR! Unexpected end of JSON input while parsing near '...grity":"sha512-kChlV+'
npm ERR! A complete log of this run can be found in:
npm ERR!     path-to-npm-logs/2018-10-12T10_31_33_026Z-debug.log
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.11.4
  - npm / yarn version: npm: 5.6.0, yarn: 1.10.1
  - Platform: MacOS 10.14 Mojave
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
I'm unable to recreate it in my environment.
any chance you can share the log from NPM that the error message refers to?

**Comment by hirviid** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/david/.nvm/versions/node/v8.11.4/bin/node',
1 verbose cli   '/Users/david/.nvm/versions/node/v8.11.4/bin/npm',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose npm-session 440ca8b676827b0e
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall @bit/bit.envs.compilers.react@0.0.14
7 info lifecycle @bit/bit.envs.compilers.react@0.0.14~preinstall: @bit/bit.envs.compilers.react@0.0.14
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-class-properties 229ms (from cache)
15 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-decorators-legacy 233ms (from cache)
16 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-async-to-generator 234ms (from cache)
17 silly pacote range manifest for babel-plugin-transform-class-properties@^6.24.1 fetched in 236ms
18 silly pacote range manifest for babel-plugin-transform-decorators-legacy@^1.3.4 fetched in 239ms
19 http fetch GET 304 https://registry.npmjs.org/babel-preset-latest 236ms (from cache)
20 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-regenerator 237ms (from cache)
21 silly pacote range manifest for babel-plugin-transform-async-to-generator@^6.24.1 fetched in 243ms
22 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-export-extensions 242ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-object-rest-spread 241ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-react-jsx 245ms (from cache)
25 silly pacote range manifest for babel-preset-latest@^6.24.1 fetched in 244ms
26 warn deprecated babel-preset-latest@6.24.1: We're super 😸  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
27 silly pacote range manifest for babel-plugin-transform-regenerator@^6.26.0 fetched in 248ms
28 silly pacote range manifest for babel-plugin-transform-export-extensions@^6.22.0 fetched in 252ms
29 silly pacote range manifest for babel-plugin-transform-object-rest-spread@^6.26.0 fetched in 252ms
30 silly pacote range manifest for babel-plugin-transform-react-jsx@^6.24.1 fetched in 255ms
31 http fetch GET 304 https://registry.npmjs.org/babel-helper-function-name 46ms (from cache)
32 silly pacote range manifest for babel-helper-function-name@^6.24.1 fetched in 49ms
33 http fetch GET 304 https://registry.npmjs.org/babel-preset-react 59ms (from cache)
34 silly pacote range manifest for babel-preset-react@^6.24.1 fetched in 64ms
35 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-class-properties 71ms (from cache)
36 silly pacote range manifest for babel-plugin-syntax-class-properties@^6.8.0 fetched in 74ms
37 http fetch GET 304 https://registry.npmjs.org/babel-template 69ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-decorators 75ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/babel-template 76ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/babel-runtime 76ms (from cache)
41 silly pacote range manifest for babel-template@^6.3.0 fetched in 77ms
42 silly pacote range manifest for babel-plugin-syntax-decorators@^6.1.18 fetched in 83ms
43 silly pacote range manifest for babel-template@^6.24.1 fetched in 83ms
44 silly pacote range manifest for babel-runtime@^6.2.0 fetched in 87ms
45 http fetch GET 304 https://registry.npmjs.org/babel-runtime 102ms (from cache)
46 silly pacote range manifest for babel-runtime@^6.22.0 fetched in 116ms
47 http fetch GET 304 https://registry.npmjs.org/babel-helper-remap-async-to-generator 109ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-async-functions 103ms (from cache)
49 silly pacote range manifest for babel-helper-remap-async-to-generator@^6.24.1 fetched in 118ms
50 silly pacote range manifest for babel-runtime@^6.26.0 fetched in 4ms
51 silly pacote range manifest for babel-plugin-syntax-async-functions@^6.8.0 fetched in 111ms
52 http fetch GET 304 https://registry.npmjs.org/babel-preset-es2015 98ms (from cache)
53 silly pacote range manifest for babel-preset-es2015@^6.24.1 fetched in 108ms
54 warn deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
55 http fetch GET 304 https://registry.npmjs.org/babel-preset-es2016 94ms (from cache)
56 http fetch GET 304 https://registry.npmjs.org/babel-preset-es2017 96ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/regenerator-transform 97ms (from cache)
58 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-export-extensions 98ms (from cache)
59 silly pacote range manifest for babel-preset-es2016@^6.24.1 fetched in 104ms
60 warn deprecated babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
61 silly pacote range manifest for babel-preset-es2017@^6.24.1 fetched in 105ms
62 warn deprecated babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
63 silly pacote range manifest for regenerator-transform@^0.10.0 fetched in 106ms
64 http fetch GET 200 https://registry.npmjs.org/babel-types 17ms (from cache)
65 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-object-rest-spread 82ms (from cache)
66 silly pacote range manifest for babel-plugin-syntax-export-extensions@^6.8.0 fetched in 109ms
67 silly pacote range manifest for babel-types@^6.24.1 fetched in 26ms
68 silly pacote range manifest for babel-plugin-syntax-object-rest-spread@^6.8.0 fetched in 96ms
69 http fetch GET 200 https://registry.npmjs.org/babel-traverse 26ms (from cache)
70 silly pacote range manifest for babel-traverse@^6.24.1 fetched in 32ms
71 http fetch GET 304 https://registry.npmjs.org/babel-helper-builder-react-jsx 78ms (from cache)
72 silly pacote range manifest for babel-helper-builder-react-jsx@^6.24.1 fetched in 86ms
73 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-jsx 90ms (from cache)
74 silly pacote range manifest for babel-traverse@^6.26.0 fetched in 6ms
75 silly pacote range manifest for babel-plugin-syntax-jsx@^6.8.0 fetched in 100ms
76 silly pacote range manifest for babel-types@^6.26.0 fetched in 8ms
77 http fetch GET 304 https://registry.npmjs.org/babel-helper-get-function-arity 86ms (from cache)
78 http fetch GET 304 https://registry.npmjs.org/babel-preset-flow 88ms (from cache)
79 http fetch GET 200 https://registry.npmjs.org/babylon 20ms (from cache)
80 http fetch GET 200 https://registry.npmjs.org/lodash 21ms (from cache)
81 silly fetchPackageMetaData error for babylon@^6.18.0 Unexpected end of JSON input while parsing near '...grity":"sha512-kChlV+'
82 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-jsx 89ms (from cache)
83 silly pacote range manifest for babel-helper-get-function-arity@^6.24.1 fetched in 97ms
84 silly pacote range manifest for lodash@^4.17.4 fetched in 28ms
85 silly pacote range manifest for babel-traverse@^6.26.0 fetched in 5ms
86 silly pacote range manifest for babel-preset-flow@^6.23.0 fetched in 100ms
87 silly pacote range manifest for babel-plugin-syntax-jsx@^6.3.13 fetched in 97ms
88 silly pacote range manifest for babel-types@^6.26.0 fetched in 8ms
89 silly pacote range manifest for lodash@^4.17.4 fetched in 13ms
90 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-react-display-name 108ms (from cache)
91 http fetch GET 200 https://registry.npmjs.org/babylon 18ms (from cache)
92 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-react-jsx-source 102ms (from cache)
93 silly fetchPackageMetaData error for babylon@^6.18.0 Unexpected end of JSON input while parsing near '...grity":"sha512-kChlV+'
94 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-react-jsx-self 98ms (from cache)
95 silly pacote range manifest for babel-plugin-transform-react-display-name@^6.23.0 fetched in 124ms
96 silly pacote range manifest for babel-plugin-transform-react-jsx-source@^6.22.0 fetched in 118ms
97 silly pacote range manifest for babel-plugin-transform-react-jsx-self@^6.22.0 fetched in 110ms
98 http fetch GET 304 https://registry.npmjs.org/core-js 53ms (from cache)
99 silly pacote range manifest for core-js@^2.4.0 fetched in 57ms
100 http fetch GET 304 https://registry.npmjs.org/babel-plugin-check-es2015-constants 59ms (from cache)
101 silly pacote range manifest for babel-plugin-check-es2015-constants@^6.22.0 fetched in 63ms
102 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-arrow-functions 65ms (from cache)
103 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-block-scoped-functions 60ms (from cache)
104 silly pacote range manifest for babel-plugin-transform-es2015-arrow-functions@^6.22.0 fetched in 73ms
105 silly pacote range manifest for babel-plugin-transform-es2015-block-scoped-functions@^6.22.0 fetched in 71ms
106 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-block-scoping 79ms (from cache)
107 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-computed-properties 75ms (from cache)
108 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-classes 79ms (from cache)
109 silly pacote range manifest for babel-plugin-transform-es2015-block-scoping@^6.24.1 fetched in 84ms
110 http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 115ms (from cache)
111 silly pacote range manifest for babel-plugin-transform-es2015-computed-properties@^6.24.1 fetched in 81ms
112 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-destructuring 62ms (from cache)
113 silly pacote range manifest for babel-plugin-transform-es2015-classes@^6.24.1 fetched in 87ms
114 silly pacote range manifest for babel-plugin-transform-es2015-destructuring@^6.22.0 fetched in 71ms
115 silly pacote range manifest for regenerator-runtime@^0.11.0 fetched in 125ms
116 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-duplicate-keys 69ms (from cache)
117 silly pacote range manifest for babel-plugin-transform-es2015-duplicate-keys@^6.24.1 fetched in 75ms
118 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-for-of 62ms (from cache)
119 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-function-name 57ms (from cache)
120 silly pacote range manifest for babel-plugin-transform-es2015-function-name@^6.24.1 fetched in 58ms
121 silly pacote range manifest for babel-plugin-transform-es2015-for-of@^6.22.0 fetched in 66ms
122 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-modules-amd 70ms (from cache)
123 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-modules-umd 60ms (from cache)
124 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-literals 75ms (from cache)
125 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-object-super 52ms (from cache)
126 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-modules-systemjs 68ms (from cache)
127 silly pacote range manifest for babel-plugin-transform-es2015-modules-umd@^6.24.1 fetched in 69ms
128 silly pacote range manifest for babel-plugin-transform-es2015-modules-amd@^6.24.1 fetched in 79ms
129 silly pacote range manifest for babel-plugin-transform-es2015-literals@^6.22.0 fetched in 84ms
130 silly pacote range manifest for babel-plugin-transform-es2015-object-super@^6.24.1 fetched in 61ms
131 silly pacote range manifest for babel-plugin-transform-es2015-modules-systemjs@^6.24.1 fetched in 76ms
132 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-shorthand-properties 68ms (from cache)
133 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-modules-commonjs 99ms (from cache)
134 silly pacote range manifest for babel-plugin-transform-es2015-shorthand-properties@^6.24.1 fetched in 70ms
135 silly pacote range manifest for babel-plugin-transform-regenerator@^6.24.1 fetched in 2ms
136 silly pacote range manifest for babel-plugin-transform-es2015-modules-commonjs@^6.24.1 fetched in 102ms
137 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-parameters 76ms (from cache)
138 silly pacote range manifest for babel-plugin-transform-es2015-parameters@^6.24.1 fetched in 81ms
139 silly pacote range manifest for babel-runtime@^6.18.0 fetched in 3ms
140 silly pacote range manifest for babel-types@^6.19.0 fetched in 3ms
141 http fetch GET 200 https://registry.npmjs.org/private 7ms (from cache)
142 silly pacote range manifest for private@^0.1.6 fetched in 15ms
143 http fetch GET 200 https://registry.npmjs.org/esutils 13ms (from cache)
144 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-spread 71ms (from cache)
145 silly pacote range manifest for esutils@^2.0.2 fetched in 17ms
146 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-unicode-regex 65ms (from cache)
147 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-template-literals 70ms (from cache)
148 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-typeof-symbol 69ms (from cache)
149 silly pacote range manifest for babel-plugin-transform-es2015-spread@^6.22.0 fetched in 77ms
150 silly pacote range manifest for babel-plugin-transform-es2015-unicode-regex@^6.24.1 fetched in 71ms
151 silly pacote range manifest for babel-plugin-transform-es2015-template-literals@^6.22.0 fetched in 75ms
152 silly pacote range manifest for babel-plugin-transform-es2015-typeof-symbol@^6.22.0 fetched in 74ms
153 http fetch GET 200 https://registry.npmjs.org/to-fast-properties 15ms (from cache)
154 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-exponentiation-operator 64ms (from cache)
155 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-es2015-sticky-regex 90ms (from cache)
156 http fetch GET 200 https://registry.npmjs.org/babel-code-frame 15ms (from cache)
157 silly pacote range manifest for to-fast-properties@^1.0.3 fetched in 20ms
158 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-trailing-function-commas 68ms (from cache)
159 http fetch GET 200 https://registry.npmjs.org/debug 14ms (from cache)
160 http fetch GET 200 https://registry.npmjs.org/babel-messages 16ms (from cache)
161 http fetch GET 200 https://registry.npmjs.org/globals 15ms (from cache)
162 silly pacote range manifest for babel-plugin-transform-exponentiation-operator@^6.24.1 fetched in 73ms
163 silly pacote range manifest for babel-plugin-transform-es2015-sticky-regex@^6.24.1 fetched in 99ms
164 silly pacote range manifest for babel-code-frame@^6.26.0 fetched in 25ms
165 silly pacote range manifest for debug@^2.6.8 fetched in 24ms
166 silly pacote range manifest for babel-messages@^6.23.0 fetched in 25ms
167 silly pacote range manifest for globals@^9.18.0 fetched in 24ms
168 silly pacote range manifest for babel-plugin-syntax-trailing-function-commas@^6.22.0 fetched in 79ms
169 silly pacote range manifest for babel-template@^6.26.0 fetched in 8ms
170 http fetch GET 200 https://registry.npmjs.org/invariant 23ms (from cache)
171 silly pacote range manifest for invariant@^2.2.2 fetched in 25ms
172 http fetch GET 304 https://registry.npmjs.org/babel-plugin-object-values-to-object-keys 888ms (from cache)
173 silly pacote range manifest for babel-plugin-object-values-to-object-keys@^1.0.2 fetched in 915ms
174 http fetch GET 304 https://registry.npmjs.org/babel-helper-define-map 52ms (from cache)
175 silly pacote range manifest for babel-helper-define-map@^6.24.1 fetched in 58ms
176 http fetch GET 304 https://registry.npmjs.org/babel-helper-replace-supers 60ms (from cache)
177 http fetch GET 304 https://registry.npmjs.org/babel-helper-optimise-call-expression 64ms (from cache)
178 http fetch GET 304 https://registry.npmjs.org/babel-helper-hoist-variables 62ms (from cache)
179 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-flow-strip-types 71ms (from cache)
180 silly pacote range manifest for babel-helper-replace-supers@^6.24.1 fetched in 66ms
181 silly pacote range manifest for babel-helper-optimise-call-expression@^6.24.1 fetched in 70ms
182 silly pacote range manifest for babel-helper-hoist-variables@^6.24.1 fetched in 68ms
183 silly pacote range manifest for babel-plugin-transform-flow-strip-types@^6.22.0 fetched in 76ms
184 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-strict-mode 72ms (from cache)
185 http fetch GET 304 https://registry.npmjs.org/babel-helper-call-delegate 71ms (from cache)
186 http fetch GET 200 https://registry.npmjs.org/chalk 10ms (from cache)
187 silly pacote range manifest for babel-plugin-transform-strict-mode@^6.24.1 fetched in 77ms
188 silly pacote range manifest for babel-helper-call-delegate@^6.24.1 fetched in 75ms
189 http fetch GET 200 https://registry.npmjs.org/js-tokens 9ms (from cache)
190 http fetch GET 304 https://registry.npmjs.org/babel-helper-regex 64ms (from cache)
191 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-object-entries 931ms (from cache)
192 http fetch GET 200 https://registry.npmjs.org/ms 11ms (from cache)
193 silly pacote range manifest for chalk@^1.1.3 fetched in 14ms
194 silly pacote range manifest for js-tokens@^3.0.2 fetched in 13ms
195 silly pacote range manifest for babel-helper-regex@^6.24.1 fetched in 68ms
196 silly pacote version manifest for ms@2.0.0 fetched in 16ms
197 silly pacote range manifest for babel-plugin-transform-object-entries@^1.0.0 fetched in 938ms
198 http fetch GET 200 https://registry.npmjs.org/loose-envify 11ms (from cache)
199 http fetch GET 304 https://registry.npmjs.org/regexpu-core 61ms (from cache)
200 http fetch GET 200 https://registry.npmjs.org/ansi-styles 12ms (from cache)
201 http fetch GET 200 https://registry.npmjs.org/escape-string-regexp 12ms (from cache)
202 silly pacote range manifest for loose-envify@^1.0.0 fetched in 17ms
203 http fetch GET 200 https://registry.npmjs.org/has-ansi 12ms (from cache)
204 http fetch GET 200 https://registry.npmjs.org/supports-color 8ms (from cache)
205 http fetch GET 200 https://registry.npmjs.org/strip-ansi 10ms (from cache)
206 silly pacote range manifest for ansi-styles@^2.2.1 fetched in 16ms
207 silly pacote range manifest for escape-string-regexp@^1.0.2 fetched in 16ms
208 silly pacote range manifest for babel-runtime@^6.9.0 fetched in 4ms
209 silly pacote range manifest for regexpu-core@^2.0.0 fetched in 68ms
210 silly pacote range manifest for has-ansi@^2.0.0 fetched in 18ms
211 silly pacote range manifest for supports-color@^2.0.0 fetched in 14ms
212 silly pacote range manifest for strip-ansi@^3.0.0 fetched in 16ms
213 silly pacote range manifest for js-tokens@^3.0.0 || ^4.0.0 fetched in 8ms
214 http fetch GET 200 https://registry.npmjs.org/ansi-regex 14ms (from cache)
215 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 16ms
216 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-exponentiation-operator 63ms (from cache)
217 http fetch GET 304 https://registry.npmjs.org/babel-helper-builder-binary-assignment-operator-visitor 56ms (from cache)
218 silly pacote range manifest for babel-plugin-syntax-exponentiation-operator@^6.8.0 fetched in 65ms
219 silly pacote range manifest for babel-helper-builder-binary-assignment-operator-visitor@^6.24.1 fetched in 58ms
220 http fetch GET 304 https://registry.npmjs.org/regjsparser 49ms (from cache)
221 silly pacote range manifest for regjsparser@^0.1.4 fetched in 50ms
222 http fetch GET 200 https://registry.npmjs.org/jsesc 3ms (from cache)
223 silly pacote range manifest for jsesc@~0.5.0 fetched in 6ms
224 http fetch GET 304 https://registry.npmjs.org/babel-helper-explode-assignable-expression 33ms (from cache)
225 silly pacote range manifest for babel-helper-explode-assignable-expression@^6.24.1 fetched in 36ms
226 http fetch GET 304 https://registry.npmjs.org/babel-plugin-syntax-flow 87ms (from cache)
227 silly pacote range manifest for babel-plugin-syntax-flow@^6.18.0 fetched in 88ms
228 http fetch GET 304 https://registry.npmjs.org/regjsgen 72ms (from cache)
229 silly pacote range manifest for regjsgen@^0.2.0 fetched in 74ms
230 http fetch GET 304 https://registry.npmjs.org/regenerate 82ms (from cache)
231 silly pacote range manifest for regenerate@^1.2.1 fetched in 83ms
232 silly pacote range manifest for babel-plugin-object-values-to-object-keys@^1.0.2 fetched in 3ms
233 silly resolveWithNewModule babel-plugin-object-values-to-object-keys@1.0.2 checking installable status
234 silly pacote range manifest for babel-plugin-transform-async-to-generator@^6.24.1 fetched in 5ms
235 silly resolveWithNewModule babel-plugin-transform-async-to-generator@6.24.1 checking installable status
236 silly pacote range manifest for babel-plugin-transform-decorators-legacy@^1.3.4 fetched in 5ms
237 silly resolveWithNewModule babel-plugin-transform-decorators-legacy@1.3.5 checking installable status
238 silly pacote range manifest for babel-plugin-transform-class-properties@^6.24.1 fetched in 5ms
239 silly resolveWithNewModule babel-plugin-transform-class-properties@6.24.1 checking installable status
240 silly pacote range manifest for babel-plugin-transform-object-entries@^1.0.0 fetched in 6ms
241 silly resolveWithNewModule babel-plugin-transform-object-entries@1.0.0 checking installable status
242 silly pacote range manifest for babel-plugin-transform-react-jsx@^6.24.1 fetched in 6ms
243 silly resolveWithNewModule babel-plugin-transform-react-jsx@6.24.1 checking installable status
244 silly pacote range manifest for babel-plugin-transform-export-extensions@^6.22.0 fetched in 6ms
245 silly resolveWithNewModule babel-plugin-transform-export-extensions@6.22.0 checking installable status
246 silly pacote range manifest for babel-plugin-transform-object-rest-spread@^6.26.0 fetched in 7ms
247 silly resolveWithNewModule babel-plugin-transform-object-rest-spread@6.26.0 checking installable status
248 silly pacote range manifest for babel-plugin-transform-regenerator@^6.26.0 fetched in 7ms
249 silly resolveWithNewModule babel-plugin-transform-regenerator@6.26.0 checking installable status
250 silly pacote range manifest for babel-preset-latest@^6.24.1 fetched in 7ms
251 silly resolveWithNewModule babel-preset-latest@6.24.1 checking installable status
252 silly pacote range manifest for babel-preset-react@^6.24.1 fetched in 1ms
253 silly resolveWithNewModule babel-preset-react@6.24.1 checking installable status
254 silly pacote range manifest for babel-helper-remap-async-to-generator@^6.24.1 fetched in 1ms
255 silly resolveWithNewModule babel-helper-remap-async-to-generator@6.24.1 checking installable status
256 silly pacote range manifest for babel-plugin-syntax-async-functions@^6.8.0 fetched in 1ms
257 silly resolveWithNewModule babel-plugin-syntax-async-functions@6.13.0 checking installable status
258 silly pacote range manifest for babel-runtime@^6.22.0 fetched in 2ms
259 silly resolveWithNewModule babel-runtime@6.26.0 checking installable status
260 silly pacote range manifest for babel-template@^6.24.1 fetched in 2ms
261 silly resolveWithNewModule babel-template@6.26.0 checking installable status
262 silly pacote range manifest for babel-types@^6.24.1 fetched in 2ms
263 silly resolveWithNewModule babel-types@6.26.0 checking installable status
264 silly pacote range manifest for babel-traverse@^6.24.1 fetched in 3ms
265 silly resolveWithNewModule babel-traverse@6.26.0 checking installable status
266 silly pacote range manifest for babel-helper-function-name@^6.24.1 fetched in 2ms
267 silly resolveWithNewModule babel-helper-function-name@6.24.1 checking installable status
268 silly pacote range manifest for babel-helper-get-function-arity@^6.24.1 fetched in 1ms
269 silly resolveWithNewModule babel-helper-get-function-arity@6.24.1 checking installable status
270 silly pacote range manifest for core-js@^2.4.0 fetched in 1ms
271 silly resolveWithNewModule core-js@2.5.7 checking installable status
272 silly pacote range manifest for regenerator-runtime@^0.11.0 fetched in 2ms
273 silly resolveWithNewModule regenerator-runtime@0.11.1 checking installable status
274 silly pacote range manifest for esutils@^2.0.2 fetched in 0ms
275 silly resolveWithNewModule esutils@2.0.2 checking installable status
276 silly pacote range manifest for lodash@^4.17.4 fetched in 1ms
277 silly resolveWithNewModule lodash@4.17.11 checking installable status
278 silly pacote range manifest for to-fast-properties@^1.0.3 fetched in 1ms
279 silly resolveWithNewModule to-fast-properties@1.0.3 checking installable status
280 http fetch GET 200 https://registry.npmjs.org/babylon 1ms (from cache)
281 silly fetchPackageMetaData error for babylon@^6.18.0 Unexpected end of JSON input while parsing near '...grity":"sha512-kChlV+'
282 silly saveTree @bit/bit.envs.compilers.react@0.0.14
282 silly saveTree ├── babel-plugin-object-values-to-object-keys@1.0.2
282 silly saveTree ├─┬ babel-plugin-transform-async-to-generator@6.24.1
282 silly saveTree │ ├─┬ babel-helper-remap-async-to-generator@6.24.1
282 silly saveTree │ │ ├─┬ babel-helper-function-name@6.24.1
282 silly saveTree │ │ │ ├─┬ babel-helper-get-function-arity@6.24.1
282 silly saveTree │ │ │ │ ├─┬ babel-runtime@6.26.0
282 silly saveTree │ │ │ │ │ ├── core-js@2.5.7
282 silly saveTree │ │ │ │ │ └── regenerator-runtime@0.11.1
282 silly saveTree │ │ │ │ └─┬ babel-types@6.26.0
282 silly saveTree │ │ │ │   ├── esutils@2.0.2
282 silly saveTree │ │ │ │   ├── lodash@4.17.11
282 silly saveTree │ │ │ │   └── to-fast-properties@1.0.3
282 silly saveTree │ │ │ ├── babel-runtime@6.26.0
282 silly saveTree │ │ │ ├─┬ babel-template@6.26.0
282 silly saveTree │ │ │ │ └── babel-traverse@6.26.0
282 silly saveTree │ │ │ ├── babel-traverse@6.26.0
282 silly saveTree │ │ │ └── babel-types@6.26.0
282 silly saveTree │ │ ├── babel-runtime@6.26.0
282 silly saveTree │ │ ├── babel-template@6.26.0
282 silly saveTree │ │ ├── babel-traverse@6.26.0
282 silly saveTree │ │ └── babel-types@6.26.0
282 silly saveTree │ ├── babel-plugin-syntax-async-functions@6.13.0
282 silly saveTree │ └── babel-runtime@6.26.0
282 silly saveTree ├── babel-plugin-transform-class-properties@6.24.1
282 silly saveTree ├── babel-plugin-transform-decorators-legacy@1.3.5
282 silly saveTree ├── babel-plugin-transform-export-extensions@6.22.0
282 silly saveTree ├── babel-plugin-transform-object-entries@1.0.0
282 silly saveTree ├── babel-plugin-transform-object-rest-spread@6.26.0
282 silly saveTree ├── babel-plugin-transform-react-jsx@6.24.1
282 silly saveTree ├── babel-plugin-transform-regenerator@6.26.0
282 silly saveTree ├── babel-preset-latest@6.24.1
282 silly saveTree └── babel-preset-react@6.24.1
283 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...grity":"sha512-kChlV+'
283 verbose stack     at JSON.parse (<anonymous>)
283 verbose stack     at parseJson (/Users/david/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
283 verbose stack     at consumeBody.call.then.buffer (/Users/david/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
283 verbose stack     at <anonymous>
283 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
284 verbose cwd path-to-workspace/.bit/components/compilers/react/bit.envs/0.0.14
285 verbose Darwin 18.0.0
286 verbose argv "/Users/david/.nvm/versions/node/v8.11.4/bin/node" "/Users/david/.nvm/versions/node/v8.11.4/bin/npm" "install"
287 verbose node v8.11.4
288 verbose npm  v5.6.0
289 error Unexpected end of JSON input while parsing near '...grity":"sha512-kChlV+'
290 verbose exit [ 1, true ]
```

**Comment by hirviid** [comment]
@itaymendel I solved it for now with a workaround, using bit inside docker 😄 . I assume it's something with my machine.

**Comment by itaymendel** [comment]
mmm interesting.
i'm closing it for now. if this happens again, please reopen.
