### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by ChuksFestus** [teambit/bit#1319]
Hello,
So i wanna try using bit but the docs and even the video on youtube isn't really giving me what i want, how come i can't review the component in the overview section, how do i rename a scoope, what happend to the docs? like how do i generate docs etc. Would appreciate a detailed example

**Comment by ChuksFestus** [comment]
> Hello,
> So i wanna try using bit but the docs and even the video on youtube isn't really giving me what i want, how come i can't review the component in the overview section, how do i rename a scoope, what happend to the docs? like how do i generate docs etc. Would appreciate a detailed example

I kinda figured out the whole overivew thingy, it gets it from your comments if i'm not mistaking now I'm stuck with some error message... seems like bit doesn't understand styled-components 

```ModuleParseError: Module parse failed: Unexpected token (56:4)
You may need an appropriate loader to handle this file type.
|   console.log(value);
|   return (
>     <InputContainer>
|       <label>{props.label}</label>
|       <input
    at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:449:19)
    at doBuild.err (/app/node_modules/webpack/lib/NormalModule.js:483:5)
    at runLoaders (/app/node_modules/webpack/lib/NormalModule.js:344:12)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/app/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /app/node_modules/graceful-fs/graceful-fs.js:78:16
    at wrappedCallback (/app/node_modules/newrelic/lib/transaction/tracer/index.js:317:17)
    at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)
    at wrappedCallback (/app/node_modules/newrelic/lib/transaction/tracer/index.js:443:66)
    at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)```

**Comment by itaymendel** [comment]
hi @ChuksFestus ,

There are a few items you raised in the main issue. I'll start by addressing the rendering error:  
From what it seems, the issue in the rendering feature is probably due to the fact that the public compilers (and bundlers) have their own configuration. This configuration probably does not work well with your project.

What I suggest is that you will modify the bundler configuration according to your needs. You can find the instructions to it [here](https://discourse.bitsrc.io/t/can-i-modify-a-build-test-environments/28).

We are working to include additional APIs for the compilers so you will be able to pass your own configs to it. I trust that it will be GA very soon.

As for component-documentation, Bit supports parsing of JSDocs or tracking a markdown file as part of the component. You can read more about it [here](https://docs.bitsrc.io/docs/documenting-components.html).

It is impossible to rename a Scope, as it will require a rename and restructure for the entire dependency trees of all components that are in that Scope and their dependents.

I'm sad to hear that the current structure of the docs is not working for you. As we constantly try to improve them, I would love it if you can list some specific issues you had when working with them, so we can try and improve them. If you would - please open a new github issue in the [docs repo](https://github.com/teambit/bit-docs).

I'm closing the issue, for now, please let me know if you need additional help.
