### ISSUE TITLE
bit import fails

### ISSUE THREAD

**Issue by renewooller** [teambit/bit#1354]
## Expected Behavior
after running bit import <mycomponent>
it should update the local scope with new versions from the remote scope. 

## Actual Behavior
Get an error:
2018-12-18T02:48:19.448Z - debug: sources.getMany, Ids: rene_wooller.nl/global/nl-swifty-interface@0.5.15
2018-12-18T02:48:19.454Z - error: got an error from command import [ids...]: TypeError: Cannot read property 'indexOf' of undefined. Error serialized: {"stack":"TypeError: Cannot read property 'indexOf' of undefined\n    at _indexOf (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/ramda/src/internal/_indexOf.js:7:18)\n    at _contains (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/ramda/src/internal/_contains.js:5:10)\n    at difference (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/ramda/src/difference.js:30:10)\n    at Object.f2 [as difference] (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/ramda/src/internal/_curry2.js:25:16)\n    at ImportComponents._callee5$ (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/dist/consumer/component-ops/import-components.js:445:83)\n    at tryCatch (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.(anonymous function) [as next] (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)\n    at step (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/dist/consumer/component-ops/import-components.js:115:191)\n    at /usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/dist/consumer/component-ops/import-components.js:115:361","message":"Cannot read property 'indexOf' of undefined"}

## Steps to Reproduce the Problem

in project A:
  1. bit add <path> --id <mycomponent>
  1. bit tag <component> 0.5.15
  1. bit export <user>.<scope> <mycomponent>

In project B
 1. bit import an existing component eg v 0.5.15
 1. make changes
 1.bit tag <component> 0.5.16
 1. bit export <user>.<scope> <mycomponent>

Back to project A:
 1. bit import <mycomponent>

Observe response:
renewooller[~/software/nl-swifty-backend] (bit_test): bit import nl-swifty-interface
npm WARN @nightlife/nl-skeletor@7.2.3 requires a peer of @types/node@~8.5.1 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-chai@2.14.0 requires a peer of sinon@^1.4.0 || ^2.1.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
successfully ran npm install at /Users/renewooller/software/nl-swifty-backend

Cannot read property 'indexOf' of undefined
 
Looking at logs:

2018-12-18T03:04:10.937Z - debug: sources.getMany, Ids: rene_wooller.nl/global/nl-swifty-interface@0.5.15
2018-12-18T03:04:10.942Z - error: got an error from command import [ids...]: TypeError: Cannot read property 'indexOf' of undefined. Error serialized: {"stack":"TypeError: Cannot read property 'indexOf' of undefined\n    at _indexOf (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/ramda/src/internal/_indexOf.js:7:18)\n    at _contains (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/ramda/src/internal/_contains.js:5:10)\n    at difference (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/ramda/src/difference.js:30:10)\n    at Object.f2 [as difference] (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/ramda/src/internal/_curry2.js:25:16)\n    at ImportComponents._callee5$ (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/dist/consumer/component-ops/import-components.js:445:83)\n    at tryCatch (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.(anonymous function) [as next] (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)\n    at step (/usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/dist/consumer/component-ops/import-components.js:115:191)\n    at /usr/local/opt/nvm/versions/node/v8.5.0/lib/node_modules/bit-bin/dist/consumer/component-ops/import-components.js:115:361","message":"Cannot read property 'indexOf' of undefined"}
2018-12-18T03:04:10.985Z - error: [*] the command import [ids...] has been terminated with an error code 1

## Specifications

  - Bit version:
13.0.4
  - Node version:
tried with 8.9.0, and 8.5.0
  - npm / yarn version:

  - Platform:
mac
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by renewooller** [comment]
I've found that if I use the full path of the component ID it works
