### ISSUE TITLE
Vue component with Typescript language throws parsing error during `status`

### ISSUE THREAD

**Issue by sirtimbly** [teambit/bit#1369]
## Expected Behavior

Adding a component and running `bit status` should show `> atoms/button ... ok`

## Actual Behavior

```
> atoms/button ...  issues found
       error found while parsing the file (please edit the file and fix the parsing error):
          src/components/atoms/button/feature-button.vue -> Unexpected token (15:10)
```
The debug log contains the longer stack trace.

```
2019-01-03T21:44:43.269Z - [32minfo[39m: [*] started a new command: "status" with the following data: 
{ args: [], flags: {}, packageManagerArgs: [] }
2019-01-03T21:44:43.278Z - [32minfo[39m: Checking if a migration is needed
2019-01-03T21:44:43.305Z - [34mdebug[39m: starting migration process
2019-01-03T21:44:43.309Z - [34mdebug[39m: running migration process for consumer
2019-01-03T21:44:43.310Z - [34mdebug[39m: bit.map version is up to date
2019-01-03T21:44:43.310Z - [34mdebug[39m: running migration process for scope in consumer
2019-01-03T21:44:43.310Z - [34mdebug[39m: running migration process for scope
2019-01-03T21:44:43.311Z - [34mdebug[39m: scope version is up to date
2019-01-03T21:44:43.329Z - [34mdebug[39m: loading consumer-components from the file-system, ids: atoms/button
2019-01-03T21:44:43.335Z - [34mdebug[39m: Failed finding a ref file /Users/tim/Sites/vue-ts-bit-bug-repro/app/.bit/objects/c5/3840df7bdc0f156d4a1fde001e0c750f5d89ad.
2019-01-03T21:44:43.335Z - [34mdebug[39m: failed finding a component atoms/button with hash: c53840df7bdc0f156d4a1fde001e0c750f5d89ad
2019-01-03T21:44:43.377Z - [34mdebug[39m: bit add - one component
2019-01-03T21:44:43.762Z - [31merror[39m: got an error from the driver while resolving dependencies
2019-01-03T21:44:43.762Z - [31merror[39m:  
{ message: [32m'Unexpected token (15:10)'[39m,
  stack:
   [32m'SyntaxError: Unexpected token (15:10)\n    at Parser.pp$5.raise (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:4454:13)\n    at Parser.pp.unexpected (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:1761:8)\n    at Parser.pp$1.parseClassBody (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:2554:14)\n    at Parser.pp$1.parseClass (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:2406:8)\n    at Parser.pp$1.parseExport (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:2642:19)\n    at Parser.parseExport (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:6000:20)\n    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:1884:74)\n    at Parser.parseStatement (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:5910:22)\n    at Parser.pp$1.parseBlockBody (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:2268:21)\n    at Parser.pp$1.parseTopLevel (/usr/local/lib/node_modules/bit-bin/node_modules/babylon/lib/index.js:1778:8)'[39m,
  pos: [33m174[39m,
  loc: { line: [33m15[39m, column: [33m10[39m },
  code: [32m'PARSING_ERROR'[39m }
2019-01-03T21:44:43.767Z - [34mdebug[39m: Finished loading the component, atoms/button
2019-01-03T21:44:43.768Z - [34mdebug[39m: loading consumer-components from the file-system, ids: atoms/button
2019-01-03T21:44:43.769Z - [34mdebug[39m: the component atoms/button has been already loaded, use the cached component
2019-01-03T21:44:43.769Z - [34mdebug[39m: loading consumer-components from the file-system, ids: 
2019-01-03T21:44:43.772Z - [34mdebug[39m: Failed finding a ref file /Users/tim/Sites/vue-ts-bit-bug-repro/app/.bit/objects/c5/3840df7bdc0f156d4a1fde001e0c750f5d89ad.
2019-01-03T21:44:43.772Z - [34mdebug[39m: failed finding a component atoms/button with hash: c53840df7bdc0f156d4a1fde001e0c750f5d89ad
2019-01-03T21:44:43.773Z - [34mdebug[39m: loading consumer-components from the file-system, ids: atoms/button
2019-01-03T21:44:43.773Z - [34mdebug[39m: the component atoms/button has been already loaded, use the cached component
2019-01-03T21:44:43.774Z - [34mdebug[39m: loading consumer-components from the file-system, ids: atoms/button
2019-01-03T21:44:43.775Z - [34mdebug[39m: the component atoms/button has been already loaded, use the cached component
2019-01-03T21:44:43.824Z - [32minfo[39m: [*] the command status has been completed successfully
```

## Steps to Reproduce the Problem

  1. Clone my repro code https://github.com/sirtimbly/bit-vue-typescript-bug
  1. `cd app/` and then `npm i`
  1. `bit status` 

The only way I can get the parser error to go away is to remove the typescript syntax from the vue file (the words public or private, specifically). It seems like the babel parser is still trying to look at the contents of the script block instead of the typescript parser?

--- 

OK I just looked some more and if I check the node modules that in the global version of bit-bin -( `~/.nvm/versions/node/v8.11.4/lib/node_modules/bit-bin/node_modules/bit-javascript` )- I see that it's using the older 1.0.5 release - which doesn't have support for Vue and typescript in it yet.  It was added in this commit https://github.com/teambit/bit-javascript/commit/e005fc25c6b5d04c0cacbe9f78244ea961c6e028 (but hasn't made it to the main release yet?)

## Specifications

  - Bit version: 13.0.4
  - Node version: v8.11.4
  - npm / yarn version: npm v5.6.0
  - Platform: MacOS Mojave
  - Bit compiler (include version): 
  - Bit tester (include version):

**Comment by sirtimbly** [comment]
OK. Sorry I finally understand what's happening, but I don't understand why 13.0.4 is still the current version. For right now I got the latest dev version by uninstalling bit-bin globally and installing the latest version on npmjs.com `npm install -g bit-bin@13.0.6-dev.31` After that my Vue typescript components are parsed correctly! 🎉

**Comment by qballer** [comment]
People on the team fixed a lot of bugs but I wouldn't use `bit@dev`. It hasn't been upgrade to the latest version on our servers and you will fail to export/import components. I'm going to see if we can cherry pick from the dev version to production. Any chance you can prepare a fake repo containing the bug ?

**Comment by sirtimbly** [comment]
Yep here  https://github.com/sirtimbly/bit-vue-typescript-bug

**Comment by GiladShoham** [comment]
@sirtimbly Thanks for the reproducing repo!

**Comment by davidfirst** [comment]
The new version (v14.0.0) has been released and it fixed the issue above.
