### ISSUE TITLE
failed loading file from the model

### ISSUE THREAD

**Issue by drewdecarme** [teambit/bit#1516]
## Expected Behavior
The bit CLI should be working properly, or minimally indicating a path for fixing the error.

## Actual Behavior
The bit CLI shows an error that doesn't have any actions associated with it.

I force removed a component from the remote registry and then force removed it from my project locally using the following commands

```shell
bit remove <ORG>.styles/cards/card-complex@1.0.5 --force --remote
bit remove <ORG>.styles/cards/card-complex@1.0.5 --force
```
Both of them worked fine, as I didn't want those components anymore. I then went to run `bit status` and got the below error.

```shell
failed loading file src/app/cards/Card/index.spec.js from the model
```
I tried a bunch of things like `link`, `install`, `build`, etc... but it seems to keep bombing out on me before anything can happen.

## Steps to Reproduce the Problem
1. Tough to tell, force uninstall a component
2. run `bit status`
3. see error

## Specifications

  - Bit version: 14.0.4
  - Node version: 10.15.0
  - npm / yarn version: 6.9.0
  - Platform: MacOSX
  - Bit compiler (include version): bit.envs/compilers/react@1.0.0
  - Bit tester (include version): none

**Comment by davidfirst** [comment]
@drewdecarme , is this file `src/app/cards/Card/index.spec.js` was part of the deleted component? is it currently part of other components?

**Comment by drewdecarme** [comment]
that file is one that is being tracked in another component which is a part of a separate directory

```
Cards
| - Card
| - CardComplex (deleted).
```

CardComplex was composed of the Bit component Card. There was no dependency of CardComplex on Card.

**Comment by drewdecarme** [comment]
Another thing I just realized is that when I run `bit build` I get the below error:
```shell
failed loading file src/app/cards/Card/index.spec.js from the model
```

When I try running `bit status` I get this error:
```
failed loading file src/app/cards/Card/index.spec.js.map from the model
```

**Comment by davidfirst** [comment]
This `card` component was tagged or is it new? what happens when you run `bit show Card`, do you get the same error? Also, by any chance this file is empty?
If it is tagged, try to run `bit cmp Card@latest` and check if you see the file there in the files array.

**Comment by drewdecarme** [comment]
Running `bit show Card` and `bit show card` got me this:
```shell
error: component "Card" was not found on your local workspace.
please specify a valid component ID or track the component using 'bit add' (see 'bit add --help' for more information)
...
error: component "card" was not found on your local workspace.
please specify a valid component ID or track the component using 'bit add' (see 'bit add --help' for more information)
```

Running `bit cmpCard@latest` got me this beautiful stack trace
```shell
{"payload":{"name":"InvalidName","isUserError":true,"componentName":"Card","message":"error: \"\u001b[1mCard\u001b[22m\" is invalid, component names can only contain alphanumeric, lowercase characters, and the following [\"-\", \"_\", \"$\", \"!\", \"/\"]","stack":"InvalidName\n    at InvalidName.ExtendableBuiltin (/usr/local/lib/node_modules/bit-bin/dist/error/abstract-error.js:15:28)\n    at InvalidName.AbstractError (/usr/local/lib/node_modules/bit-bin/dist/error/abstract-error.js:45:116)\n    at new InvalidName (/usr/local/lib/node_modules/bit-bin/dist/bit-id/exceptions/invalid-name.js:27:112)\n    at Function.parse (/usr/local/lib/node_modules/bit-bin/dist/bit-id/bit-id.js:276:82)\n    at Scope._callee34$ (/usr/local/lib/node_modules/bit-bin/dist/scope/scope.js:1713:84)\n    at tryCatch (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:147:5)"},"headers":{"version":"14.0.4"}}
```

**Comment by davidfirst** [comment]
lol sorry about the `isUserError`, I added it recently, but not for blaming users :)

Anyway, I just got confused with the name, please try to run the same commands but replace `Card` with `CardComplex`.

**Comment by drewdecarme** [comment]
Haha totally fine, I actually love that strategy to narrow things down.

Here are couple more attempts:

```shell
// command
bit cmp cards/card

// results
{
    "name": "cards/card",
    "scope": "<ORG>.components",
    "versions": {
        "1.0.0": "111de28f534339ce81b1b49bd6aeb10eebd40116",
        "1.0.1": "f584171329437f42e6cf62bfa1976e814163024f"
    },
    "lang": "javascript",
    "deprecated": false,
    "bindingPrefix": "@bit"
}
```

```shell
// command
bit cmp cards/card-complex

// results
{"payload":{"name":"GeneralError","isUserError":true,"msg":"component was not found","message":"component was not found","stack":"GeneralError\n    at GeneralError.ExtendableBuiltin (/usr/local/lib/node_modules/bit-bin/dist/error/abstract-error.js:15:28)\n    at GeneralError.AbstractError (/usr/local/lib/node_modules/bit-bin/dist/error/abstract-error.js:45:116)\n    at new GeneralError (/usr/local/lib/node_modules/bit-bin/dist/error/general-error.js:27:114)\n    at _callee$ (/usr/local/lib/node_modules/bit-bin/dist/api/scope/lib/cat-component.js:74:19)\n    at tryCatch (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:17:14)"},"headers":{"version":"14.0.4"}}
```

```shell
// command
bit cmp cards/CardComplex

// results
{"payload":{"name":"GeneralError","isUserError":true,"msg":"component was not found","message":"component was not found","stack":"GeneralError\n    at GeneralError.ExtendableBuiltin (/usr/local/lib/node_modules/bit-bin/dist/error/abstract-error.js:15:28)\n    at GeneralError.AbstractError (/usr/local/lib/node_modules/bit-bin/dist/error/abstract-error.js:45:116)\n    at new GeneralError (/usr/local/lib/node_modules/bit-bin/dist/error/general-error.js:27:114)\n    at _callee$ (/usr/local/lib/node_modules/bit-bin/dist/api/scope/lib/cat-component.js:74:19)\n    at tryCatch (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:17:14)"},"headers":{"version":"14.0.4"}}
```

```shell
// command
bit cmp cards/card-expandable

// results
{
    "name": "cards/card-expandable",
    "scope": "<ORG>.components",
    "versions": {
        "1.0.0": "23caed4839afdab697b7c6b94bef1cec6fb1c497",
        "1.0.1": "512a114c358c48ec7f1704ae382a739a807bd021",
        "1.0.2": "a7e50bd09d0737fe5472d988f4194e5107c641ea"
    },
    "lang": "javascript",
    "deprecated": false,
    "bindingPrefix": "@bit"
}
```

The three components that are a part of this namespace are (bit scopes/component-names)
```
cards
| - Card (cards/card)
| - CardComplex (cards/card-complex)
| - CardExpandable (cards/card-expandable)
```

**Comment by davidfirst** [comment]
Oh OK, I see. so, the component name I should have asked for was `cards/card`. 

In general, it seems to be like a bug and I'd like to reproduce it. If you can zip your workspace and send it to david@bit.dev, it'd be great.
The issue is that for some reason the file was deleted from the model. to get it back I can think of two possibilities:
1. re-tag the `cards/card` component.  (if the component is not modified, you'll need to add `--force` flag).
2. if the component was exported, try to re-import it.

**Comment by drewdecarme** [comment]
Ah nice, okay. I'll zip it up for you and send it over before I do any of those fixes that you mentioned.

**Comment by drewdecarme** [comment]
Results on those possible solutions:

```shell
# command
bit tag cards/card --force

# result
failed loading file src/app/cards/Card/index.spec.js from the model
```

```shell
# command
bit remove cards/card

# result
failed loading file src/app/cards/Card/index.spec.js from the model
```

```shell
# command
bit remove cards/card --force

# result
failed loading file src/app/cards/Card/index.spec.js from the model
```
