### ISSUE TITLE
exception when loading env after folder copy

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1585]
## Expected Behavior
Identify the case and re-import / re-link what needed

## Actual Behavior
An ugly exception the user can't handle himself.
```
error: bit failed to load bit.envs/compilers/react@7.0.5 with the following exception:
Cannot find module '../../../../../../has-own-property/bit.utils/1.0.0/dist/src/object/hasOwnProperty'.
Error: Cannot find module '../../../../../../has-own-property/bit.utils/1.0.0/dist/src/object/hasOwnProperty'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/Users/giladshoham/dev/bit/bit/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/private/tmp/env-load/wd2/.bit/components/compilers/react/bit.envs/7.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/7.0.3/node_modules/@bit/bit.utils.object.group-by/dist/src/object/hasOwnProperty.js:4:18)
    at Module._compile (/Users/giladshoham/dev/bit/bit/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/Users/giladshoham/dev/bit/bit/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/private/tmp/env-load/wd2/.bit/components/compilers/react/bit.envs/7.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/7.0.3/node_modules/@bit/bit.utils.object.group-by/dist/src/object/groupBy.js:8:23)
    at Module._compile (/Users/giladshoham/dev/bit/bit/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

## Steps to Reproduce the Problem
```sh
mkdir env-load
cd env-load
mkdir wd1
cd wd1
bit init
touch index.js
bit add index.js
bit import bit.envs/compilers/react -c
cd ../
cp -r wd1 ./wd2
cd wd2
bit status
```
This is probably related to the symlinks inside the .bit/components folder which aren't copied as expected.

## Specifications

  - Bit version: 14.0.6
  - Node version: 8.10.0
  - npm / yarn version: 6.8.0
  - Platform: mac
  - Bit compiler (include version):  bit.envs/compilers/react
  - Bit tester (include version): N/A

**Comment by davidfirst** [comment]
It's not easy to automatically fix this to the user. Instead, I added a new 'diagnose' to `bit doctor`, named "broken-symlink-files", which identify such cases and suggest a solution.
https://github.com/teambit/bit/pull/1590
