### ISSUE TITLE
getting 'bit failed to load' when tagging component 

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/bit#1607]
## Expected Behavior
Should tag, without errors

## Actual Behavior
```bash
❯ bit tag iframe/communicator
successfully installed the bit.envs/compilers/babel@0.0.20 compiler
error: bit failed to load bit.envs/compilers/babel@0.0.20 with the following exception:
Cannot find module '/Users/kutner/Documents/Projects/bitsrc/web/.bit/components/compilers/babel/bit.envs/0.0.20'.
Error: Cannot find module '/Users/kutner/Documents/Projects/bitsrc/web/.bit/components/compilers/babel/bit.envs/0.0.20'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (/usr/local/lib/node_modules/bit-bin/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Function._callee4$ (/usr/local/lib/node_modules/bit-bin/dist/extensions/base-extension.js:597:27)
    at tryCatch (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)
    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:147:5)

web git/master*  13s
❯ bit tag iframe/communicator
⡀⠀ importing components(node:92540) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2 component(s) tagged | 0 added, 1 changed, 1 auto-tagged
changed components:  bitsrc.ui/iframe/communicator@0.2.5
auto-tagged components (as a result of tagging their dependencies):  playground-client@0.0.2
```

## Steps to Reproduce the Problem
  1. import said component ```bitsrc.ui/iframe/communicator```
  1. modify component (i.e. add space)
  1. run ```bit tag iframe/communicator```
-> error occures

## Specifications

  - Bit version: 14.1.0
  - Node version: 11.13.0
  - npm / yarn version: yarn 1.15.2
  - Platform: MacOs

**Comment by GiladShoham** [comment]
@KutnerUri can you please share the full component name?

**Comment by KutnerBitsrc** [comment]
oh right my bad:
bitsrc.ui/iframe/communicator

**Comment by davidfirst** [comment]
After lots of investigation, this seems to be reproducible on node v11.13.0 only and only on the first import when the components of the environment are not there.
It doesn't happen on node v11.6.0 nor v11.14.0.
So, the workaround, for now, is either, upgrade node to v11.14.0 or run the import again.
I'm still investigating this but lowering the priority due to the above from critical to medium.

**Comment by KutnerUri** [comment]
Thanks for the update!
Odd that it is caused by Node itself, but at least it is reproducable.

בתאריך יום ו׳, 10 במאי 2019, 19:46, מאת David First ‏<
notifications@github.com>:
