### ISSUE TITLE
'bit commit...' causes an error

### ISSUE THREAD

**Issue by leon-good-life** [teambit/bit#180]
```
iMac:leonbit2 leon$ bit status
inline components
     > global/is-substring
     > is-substring/impl.js
                         

sources waiting for export
     > @this/global/is-substring - 1
iMac:leonbit2 leon$ bit commit is-substring 'initial commit'
⡀⠀ persisting...{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/bit/0.6.0/libexec/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/bit/0.6.0/libexec/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/bit/0.6.0/libexec/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
⠉⠩ persisting...

```

**Comment by GiladShoham** [comment]
Thanks for reporting.
Can you describe steps to reproduce, please?

**Comment by leon-good-life** [comment]
```
iMac:~ leon$ cd ~/Desktop/
iMac:Desktop leon$ mkdir is-substring
iMac:Desktop leon$ cd is-substring/
iMac:is-substring leon$ bit init
successfully initialized an empty bit scope.
iMac:is-substring leon$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (is-substring) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /Users/leon/Desktop/is-substring/package.json:

{
  "name": "is-substring",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes) 
iMac:is-substring leon$ npm install bit-javascript --save-dev

> fsevents@1.1.2 install /Users/leon/Desktop/is-substring/node_modules/fsevents
> node install

[fsevents] Success: "/Users/leon/Desktop/is-substring/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> caporal@0.5.0 postinstall /Users/leon/Desktop/is-substring/node_modules/caporal
> (test -f ./node_modules/husky/bin/install.js && node ./node_modules/husky/bin/install.js) || exit 0


> spawn-sync@1.0.15 postinstall /Users/leon/Desktop/is-substring/node_modules/spawn-sync
> node postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN is-substring@1.0.0 No description
npm WARN is-substring@1.0.0 No repository field.

+ bit-javascript@0.6.4
added 295 packages in 22.616s
iMac:is-substring leon$ bit create is-substring
created component "is-substring" in box "global"
iMac:is-substring leon$ open ./inline_components/global/is-substring/impl.js 
```

```javascript
module.exports = function isSubstring(str, containsStr) {
  return -1 !== str.indexOf(containsStr);
};
```

```
iMac:is-substring leon$ bit status
inline components
     > global/is-substring
                         

you don't have any sources to export
iMac:is-substring leon$ bit commit global/is-substring 'initial commit'
⡀⠀ persisting...{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/bit/0.6.0/libexec/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/bit/0.6.0/libexec/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/bit/0.6.0/libexec/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
⠅
```

**Comment by GiladShoham** [comment]
Thanks @leon-good-life 
I'll check it out.

Can you please try with the latest version of bit (0.6.5)?
Also, try to commit without the global/ only bit commit is-string "message"'

Thanks

**Comment by GiladShoham** [comment]
Fixed by:
https://github.com/teambit/bit/commit/4313a70e4771917369666b1fccb3e251876a2422
