### ISSUE TITLE
Not able to use babel-plugin-inline-import-data-uri in React compiler

### ISSUE THREAD

**Issue by dajocarter** [teambit/bit#1901]
### Describe the bug

I forked the [React compiler](https://bit.dev/bit/envs/compilers/react) in order to add `babel-plugin-inline-import-data-uri` to the `.babelrc` and `index.js` file as you can see [here](https://bit.dev/eaze/envs/compilers/react/~code). When using this as my compiler, `bit build` fails.

### Steps to Reproduce

1. Clone https://github.com/dajocarter/bit-babel-plugin-inline-import-data-uri
2. npm install
3. bit init
4. bit build address-details (fails)

### Expected Behavior

Running `bit build` should not fail with an error.

### Screenshots, exceptions and logs

```
$ bit build address-details
error: bit failed to build address-details with the following exception:
"reference" argument must be specified
Error: "reference" argument must be specified
    at Function.getContents (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/node_modules/babel-plugin-inline-import-data-uri/build/helper.js:66:15)
    at PluginPass.exit (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/node_modules/babel-plugin-inline-import-data-uri/build/index.js:31:45)
    at newFn (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/path/context.js:97:8)
    at TraversalContext.visitQueue (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/Users/davidc/Sites/bit-babel-plugin-inline-import-data-uri/.git/bit/components/compilers/react/eaze.envs/1.0.5/components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/node_modules/@babel/traverse/lib/index.js:76:12)
```

### Specifications

- Bit version: 14.2.3
- Node version: 10.16.0
- npm / yarn version: 6.10.0
- Platform: Mac OS 10.14.5
- Bit compiler (include version): eaze.envs/compilers/react@1.0.5
- Bit tester (include version): eaze.envs/testers/jest@22.4.5

### Additional context

I was able to build this component with eaze.envs/compilers/react@1.0.3, but needed to support the inline import of the svg data uri

**Comment by GiladShoham** [comment]
@dajocarter Hi,
A quick update:
I was able to reproduce the bug without bit at all.
It's something about the Babel programmatic API.
Here a quick demo:

update the bablerc (remove emotion plugin)
```json
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "inline-import-data-uri",
    "@babel/plugin-proposal-class-properties"
  ]
}
```
add a babel.js file (which just call babel progrematically)
```js
const fs = require('fs');
const { transform } = require('@babel/core');

const options = fs.readFileSync('./.babelrc');
const file = fs.readFileSync('./src/index.js');

const _runBabel = (file, options, distPath) => {
  const {
      code,
      map
  } = transform(file, options);
  console.log('im here')

  return code;
}

_runBabel(file.toString(), JSON.parse(options.toString()));
```
place it in the root and run it with `node babel.js`
You will see the same error.

My hunch says it's something about the fact that when calling the transform function we pass the actual content so it doesn't have the file path which I believe is the missing reference.
I'll continue checking if there is a way to pass this filepath/filename to transform.

**Comment by GiladShoham** [comment]
Another update:
Adding `options.filename = './src/index.js';` before calling the transform will solve the issue.
I'll check it a bit more, and if everything fine I'll update all the compilers uses babel behind the scene.

You don't have to wait for me, you can import the [babel-base-compiler](https://bit.dev/bit/envs/internal/babel-base-compiler) into the same workspace where you import the original react compiler, change it there, tag the base compiler (it should auto-tag your react fork if they are imported in the same workspace), then export them both.

**Comment by itaymendel** [comment]
improved babel support for bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
