### ISSUE TITLE
Bit build fails when the component imports another bit component from npm or yarn

### ISSUE THREAD

**Issue by VictorNicolasLO** [teambit/bit#2017]
### Describe the bug

When I try to build a new component which needs another component from bits installed via npm or yarn it fails and it shows an error

### Steps to Reproduce

1. Export a component
2. Use it in another component that you are going to export via yarn or npm
3. try to build or tag

### Expected Behavior
To build a component importing other components from npm or yarn

### Screenshots, exceptions and logs
This is the error when I try to build it. 

```
error: bit failed to build auth-app with the following exception:
error: component "woobydev.components/social-button@0.0.1" was not found
ComponentNotFound
    at /usr/local/lib/node_modules/bit-bin/dist/scope/scope.js:873:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:638:19)
```

### Specifications

- Bit version: 14.3.0
- Node version: v11.12.0
- npm / yarn version: 1.17.3
- Platform: Mac os
- Bit compiler (include version): bit.envs/compilers/typescript@3.0.29
- Bit tester (include version): None

### Additional context
It doesn't happen when I import the component via *bit import* just when I import via npm or yarn

**Comment by itaymendel** [comment]
are you able to properly install components using npm/yarn?
does this error happen when you `import <component> from '<component>'`?

**Comment by VictorNicolasLO** [comment]
> are you able to properly install components using npm/yarn?
> does this error happen when you `import <component> from '<component>'`?

I think that I am able to install components because I can run and build my project using *bits* components just from npm/yarn and yes, it happens when I `import <component> from '@bit/<component>'

**Comment by itaymendel** [comment]
can you please paste here the exact `import` statement you use in your code?

**Comment by VictorNicolasLO** [comment]
import SocialButtons from '@bit/semantic-org.semantic-ui-react.button';
and the console display this
```
error: bit failed to build auth-app with the following exception:
error: component "semantic-org.semantic-ui-react/button@0.86.0" was not found
ComponentNotFound
    at /usr/local/lib/node_modules/bit-bin/dist/scope/scope.js:873:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:638:19)
```
where `auth-app` is the component that I want to build/tag

**Comment by VictorNicolasLO** [comment]
> Hey @VictorNicolasLO
> If I understand, you try to tag and export a component that uses another component that was installed with npm/yarn, I try something like this and everything worked.
> 
> * I create a new React project and install this [component](https://bit.dev/semantic-org/semantic-ui-react/button).
> * I create a new component (the example below).
> * Imported the [React compiler](https://bit.dev/bit/envs/compilers/react).
> * Build & tag & export.
> 
> ```
> import React from 'react';
> import SocialButtons from '@bit/semantic-org.semantic-ui-react.button'
> 
> const style = <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/semantic-ui@2.4.1/dist/semantic.min.css'/>
> 
> function NewComp() {
>     return (
>         <div>
>             {style}
>             <h1>Test Component</h1>
>             <SocialButtons circular color='facebook' icon='facebook' />
>             <SocialButtons circular color='twitter' icon='twitter' />
>             <SocialButtons circular color='linkedin' icon='linkedin' />
>             <SocialButtons circular color='google plus' icon='google plus' />
>         </div>
>     );
> }
> 
> export default NewComp;
> ```
> 
> If I don't understand well, please give me more details so I can reproduce the error.
> Upload the `package.json` and the `.bitmap` if you can, it can help me to understand.

Thanks @JoshK2
 I found that the compiler `bit.envs/compilers/typescript@3.0.32` may be causing this error, anyway I made a repository where you can replicate this error 

https://github.com/VictorNicolasLO/bit-test-issue

You can replicated trying this
``` bash
$ bit import bit.envs/compilers/typescript -c
$ bit add ./src/components/test-component
$ bit tag test-component
```

**Comment by JoshK2** [comment]
Hey @VictorNicolasLO, the component from semantic-ui has cyclic dependencies with image and label component and this is causing another problem.
But I see that you try to work with this [component](https://bit.dev/woobydev/components/social-button), so I clone your repo and tried it, and the bug is fixed with a new version of Bit, currently is in dev version and it will be released in few days, but you can install the dev version `npm i bit-bin@dev -g` to solve the problem.

You can see the error with the older version and the build is passing with the new version:
![image](https://user-images.githubusercontent.com/35892475/66041221-0cecb900-e522-11e9-821b-9d190f670dce.png)

I created a pull request to your test project that works with the new Bit version
https://github.com/VictorNicolasLO/bit-test-issue/pull/1

Also, you need to set `react` and `react-dom` as peer dependencies because the consumer project environment has already installed these packages as normal dependencies. 
[React Guidelines
](https://docs.bit.dev/docs/react-guidelines#add-react-libraries-as-peer-dependencies-with-relaxed-versions)

**Comment by VictorNicolasLO** [comment]
> Hey @VictorNicolasLO, the component from semantic-ui has cyclic dependencies with image and label component and this is causing another problem.
> But I see that you try to work with this [component](https://bit.dev/woobydev/components/social-button), so I clone your repo and tried it, and the bug is fixed with a new version of Bit, currently it's a dev version and it will be released in few days, but you can install the dev version `npm i bit-bin@dev -g` to solve the problem.
> 
> You can see the error with the older version and the build is passing with the new version:
> ![image](https://user-images.githubusercontent.com/35892475/66041221-0cecb900-e522-11e9-821b-9d190f670dce.png)
> 
> I created a pull request to your test project that works with the new Bit version
> [VictorNicolasLO/bit-test-issue#1](https://github.com/VictorNicolasLO/bit-test-issue/pull/1)
> 
> Also, you need to set `react` and `react-dom` as peer dependencies because the consumer project environment has already installed these packages as normal dependencies.
> [React Guidelines ](https://docs.bit.dev/docs/react-guidelines#add-react-libraries-as-peer-dependencies-with-relaxed-versions)

Tanks @JoshK2 now it works !
