### ISSUE TITLE
error on exporting component having another bit component imported from a different collection on remote server

### ISSUE THREAD

**Issue by rbalet** [teambit/bit#2049]
### Describe the bug

When I'm exporting a component to a remote server which have imported component from an another collection on this server the export fails with.

### Steps to Reproduce

1.  create 2 remote collection (firstCollection and secondCollection)
2. create 1 component and export it to the first remote collection (first-component to firstCollection)
3. create the second component, import into it the first component 
_I'm using bit with angular so it's look like_
```ts
import { CommonModule } from '@angular/common'
import { NgModule } from '@angular/core'
import { FirstComponent} from '@bit/firstCollectio.first-component
import { SecondComponent } from './second-component.component'

@NgModule({
  declarations: [SecondComponent],
  imports: [CommonModule, FirstComponent],
})
export class SecondComponentModule {}
```
4. exporting it to the secondCollection `bit export secondCollection`

### Expected Behavior

exporting the new created component

### Screenshots, exceptions and logs
In the cmd
```bash
error: received an invalid response from the remote SSH server.
to see the invalid response, have a look at the log, located at C:\Users\myName\AppData\Local\Bit\logs\debug.log

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```

in the debug.log
```log
2019-10-02T09:46:55.644Z [34mdebug[39m: ssh, reading ssh key at C:\Users\myName/.ssh/id_rsa 
2019-10-02T09:46:55.648Z [34mdebug[39m: ssh, failed to connect using ssh-key. SSH key not found in `~/.ssh/id_rsa` or `ssh_key_file` config in `bit config` either not configured or refers to wrong path. 
2019-10-02T09:46:55.648Z [34mdebug[39m: ssh, trying to connect using user-password 
2019-10-02T09:47:30.735Z [34mdebug[39m: ssh, authenticated successfully using user-password 
2019-10-02T09:47:30.742Z [34mdebug[39m: ssh: going to run a remote command _put, path: /home/bit/components 
2019-10-02T09:47:32.694Z [34mdebug[39m: ssh: exit. Exit code: 0 
2019-10-02T09:47:32.695Z [34mdebug[39m: ssh: returned with code: 0, signal: undefined. 
2019-10-02T09:47:32.698Z [31merror[39m: unpackCommand found on error "SyntaxError: Unexpected token � in JSON at position 0", while parsing the following string: [90musername[39m[90m: [39m  
2019-10-02T09:47:32.703Z [33mwarn[39m: exportMany, failed pushing ids to the bare-scope 
2019-10-02T09:47:32.705Z [31merror[39m: got an error from command export [remote] [id...]: SSHInvalidResponse. Error serialized: {"stack":"SSHInvalidResponse\n    at SSH._unpack (C:\\Users\\myName\\AppData\\Roaming\\npm\\node_modules\\bit-bin\\dist\\scope\\network\\ssh\\ssh.js:627:13)\n    at exec.then.data (C:\\Users\\myName\\AppData\\Roaming\\npm\\node_modules\\bit-bin\\dist\\scope\\network\\ssh\\ssh.js:638:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","name":"SSHInvalidResponse","isUserError":true,"response":"\u001b[90musername\u001b[39m\u001b[90m: \u001b[39m ","showDoctorMessage":true} 
2019-10-02T09:47:32.853Z [31merror[39m: User gets the following error: error: received an invalid response from the remote SSH server.
to see the invalid response, have a look at the log, located at C:\Users\myName\AppData\Local\Bit\logs\debug.log

run 'bit doctor' to get detailed workspace diagnosis and issue resolution. 
2019-10-02T09:47:32.856Z [31merror[39m: [*] the command export [remote] [id...] has been terminated with an error code 1 
```

### Specifications

- Bit version:14.4.0
- Node version: 10.16.3
- npm / yarn version: 6.11.3
- Platform: vsCode
- Bit compiler (include version): bit.envs/compilers/angular@0.2.0
- Bit tester (include version): none

### Additional context

I'm using test, but don't look like angular have a tester and I already push others component and that wasn't never a problem.
I've added all the peerDependencies (also try to add firstComponent as dependencie)

**Comment by GiladShoham** [comment]
Are you trying to export into your own server or to bit.dev server?
It looks like some issue with authentication which results a bad response format.
If you are running it against bit.dev, can you try to authenticate using `bit login` command and run the export again?

**Comment by rbalet** [comment]
I'm running on my own server

**Comment by GiladShoham** [comment]
can you try some other operations against the remote server like `bit ls [remote-scope]`?
I look like you didn't configure your ssh keys in the authorized keys on the server.
See the note here:
https://docs.bit.dev/docs/bit-server.html#server-setup
You might also want to take a look at this repo as an example:
https://github.com/teambit/bit-docker

**Comment by rbalet** [comment]
I migrate my project on the bit.dev server since it's easier and prettier.
But, It's make sense since I forget to configure the ssh keys so I close this issue.

Thx and sorry for the disturbance

**Comment by cloudsoh** [comment]
```
2019-10-10T09:05:39.285Z ^[[34mdebug^[[39m: ssh, trying to connect using ssh-agent
2019-10-10T09:05:39.389Z ^[[34mdebug^[[39m: ssh, authenticated successfully using ssh-agent
2019-10-10T09:05:39.444Z ^[[34mdebug^[[39m: ssh: going to run a remote command _put, path: /opt/bit/asd
2019-10-10T09:05:40.755Z ^[[34mdebug^[[39m: ssh: exit. Exit code: 0
2019-10-10T09:05:40.756Z ^[[34mdebug^[[39m: ssh: returned with code: 0, signal: undefined.
2019-10-10T09:05:40.758Z ^[[31merror^[[39m: unpackCommand found on error "SyntaxError: Unexpected token � in JSON at position 0", while parsing the following string: ^[[90musername^[[39m^[[90m: ^[[39m
2019-10-10T09:05:40.760Z ^[[33mwarn^[[39m: exportMany, failed pushing ids to the bare-scope
2019-10-10T09:05:40.761Z ^[[31merror^[[39m: got an error from command export [remote] [id...]: SSHInvalidResponse. Error serialized: {"stack":"SSHInvalidResponse\n    at SSH._unpack (/usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:627:13)\n    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:638:16\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","name":"SSHInvalidResponse","isUserError":true,"response":"\u001b[90musername\u001b[39m\u001b[90m: \u001b[39m ","showDoctorMessage":true}
2019-10-10T09:05:40.810Z ^[[31merror^[[39m: User gets the following error: error: received an invalid response from the remote SSH server.
to see the invalid response, have a look at the log, located at /Users/cloud/Library/Caches/Bit/logs/debug.log
```

I have ssh agent setup-ed. But still facing this issue, the problem does not happen when I export in the `bit-react-tutorial`. But it happens when I am trying to customize the `typescript-compiler`.

**Comment by davidfirst** [comment]
@cloudsoh , are you trying to export to `bit.dev` or to a self-hosted scope? according to the log, it seems more like the latter, if so, what happens when you ssh to that resource without using Bit?
