### ISSUE TITLE
bit status AssertionError

### ISSUE THREAD

**Issue by eric-blue** [teambit/bit#2111]
### Describe the bug

`bit status` fails, producing an `AssertionError`, while `bit build` and `bit test` run fine. The error seems to be within bit-bin's dependency blue-bird

### Steps to Reproduce

1. Run bit status

### Expected Behavior

Expected to be able to run bit status. This might be a local issue, but the error log doesn't allude to any method of determining that.

### Screenshots, exceptions and logs

```
$ bit status
AssertionError [ERR_ASSERTION]: Code: ERR_INVALID_ARG_TYPE; The provided arguments length (1) does not match the required ones (3).
    at getMessage (internal/errors.js:220:5)
    at new NodeError (internal/errors.js:159:13)
    at cloneErrorObject (/usr/local/lib/node_modules/bit-bin/dist/error/clone-error-object.js:27:15)
    at hashErrorIfNeeded (/usr/local/lib/node_modules/bit-bin/dist/error/hash-error-object.js:63:55)
    at sendToAnalyticsAndSentry (/usr/local/lib/node_modules/bit-bin/dist/cli/default-error-handler.js:716:62)
    at _default (/usr/local/lib/node_modules/bit-bin/dist/cli/default-error-handler.js:740:3)
    at migrateWrapper.then.catch.err (/usr/local/lib/node_modules/bit-bin/dist/cli/command-registrar.js:215:61)
    at tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:15:14)
```

### Specifications

- Bit version: 14.4.3
- Node version: 10.15.3
- npm / yarn version: npm 6.12.1
- Platform: macOS 
- Bit compiler (include version): `bit.envs/compilers/react-typescript@3.0.6`
- Bit tester (include version): `bit.envs/testers/jest@22.4.3`

### Additional context

Tried clearing `node_modules`/`package-lock.json`

**Comment by davidfirst** [comment]
Hi @eric-blue , I'd like to try to reproduce it. 
Any chance you can send me a reproducible workspace zipped? (david@bit.dev).

In the meanwhile, according to the error message, it seems to be related somehow to the error reporting service, so disabling it (by running `bit config set error_reporting false`) could resolve the issue.

bit config set error_reporting false
