### ISSUE TITLE
Typescript conviler fails on build

### ISSUE THREAD

**Issue by Rumpelstinsk** [teambit/bit#2186]
### Describe the bug

I'm trying to upload a typescript-component to bit. Howver every time I try to do `bit build` it throws a exception.

### Steps to Reproduce

1. Create a new react-app with typescript: `npx create-react-app my-app --template typescript`
2. Create a folder for the component `mkdir .\my-app\src\components\TaskForm`
3. Create a file for typescript intefaces `......\TaskFork\types.ts` with the next content
```
export interface ITaskFormTask{
    [key:string]:string;
    title: string;
    description: string;
}

export interface ITaskFormProps {
    addANewTask: (task: ITaskFormTask) => void;
}

export interface ITaskFormState {
    task: ITaskFormTask;
    showError: boolean;
}
```
4. Create a file for the component `......\TaskFork\index.tsx` with the next content:
```
import React, { Component } from 'react';
import * as TYPES from './types';

export { TYPES as TaskFormTypes };

export class TaskForm extends Component<TYPES.ITaskFormProps, TYPES.ITaskFormState> {
    private emptyTask:TYPES.ITaskFormTask = {description: "", title: ""};

    constructor(props: TYPES.ITaskFormProps) {
        super(props);
        this.state = {
            task: this.emptyTask,
            showError: false
        };
    }

    private handleNewTask(e: React.FormEvent<HTMLFormElement>):void {
        e.preventDefault();
        let newTask: TYPES.ITaskFormTask = {
            title: this.state.task.title,
            description: this.state.task.description
        };
        this.props.addANewTask(newTask);

        this.setState({
            task: this.emptyTask
        });
    }

    private handleOnChange(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>):void {
        let {name, value} = e.target;
        let task:TYPES.ITaskFormTask = Object.assign({}, this.state.task);
        task[name] = value;        
        this.setState({task});
    }
    public render(): JSX.Element {
        return (
            <div className="card card-body">
                <form onSubmit={e => this.handleNewTask(e)}>
                    <div className="form-group">
                        <input
                            type="text"
                            name="title"
                            className="form-control"
                            placeholder="TaskTitle"
                            onChange={e => this.handleOnChange(e)}
                            value={this.state.task.title} />
                    </div>

                    <div className="form-group">
                        <textarea
                            name="description"
                            className="form-control"
                            placeholder="Task description"
                            value={this.state.task.description}
                            onChange={e => this.handleOnChange(e)} ></textarea>

                    </div>
                    <button type="submit" className="btn btn-primary btn-block">Save</button>

                </form>
            </div>
        )
    }
}
```
5. Init bit: `bit init`
6. Import react compiler: `bit import bit.envs/compilers/react -c`
7. Import react-typescript-compiler: `bit import -c bit.envs/compilers/react-typescript`
8. Add component to collection: `bit add .\src\components\TaskForm`
9. Build the project: `bit build` and see the exception

### Expected Behavior
Build correctly without exception.

### Screenshots, exceptions and logs

After `bit build`, the next exeption is shown in the console:

> error: bit failed to build task-form with the following exception:
> Cannot read property 'endsWith' of undefined
> TypeError: Cannot read property 'endsWith' of undefined
>     at C:\Proyectos\bit\sample_colection\my-app\.bit\components\compilers\react-typescript\bit.envs\3.1.17\components\.dependencies\compilers\typescript\bit.envs\3.1.13\dist\ts-compiler\src\compile.js:142:28
>     at Array.find (<anonymous>)
>     at findMainFile (C:\Proyectos\bit\sample_colection\my-app\.bit\components\compilers\react-typescript\bit.envs\3.1.17\components\.dependencies\compilers\typescript\bit.envs\3.1.13\dist\ts-compiler\src\compile.js:137:21)
>     at C:\Proyectos\bit\sample_colection\my-app\.bit\components\compilers\react-typescript\bit.envs\3.1.17\components\.dependencies\compilers\typescript\bit.envs\3.1.13\dist\ts-compiler\src\compile.js:120:32
>     at step (C:\Proyectos\bit\sample_colection\my-app\.bit\components\compilers\react-typescript\bit.envs\3.1.17\components\.dependencies\compilers\typescript\bit.envs\3.1.13\dist\ts-compiler\src\compile.js:32:23)
>     at Object.next (C:\Proyectos\bit\sample_colection\my-app\.bit\components\compilers\react-typescript\bit.envs\3.1.17\components\.dependencies\compilers\typescript\bit.envs\3.1.13\dist\ts-compiler\src\compile.js:13:53)  
>     at fulfilled (C:\Proyectos\bit\sample_colection\my-app\.bit\components\compilers\react-typescript\bit.envs\3.1.17\components\.dependencies\compilers\typescript\bit.envs\3.1.13\dist\ts-compiler\src\compile.js:4:58)

### Specifications

- Bit version: 14.6.0
- Node version: 12.4.0
- npm version: 6.11.3
- Platform: Visual Studio Code
- Bit compiler (include version): Last version of both compilers.

**Comment by GiladShoham** [comment]
this issue is related to the compiler itself, moving to the envs repo.
