### ISSUE TITLE
Bit import is giving me error: received an invalid response from the remote SSH server.

### ISSUE THREAD

**Issue by rubenofen** [teambit/bit#2199]
When I do a bit import it is giving me an ssh error

### Steps to Reproduce

1. launch bit import from a monorepo project

### Expected Behavior

the components are imported

### Specifications
  bit version   : 14.7.1
  node version  : v12.13.1
  npm version   : 6.12.1
  yarn version  : 1.19.1
  platform      : win32
  user details  : rubenofen<rubenofen@gmail.com>

║ category           │ name                            │ description                                            │ status ║
║ configuration      │ validate workspace's bit config │ validate workspace configuration object                │ passed ║
║ vendors            │ validate git exec               │ validate that git executable found                     │ passed ║
║ internal store     │ check orphan refs               │ checks for empty internal refs in local workspace      │ passed ║
║ local environments │ check environment symlinks      │ validate generated symlinks for workspace environments │ passed ║
║ vendors            │ validate npm exec               │ validate that npm executable found                     │ passed ║
║ vendors            │ validate yarn exec              │ validate that yarn executable found                    │ passed ║
║ core               │ validate bit version            │ validate that bit version is up to date                │ passed ║

### Additional context

part of log doc:

2019-12-17T08:57:54.767Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-file-uploader, however version 0.0.27 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-icons, however version 1.0.17 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-menu, however version 0.0.22 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-modal-plus-dialog, however version 0.0.28 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-modal, however version 1.0.22 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-monoselect, however version 0.0.24 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-pagination, however version 1.0.34 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-progress-bar, however version 0.0.16 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-radio-button, however version 1.0.19 object was not found on the filesystem 
2019-12-17T08:57:54.768Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-reset-filter, however version 1.0.12 object was not found on the filesystem 
2019-12-17T08:57:54.769Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-search, however version 0.0.14 object was not found on the filesystem 
2019-12-17T08:57:54.769Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-table, however version 0.0.30 object was not found on the filesystem 
2019-12-17T08:57:54.769Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-toast, however version 0.0.10 object was not found on the filesystem 
2019-12-17T08:57:54.769Z [34mdebug[39m: sources.get, found ancert.ancert-ui/aui-yes-no-dialog, however version 0.0.28 object was not found on the filesystem 
2019-12-17T08:57:55.325Z [34mdebug[39m: getExternalOnes, getExternalOnes: 24 left. Fetching them from a remote 
2019-12-17T08:57:55.326Z [34mdebug[39m: [-] Running fetch (withoutDeps: true) on a remote 
2019-12-17T08:57:55.328Z [34mdebug[39m: Establishing a new SSH connection to ssh://bit@hub.bit.dev:ancert.ancert-ui 
2019-12-17T08:57:55.329Z [34mdebug[39m: ssh, trying to connect using token 
2019-12-17T08:57:56.987Z [34mdebug[39m: ssh, authenticated successfully using token 
2019-12-17T08:57:56.987Z [34mdebug[39m: ssh: going to run a remote command _fetch --no-dependencies, path: ancert.ancert-ui 
2019-12-17T08:58:45.899Z [34mdebug[39m: ssh: returned with code: undefined, signal: undefined. 
2019-12-17T08:58:45.926Z [31merror[39m: got an error from command import [ids...]: SSHInvalidResponse. Error serialized: {"stack":"SSHInvalidResponse\n    at parseResponse (C:\\Users\\rsahagun\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\bit-bin\\dist\\scope\\network\\ssh\\ssh.js:846:19)\n    at C:\\Users\\rsahagun\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\bit-bin\\dist\\scope\\network\\ssh\\ssh.js:853:13\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","isUserError":true,"name":"SSHInvalidResponse","response":"<--- Last few GCs --->\n\n[2656:0x3e6c610]    43129 ms: Mark-sweep 1503.3 (1560.3) -> 1503.2 (1565.3) MB, 1103.4 / 0.0 ms  allocation failure GC in old space requested\n[2656:0x3e6c610]    44209 ms: Mark-sweep 1503.2 (1565.3) -> 1503.0 (1534.8) MB, 1079.1 / 0.0 ms  last resort GC in old space requested\n[2656:0x3e6c610]    45308 ms: Mark-sweep 1503.0 (1534.8) -> 1503.0 (1534.8) MB, 1098.8 / 0.0 ms  last resort GC in old space requested\n\n\n<--- JS stacktrace --->\n\n==== JS stack trace =========================================\n\nSecurity context: 0x2977e1825891 <JSObject>\n    0: builtin exit frame: stringify(this=0x2977e1818349 <Object map = 0xf4dac848d9>,0x2c5830b822d1 <undefined>,0x2c5830b822d1 <undefined>,0x3bedbd6ece61 <Object map = 0xf4dace3051>)\n\n    1: arguments adaptor frame: 1->3\n    2: toString [/usr/local/share/.config/yarn/global/node_modules/bit-bin/dist/scope/component-objects.js:70] [bytecode=0x137b348569e9 offset=86](this=0xb968d3fcc91 <ComponentO...\n\n","showDoctorMessage":true} 
2019-12-17T08:58:46.211Z [31merror[39m: User gets the following error: error: received an invalid response from the remote SSH server.
to see the invalid response, have a look at the log, located at C:\Users\rsahagun\AppData\Local\Bit\logs\debug.log

run 'bit doctor' to get detailed workspace diagnosis and issue resolution. 
2019-12-17T08:58:46.217Z [31merror[39m: [*] the command import [ids...] has been terminated with an error code 1

**Comment by GiladShoham** [comment]
@rubenofen Thanks for reporting this.
It looks like some out of memory error in our servers.
We change some memory configuration on our side.
Can you please try again and update us?

Thanks.

**Comment by rubenofen** [comment]
Sorry, but it is crashing yet.

**Comment by GiladShoham** [comment]
@rubenofen 
Thanks for the update.
Is there an option for you to give me read permission to your collection? 
and maybe the .bitmap file?
That will be very helpful in order to debug this issue.
If it's possible, please give gilad@bit.dev read permission.
Thanks.

**Comment by rubenofen** [comment]
Hello Gilad, we have gived you access to the collection.
https://bit.dev/ancert/ancert-ui

**Comment by rubenofen** [comment]
Hello Gilad, Did you get a chance to look at this?

**Comment by GiladShoham** [comment]
Sorry, I'll check it.
Is there a chance to get the .bitmap file?
(you can send it privately to gilad@bit.dev)
Thanks.

**Comment by rubenofen** [comment]
Hello Gilad,

Thank you but we have found the problem.
We had updoaded a **.exe** file inside aui-icons/assets and after that the import command started to fail. Thus, it would be possible to block or give an error when a .exe file is uploading to bit, to avoid this type of issues.

Thank you.

**Comment by GiladShoham** [comment]
@rubenofen Thanks for the update.
If you can open a feature request about it (and reference this issue), it will be great.
Thanks.

**Comment by rubenofen** [comment]
Done
