### ISSUE TITLE
Bit import on fresh install MacOS gives obscure error

### ISSUE THREAD

**Issue by ezbz** [teambit/bit#222]
OS: MacOS 10.12.6
Shell: zsh 5.3.1 (x86_64-apple-darwin16.6.0)
Installed bit via `sudo npm install bit-bin --global`

Bit config, init and status pass ok but when I try to import I get the following:
```
~/d/bitsrc ❯❯❯ bit import bit.utils/validator/is-email
Error
    at unpackCmd (/usr/local/lib/node_modules/bit-bin/dist/utils/unpack-command.js:15:11)
    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:247:75
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

When I  go to `unpackCmd (/usr/local/lib/node_modules/bit-bin/dist/utils/unpack-command.js:15:11)` and change line 15 from:

`    throw new Error(str);`
to
`    throw new Error(err);`

And run again I get:

```
~/d/bitsrc ❯❯❯ bit import bit.utils/validator/is-email
Error: SyntaxError: Unexpected end of JSON input
    at unpackCmd (/usr/local/lib/node_modules/bit-bin/dist/utils/unpack-command.js:15:11)
    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:247:75
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Proper validation error handling is needed here for configuration issues

**Comment by GiladShoham** [comment]
Thanks, @ezbz for reporting this issue.

few comments about the issue:

1. Can you please share your bit version? (run bit -V in terminal). if it's lower than 0.10.5 I suggest you upgrade to version 0.10.5 (released yesterday)
2. bit.utils is an old scope which is not backward compatible, we will update this scope in a few days (and we will notify you right after)
3. Regarding the unpack cmd error, we just took care of this in version 0.10.5, now you should get a better error in the terminal, and the real error should be written into bit logs which you can find in this path:
```
~/Library/Caches/Bit/logs/debug.log
```

**Comment by ezbz** [comment]
```
~/d/bitsrc ❯❯❯ bit -V
0.10.4
~/d/bitsrc ❯❯❯ bit import bit.utils/validator/is-email
Error: SyntaxError: Unexpected end of JSON input
    at unpackCmd (/usr/local/lib/node_modules/bit-bin/dist/utils/unpack-command.js:15:11)
    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:247:75
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
~/d/bitsrc ❯❯❯ more ~/Library/Caches/Bit/logs/debug.log                                                                                              ⏎

2017-08-17T11:53:20.868Z - info: [*] started a new command: "import [ids...]" with the following data: args=[0=bit.utils/validator/is-email], tester=undefined, verbose=undefined, compiler=undefined, prefix=undefined, display_dependencies=undefined
2017-08-17T11:53:21.365Z - debug: importSpecificComponents, Ids: bit.utils/validator/is-email
2017-08-17T11:53:21.368Z - debug: scope.getManyWithAllVersions, Ids: bit.utils/validator/is-email@latest
2017-08-17T11:53:21.369Z - debug: scope.importMany: bit.utils/validator/is-email@latest
2017-08-17T11:53:21.369Z - debug: sources.getMany, Ids:
2017-08-17T11:53:21.369Z - debug: scope.importMany: successfully fetched local components and their dependencies. Going to fetch externals
2017-08-17T11:53:21.370Z - debug: Planning to run a hook post_export_hook with a method post
2017-08-17T11:53:21.370Z - debug: Planning to run a hook post_import_hook with a method post
2017-08-17T11:53:21.375Z - warn: Failed running the post_import_hook hook as destUrl is not set in the config file
2017-08-17T11:53:21.378Z - debug: getExternalMany, planning on fetching from remote scope. Ids: bit.utils/validator/is-email@latest
2017-08-17T11:53:21.378Z - debug: sources.getMany, Ids: bit.utils/validator/is-email@latest
2017-08-17T11:53:21.379Z - debug: Failed reading a ref file /Users/erezmazor/dev/bitsrc/.bit/objects/9c/47b39a1e6d56ba1dfcb2bd81fbe9221d57010d
2017-08-17T11:53:21.380Z - debug: getExternalMany: 1 left. Fetching them from a remote
2017-08-17T11:53:21.381Z - debug: [-] Running fetch or fetchOnes on a remote
2017-08-17T11:53:24.890Z - error:  Error: SyntaxError: Unexpected end of JSON input
    at unpackCmd (/usr/local/lib/node_modules/bit-bin/dist/utils/unpack-command.js:15:11)
    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:247:75
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2017-08-17T11:53:24.913Z - error: [*] the command has been terminated with an error code 1
```

**Comment by GiladShoham** [comment]
Thanks @ezbz 

This component won't work for now since it's an old component.
I'll update this thread once we will update it.

Regarding the unpack cmd error, you should get a better error.
It's a bug, and I added it to our todo list.

**Comment by GiladShoham** [comment]
@ezbz this should work now, with the latest version of bit (0.10.6) and the current utils scope on bitsrc.io
I'm closing this, if it's still happening to you i'll open it again.
