### ISSUE TITLE
better output for bit test

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2234]
I am running `bit test`, and the `build` fail, producing this unreadable output:

```
❯ bit test base/button
error: bit failed to build bit.gui/base/button@0.0.6 with the following exception:
Command failed with exit code 2 (ENOENT): /Users/kutner/Documents/Projects/sandbox-playground/.git/bit/components/compilers/react-typescript/bit.envs/3.1.27/components/.dependencies/compilers/typescript/bit.envs/3.1.21/node_modules/typescript/bin/tsc -d
Error: Command failed with exit code 2 (ENOENT): /Users/kutner/Documents/Projects/sandbox-playground/.git/bit/components/compilers/react-typescript/bit.envs/3.1.27/components/.dependencies/compilers/typescript/bit.envs/3.1.21/node_modules/typescript/bin/tsc -d
    at makeError (/Users/kutner/Documents/Projects/sandbox-playground/.git/bit/components/compilers/react-typescript/bit.envs/3.1.27/components/.dependencies/compilers/typescript/bit.envs/3.1.21/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/kutner/Documents/Projects/sandbox-playground/.git/bit/components/compilers/react-typescript/bit.envs/3.1.27/components/.dependencies/compilers/typescript/bit.envs/3.1.21/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From previous event:
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at getBuildResults (/Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:611:22)
    at /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:615:32
    at Generator.next (<anonymous>)
From previous event:
    at _runBuild2 (/Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:621:21)
    at _runBuild (/Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:470:21)
    at /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:403:14
    at Generator.next (<anonymous>)
From previous event:
    at _build2 (/Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:435:18)
    at _build (/Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:368:18)
    at /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:248:35
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at buildComponent (/Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:290:28)
    at /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component/consumer-component.js:1021:44
    at Generator.next (<anonymous>)
From previous event:
    at Component.build (/Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/consumer/component/consumer-component.js:1032:7)
    at /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/scope/scope.js:531:27
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/scope/scope.js:547:23)
    at /Users/kutner/.config/yarn/global/node_modules/p-map-series/index.js:8:26
    at /Users/kutner/.config/yarn/global/node_modules/p-reduce/index.js:16:10
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This is unlike the pretty output from `bit build`:
```
❯ bit build base/button           
⠍⠀ isolating component - base/buttonbutton.spec.tsx:8:1 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

8 it('should render', () => {
  ~~

button.spec.tsx:14:1 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

14 it('should trigger onClick', () => {
   ~~

button.spec.tsx:25:1 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

25 it('should remove loader after onClick has been resolved', async () => {
   ~~

button.spec.tsx:44:1 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

44 it('should remove loader even when onClick has been rejected', async () => {
   ~~
```

**Worse still**, I don't have a tester defined!
`bit test` should do nothing when tester is undefined

### reference 
  bit version   : 14.7.1
  node version  : v12.12.0
  npm version   : 6.13.4
  yarn version  : 1.19.1
  platform      : darwin

**Comment by GiladShoham** [comment]
you are right. we will fix it

**Comment by itaymendel** [comment]
improved in v15
