### ISSUE TITLE
Cannot build component that uses styled-components

### ISSUE THREAD

**Issue by makeupsomething** [teambit/bit#2312]
## Description

I have created a project from scratch with create-react-app. Set up the project for bit following the docs. I built a simple button component that is styled with styled components but I cannot build it with `built build`. I get a long list of errors. Running `bit test` I get an error output like so

``` 
error: bit failed to build fancy-button with the following exception:
Command failed with exit code 2 (ENOENT): /Users/darylcole/Documents/projects/syns-component-library/.git/bit/components/compilers/react-typescript/bit.envs/3.1.44/components/.dependencies/compilers/typescript/bit.envs/3.1.39/node_modules/typescript/bin/tsc --declaration
Error: Command failed with exit code 2 (ENOENT): /Users/darylcole/Documents/projects/syns-component-library/.git/bit/components/compilers/react-typescript/bit.envs/3.1.44/components/.dependencies/compilers/typescript/bit.envs/3.1.39/node_modules/typescript/bin/tsc --declaration
    at makeError (/Users/darylcole/Documents/projects/syns-component-library/.git/bit/components/compilers/react-typescript/bit.envs/3.1.44/components/.dependencies/compilers/typescript/bit.envs/3.1.39/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/darylcole/Documents/projects/syns-component-library/.git/bit/components/compilers/react-typescript/bit.envs/3.1.44/components/.dependencies/compilers/typescript/bit.envs/3.1.39/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Specifications

- Bit version: 14.7.3
- Node version:v12.13.1
- npm / yarn version:1.19.2
- Platform:macos
- Bit compiler (include version):bit.envs/compilers/react-typescript@3.1.44
- Bit tester (include version): n/a

### Context and additional information

Details for the button from `bit show`
```
╔═══════════════════╤════════════════════════════════════════════════════╗
║ Id                │ fancy-button                                       ║
╟───────────────────┼────────────────────────────────────────────────────╢
║ Compiler          │ bit.envs/compilers/react-typescript@3.1.44         ║
╟───────────────────┼────────────────────────────────────────────────────╢
║ Language          │ javascript                                         ║
╟───────────────────┼────────────────────────────────────────────────────╢
║ Main File         │ src/components/fancy-button/index.ts               ║
╟───────────────────┼────────────────────────────────────────────────────╢
║ Dependencies      │ @types/react@^16.9.0                               ║
║                   │ @types/styled-components@^4.4.2                    ║
╟───────────────────┼────────────────────────────────────────────────────╢
║ Dev Dependencies  │                                                    ║
╟───────────────────┼────────────────────────────────────────────────────╢
║ Peer Dependencies │ react@^16.11.0                                     ║
║                   │ styled-components@^5.0.1                           ║
║                   │ react-dom@^16.11.0                                 ║
║                   │ @types/react@16.9.11                               ║
║                   │ @types/react-dom@16.9.4                            ║
╟───────────────────┼────────────────────────────────────────────────────╢
║ Files             │ src/components/fancy-button/FancyButton.tsx        ║
║                   │ src/components/fancy-button/index.ts               ║
╚═══════════════════╧════════════════════════════════════════════════════╝
```

**Comment by itaymendel** [comment]
Hi @makeupsomething , I'm unable to reproduce it locally, can you please create a public github repo from your project and push the code, so I can see if it reproduces locally?

**Comment by makeupsomething** [comment]
Hi @itaymendel thank you for getting back to me!

I've reproduced it here in a simple app
https://github.com/makeupsomething/bit-test-app

I must be missing something simple with the setup but I have no idea what i missing :/

**Comment by makeupsomething** [comment]
Just an update on this.
When I set up a project in the exact same way but with javascript instead of typescript I can build with no issues.

**Comment by makeupsomething** [comment]
We can close this
The issue was same as this https://github.com/teambit/envs/issues/68
