### ISSUE TITLE
Bit build doesn't do anything

### ISSUE THREAD

**Issue by donnierisk** [teambit/bit#2319]
## Expected Behavior
I created a Vue component that has a dependancy on a scss file (Which is also a shared component), I use scss variables in my styles, whenever I run "bit build", it should build the component.

## Actual Behavior
hangs indefinitely with no information, it says "building component - <mycomponent>" even with --verbose. It has worked before twice out of the 7 times with the dependancy, if I remove the dependancy it builds again. The code looks exactly the same as when it worked before.

## Steps to Reproduce the Problem

  1. Create Vue app and add scss
  2. create bit component of scss file that contains variables
  3. create vue bit component that uses that scss as a dependancy

Example of code below:
**scss component (global/variables)**

```
$btn-bg-dark: #196476;
$btn-bg-light: #ffffff;
```

**Vue component**
```
<style lang="scss">
@import "~@bit/myusername.mycollection.global.variables";

.btn-primary {
  background: $btn-bg-light;
  color: $btn-bg-dark;
}

.dark .btn-primary {
  background: $btn-bg-dark;
  color: white;
}
</style>
```

## Specifications

 bit version   : 14.7.4
  node version  : v13.3.0
  yarn version  : 1.19.1
  - Platform: darwin
  - Bit compiler (include version): bit.envs/bundlers/vue@2.6.20
  - Bit tester (include version):

**Comment by octavius37** [comment]
I had a very similar experience, with 2.6.20 getting stuck at build. I used 2.6.15 to build successfully in the end. However my component did not have a direct scss import, but I was using Vuetify so it might still be related to the scss loader in the compiler.

**Comment by GiladShoham** [comment]
@donnierisk Thanks for reporting this.
We will check it.

**Comment by iansprice** [comment]
Experiencing the same with a Vue component with an image dependency

**Comment by iansprice** [comment]
```
// Folder structure:
//   - src
//      - components (has one javascript file; JS file is a Bit component)
//      - assets (has one png; folder is a Bit component)

$ bit build assets

⢈⠩ building component - assets
    at MemoryFileSystem.readdirSync (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/memory-fs/lib/MemoryFileSystem.js:128:10)
    at /home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/dist/vue/index.js:26:28
    at finalCallback (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/webpack/lib/Compiler.js:271:21)
    at /home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/webpack/lib/Compiler.js:671:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/Hook.js:154:20)
    at /home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/webpack/lib/Compiler.js:668:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/Hook.js:154:20)
    at /home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/webpack/lib/Compilation.js:1385:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/Hook.js:154:20)
    at /home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/webpack/lib/Compilation.js:1376:32
    at eval (eval at create (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/terser-webpack-plugin/dist/index.js:321:9
    at step (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
    at /home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/terser-webpack-plugin/dist/TaskRunner.js:111:15
    at tryCatcher (/home/ian/Documents/Programming/aquaseca_storybook/.git/bit/components/bundlers/vue/bit.envs/2.6.20/node_modules/bluebird/js/release/util.js:16:23)
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ModuleParseError'
    |     property 'origin' -> object with constructor 'MultiModule'
    |     property 'dependencies' -> object with constructor 'Array'
    |     ...
    |     property 'module' -> object with constructor 'NormalModule'
    --- property 'error' closes the circle
    at JSON.stringify (<anonymous>)
    at /home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/dist/cli/command-registrar.js:247:106
    at tryCatcher (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ian/.nvm/versions/node/v12.16.1/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

```

This calls the following from **fs-memory/lib/MemoryFileSystem.js** (the top line of the traceback). Looking into that there seems to be an error. 

```
MemoryFileSystem.prototype.readdirSync = function(_path) {
	if(_path === "/") return Object.keys(this.data).filter(Boolean);
	var path = pathToArray(_path);
	var current = this.data;      // **this.data is an empty object here**
	for(var i = 0; i < path.length - 1; i++) {
		if(!isDir(current[path[i]]))
                        // **This error is thrown if the command is forcefully exited; otherwise endless recursion**
			throw new MemoryFileSystemError(errors.code.ENOENT, _path);
		current = current[path[i]];
	}
```

Not sure if this is helpful at all, but seems to be related behavior

**Comment by cdholjes** [comment]
Had this issue when I added these 2 packages:
- stylus
- stylus-loader

After removing them and going back to plain css the build when through like normal
