### ISSUE TITLE
bit build breaks after merging 2 components into 1

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2365]
### Describe the bug

I have 2 components that were merged into one by another member of my team.
I pulled the changes that were made by that team member and ran `bit status`
I get the following:
```
your workspace has outdated objects. please use "bit import" to pull the latest objects from the remote scope
```
then I ran `bit import` and `bit checkout -a latest` to make sure that I got all the latest changes. bit import ran successfully and bit checkout said that i'm already up to date.

then I tried to tag my modified components and got the following error:
```
error: bit failed to build bit.marketing/concrete/icon-line@0.0.4 with the following exception:
unable to topological sort dependencies of bit.marketing/concrete/icon-line@0.0.4. Original error: topologicalSortComponentDependencies, bit.marketing/constants/_storagemodule@0.0.2 is missing
GeneralError
    at topologicalSortComponentDependencies (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/dist/scope/graph/components-graph.js:157:11)
    at /Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/dist/environment/isolator.js:279:69
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/oded/.nvm/versions/node/v10.15.3/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

I also tried to run `bit build -c` and got the same error. then I tried to build only the component that had the missing dependency using the following command: `bit build concrete/icon-line --skip-update -c`. it also gave the same error.
I tried to delete the `dist` folder and `bit build` but it also did not work.

when I looked into it, I saw that the component was not using the missing dependency directly, but it was a dependency of one of its dependencies.
```
concrete/icon-line -> concrete/image -> constants/storage
```

to solve this issue I tagged the components separately. `constants/storage` then `concrete/image` then `concrete/icon-line`. now im stuck in a loop because the dependency versions are changing all the time. [see issue here](https://github.com/teambit/bit/issues/2364)

### Specifications

- Bit version: 14.7.5-dev.1
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43

**Comment by itaymendel** [comment]
What does "merge components" mean? what was the exact command/workflow?
