### ISSUE TITLE
Error cannot find module when moving directory

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2402]
I moved my workdir (`mv ./eva-homepage ./pages/eva-homepage`).
Trying to run `bit s`, I get this error:

```bash
❯ bit s        
error: bit failed to load bit.envs/compilers/react-typescript@3.1.43 with the following exception:
Cannot find module '@bit/bit.envs.compilers.typescript'
Require stack:
- /Users/kutner/Documents/Projects/pages/eva-homepage/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/dist/react-typescript/src/index.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/extensions/base-extension.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/extensions/extension.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/extensions/extensions-loader.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/app.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/bin/bit.js.
Error: Cannot find module '@bit/bit.envs.compilers.typescript'
Require stack:
- /Users/kutner/Documents/Projects/pages/eva-homepage/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/dist/react-typescript/src/index.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/extensions/base-extension.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/extensions/extension.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/extensions/extensions-loader.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/app.js
- /Users/kutner/.config/yarn/global/node_modules/bit-bin/bin/bit.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/kutner/Documents/Projects/pages/eva-homepage/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/dist/react-typescript/src/index.js:3:39)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/kutner/.config/yarn/global/node_modules/bit-bin/dist/extensions/base-extension.js:569:24
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/kutner/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/kutner/.config/yarn/global/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/kutner/.config/yarn/global/node_modules/bluebird/js/release/promise.js:609:26)
```

any idea why or how to resolve it?

### Specifications

- Bit version: 14.7.7
- Node version: 12.12.0
- npm / yarn version: 1.22.0
- Platform: MacOS

**Comment by itaymendel** [comment]
You need to use `bit mv ...` to move files/components around... otherwise Bit does not know where to sycn the components to.

You can run `bit mv ...` even after you have moved the files.

**Comment by KutnerUri** [comment]
as a workaround, I solved it like so:
1. `bit init --reset-hard`
1. Revert delete .bitmap
1. `bit import`

afterwards `bit build` and `bit status` worked normally
