### ISSUE TITLE
config.get is not a function

### ISSUE THREAD

**Issue by toolsallegory** [teambit/bit#2422]
### Describe the bug

A clear and concise description of the issue.

when installing on macOS 10.15.2, using:
-npm
-yarn
-homebrew
-directly copying executable

when I run bit init or bit or bit --version or bit anything, I get the following 

TypeError: config.get is not a function
    at getSync (/snapshot/bit/dist/api/consumer/lib/global-config.js:163:31)
    at Object.<anonymous> (/snapshot/bit/dist/logger/logger.js:127:67)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:25:18)

any command with bit will produce this error.

### Steps to Reproduce

1. install bit
2. type bit init in target repo

### Expected Behavior

I expect the thing to work in any capacity

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

TypeError: config.get is not a function
    at getSync (/snapshot/bit/dist/api/consumer/lib/global-config.js:163:31)
    at Object.<anonymous> (/snapshot/bit/dist/logger/logger.js:127:67)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:25:18)

### Specifications

- Bit version: latest
- Node version: 10.16.3
- npm / yarn version: yarn 1.21.1, npm 6.13.7, homebrew 2.2.9
- Platform: macOS 10.15.2
- Bit compiler (include version): did not get to this step
- Bit tester (include version): did not get to this step

### Additional context

this was my first time trying to install bit, I followed the quick-start, not sure if that's relevant

**Comment by davidfirst** [comment]
@toolsallegory , sorry for the late answer. I haven't seen this error before. 
Cleaning the entire Bit cache directory might resolve the issue. On Mac, it's located at `/Users/your-user/Library/Caches/Bit`.

**Comment by GiladShoham** [comment]
This happens to @guysaar223 as well many times. I know why it happens an ill fix it

**Comment by davidfirst** [comment]
@GiladShoham , please see my PR here https://github.com/teambit/bit/pull/2741.
It happened to me due to a different error (`Object.entries is not a function`), but because it used to return the error object instead of throwing the error, later, it used this error object as if it was a `Config` instance and called `.get()` on it.

**Comment by itaymendel** [comment]
irrelevant for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
