### ISSUE TITLE
tsconfig.json not found after installing Angular compiler during setup tutorial

### ISSUE THREAD

**Issue by maxmumford** [teambit/bit#2467]
### Describe the bug

When following the [Angular tutorial](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial), at the `bit build` stage, I get an exception saying tsconfig.json could not be found (see exception details below).

### Steps to Reproduce

$ git clone https://github.com/teambit/bit-angular-tutorial
$ cd bit-angular-tutorial
$ npm install
$ bit init
$ bit add src/app/product-list  --main src/app/product-list/product-list.module.ts
$ bit import bit.envs/compilers/angular --compiler 
$ bit build

### Expected Behavior

The build should succeed

### Screenshots, exceptions and logs

The following exception occurs when running bit build:

```
error: bit failed to load bit.envs/compilers/angular@0.2.1 with the following exception:
Cannot find module 'C:\Dev\test\bit-angular-tutorial\.git\bit\components\compilers\angular\bit.envs\0.2.1\dist\angular\tsconfig.json'
Require stack:
- C:\Dev\test\bit-angular-tutorial\.git\bit\components\compilers\angular\bit.envs\0.2.1\dist\angular\angular.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\base-extension.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\extension.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\extensions-loader.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\app.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\bin\bit.js.
Error: Cannot find module 'C:\Dev\test\bit-angular-tutorial\.git\bit\components\compilers\angular\bit.envs\0.2.1\dist\angular\tsconfig.json'
Require stack:
- C:\Dev\test\bit-angular-tutorial\.git\bit\components\compilers\angular\bit.envs\0.2.1\dist\angular\angular.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\base-extension.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\extension.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\extensions-loader.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\app.js
- C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\bin\bit.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Dev\test\bit-angular-tutorial\.git\bit\components\compilers\angular\bit.envs\0.2.1\dist\angular\angular.js:55:16)       
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\base-extension.js:569:24
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\Users\MaxMumford\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\promise.js:609:26)       
```

### Specifications

- Bit version: 14.7.6
- Node version: v12.14.1
- npm / yarn version: 6.13.4
- Platform: windows 10
- Bit compiler (include version): bit.envs/compilers/angular@0.2.1
- Bit tester (include version): not sure

**Comment by Tallyb** [comment]
Hi, 
For now use compiler@0.2.0. I will publish a new version soon.

**Comment by maxmumford** [comment]
Thank you, 0.2.0 works. For anyone else who finds themselves here, in your `package.json` file, change the following line:

`"compiler": "bit.envs/compilers/angular@0.2.1"`

to:

`"compiler": "bit.envs/compilers/angular@0.2.0"`

Then run `bit install` then `bit build` and it should work.
