### ISSUE TITLE
original message: array.map is not a function

### ISSUE THREAD

**Issue by Xuezenghuigithub** [teambit/bit#2543]
When I  import components from my Bit Server, get an error: 

```
error: unexpected network error has occurred.  original message: array.map is not a function
```

But the `bit list <scope>` command shows that my component upload is successful...I have no relevant information when I use `--v` or `bit docter`. Please help me...

---

  bit version   : 14.7.6
  node version  : v12.12.0
  npm version   : 6.14.3
  yarn version  : 1.22.0
  platform      : darwin

**Comment by GiladShoham** [comment]
Are you hosting on your on server or on bit.dev?
Please attach your debug logs so we can sort it out.

**Comment by huangyingwen** [comment]
The same error occurs
Through [bit-docker](https://github.com/teambit/bit-docker) to build local services
```json
{
"payload": {
"name": "TypeError",
"message": "array.map is not a function",
"stack": "TypeError: array.map is not a function\n at Function.deserialize (/usr/local/lib/node_modules/bit-bin/dist/bit-id/bit-ids.js:127:32)\n at /usr/local/lib/node_modules/bit-bin/dist/api/scope/lib/fetch.js:77:36\n at Generator.next (<anonymous>)\n at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n at /usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:201:15\n at fetch (/usr/local/lib/node_modules/bit-bin/dist/api/scope/lib/fetch.js:111:19)\n at then (/usr/local/lib/node_modules/bit-bin/dist/cli/commands/private-cmds/_fetch-cmd.js:113:33)\n at tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:517:31)\n at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:574:18)\n at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:619:10)\n at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:699:18)\n at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:138:12)\n at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:131:9)\n at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:147:5)"
},
"headers": {
"version": "14.2.3"
}
}
```
但是bit list <scope>命令显示我的组件上传成功，bit docter 也正常
---
bit version : 14.2.3
node version : v10.17.0
npm version : 6.11.3
yarn version : 1.19.2
platform : macos 10.15.4

**Comment by cristiz1992** [comment]
I'm having the exact issue as huangyingwen.
Do you have a fix for this ?
