### ISSUE TITLE
Bit export fails with 'hash not found'

### ISSUE THREAD

**Issue by pcaciula** [teambit/bit#2660]
### Cannot Export `hash [...] not found`

Export just stopped working. Tried clearing cache. Tried bit init --reset . Same error. Only solution was starting a new workspace,

### Steps to Reproduce

0. Build a bunch of components and tag, import, and export without issue.
1. bit export user.collection

### Expected Behavior

Should be able to export tagged components to remote at bit.dev. Expectation would be either this error shouldn't occur or that there'd be a clear solution/path to resolving without starting a new workspace and manually resetting everything.

### Specifications

- Bit version: 14.7.6
- Node version: v11.11.0
- npm / yarn version: 1.22.4
- Platform: MacOS Mojave 10.14.6
- Bit compiler (include version): bit.envs/compilers/vue@0.1.4

### Additional context

In copying and re-initting w/the existing .bitmap file, versions of almost of the component versions were uknown to upstream and threw errors - manually reducing their versions in .bitmap (I imagine this is not recommended, but didn't see any other way) allowed me to import. Then I just re-exported the updated version to bit in the new workspace and the problem was resolved. It would appear that my original workspace somehow got out of sync with the upstream. 

Evaluating Bit for use at a large enterprise for an upcoming project, so this issue is slightly concerning - any resolution/insight would be greatly appreciated - it's very possible this is the result of user error, but can't find any docs to explain/ info on how to resolve and fix the existing workspace.

**Comment by GiladShoham** [comment]
@pcaciula Thanks for reporting this.
We didn't saw this error for a long time.
If you still have the original workspace, any chance you can try `bit export --all`?
Thanks.

**Comment by davidfirst** [comment]
In addition to @GiladShoham, before this error is thrown, Bit writes to the log file the component id of that hash, which is helpful for debugging the issue.
The log file is located at `/Users/you-user/Library/Caches/Bit/logs/debug.log`, you can search for `HashNotFound`. 
 
Looking into the code, it seems to happen at the phase of changing the scope name of a dependency. In this case, if I understand correctly, the components weren't new, so the only reason to change their scope-name is when doing a fork (exporting to a different scope) implicitly or explicitly. 

@pcaciula, when you were running the export command, did you get a warning from Bit that you're going to fork the components? if not, were there some new components in the workspace?
(I'm trying to narrow the options so I could try to reproduce it somehow).

**Comment by pcaciula** [comment]
There's nothing to export in `bit export --all`... I tried doing `bit init --reset-hard`, probably killed everything. @davidfirst , it was not a fork and there were no warnings, I think there were new components I had tagged probably more than 1 that I was ready to export. 
Here's the log: 
`2020-05-08T21:59:39.775Z [32minfo[39m: [*] started a new command: "export [remote] [id...]" with the following data: {
  "args": [
    "pcaciula.scor",
    []
  ],
  "flags": {},
  "packageManagerArgs": []
}
2020-05-08T21:59:39.870Z [34mdebug[39m: Checking if a migration is needed 
2020-05-08T21:59:39.888Z [32minfo[39m: triggering hook pre-export 
2020-05-08T21:59:40.045Z [34mdebug[39m: scope.exportMany, ids: pcaciula.scor/mixins/drupal-settings, pcaciula.scor/mixins/mixins-analytics, pcaciula.scor/mixins/mixins-global-props, pcaciula.scor/mixins/mixins-post-shared-props, pcaciula.scor/mixins/mixins-post-props, pcaciula.scor/mixins/mixins-post, pcaciula.scor/mixins/mixins-post-shared-carousel, pcaciula.scor/mixins/mixins-swiper, pcaciula.scor/section-title, pcaciula.scor/helpers/url-helper, pcaciula.scor/helpers/uuid, pcaciula.scor/ad, pcaciula.scor/icon, pcaciula.scor/card-see-all, pcaciula.scor/cta-button, pcaciula.scor/card-widget, pcaciula.scor/action-button, pcaciula.scor/card-ui, theme/_mixins, theme/_variables, theme/_breakpoints 
2020-05-08T21:59:40.051Z [34mdebug[39m: enrich context from global config 
2020-05-08T21:59:40.109Z [34mdebug[39m: reading ssh public key from /Users/PaulCaciula/.ssh/id_rsa.pub 
2020-05-08T21:59:40.164Z [34mdebug[39m: export-scope-components, export all ids to one remote 
2020-05-08T21:59:41.124Z [34mdebug[39m: scope._convertToCorrectScope, switching pcaciula.scor/action-button version hash from 3dab5589ebb9217ebc9863e85108cc96ed85b1a8 to 3fcd5630a34deedea6f3d7a2bf840513d0550540 
2020-05-08T21:59:41.134Z [31merror[39m: got an error from command export [remote] [id...]: HashNotFound. Error serialized: {"stack":"HashNotFound\n    at Repository.loadSync (/usr/local/lib/node_modules/bit-bin/dist/scope/objects/repository.js:446:15)\n    at getIdWithUpdatedScope (/usr/local/lib/node_modules/bit-bin/dist/scope/component-ops/export-scope-components.js:681:48)\n    at version.getAllDependencies.forEach.dependency (/usr/local/lib/node_modules/bit-bin/dist/scope/component-ops/export-scope-components.js:658:30)\n    at Array.forEach (<anonymous>)\n    at changeDependencyScope (/usr/local/lib/node_modules/bit-bin/dist/scope/component-ops/export-scope-components.js:657:36)\n    at /usr/local/lib/node_modules/bit-bin/dist/scope/component-ops/export-scope-components.js:623:37\n    at Generator.next (<anonymous>)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n    at /usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:201:15\n    at /usr/local/lib/node_modules/bit-bin/dist/scope/component-ops/export-scope-components.js:647:22\n    at Array.map (<anonymous>)\n    at /usr/local/lib/node_modules/bit-bin/dist/scope/component-ops/export-scope-components.js:617:67\n    at Generator.next (<anonymous>)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)","isUserError":true,"name":"HashNotFound","hash":"5127299e181716372e60273420db8c0a78d2c44f","showDoctorMessage":true} 
2020-05-08T21:59:41.704Z [31merror[39m: User gets the following error: hash [1m5127299e181716372e60273420db8c0a78d2c44f[22m not found

run 'bit doctor' to get detailed workspace diagnosis and issue resolution. `

**Comment by davidfirst** [comment]
@pcaciula , thanks, the log is very helpful.
It's happening as I thought during the scope conversion. In your case, it seems to be related to one of the `pcaciula.scor/action-button` dependencies. I guess one one of them is a new component and Bit was trying to convert the non-scope to `pcaciula.scor` and somehow something went wrong there. 
Nothing unique in this use-case, it's pretty standard and we also have tests that cover it, so in order to reproduce it, I'll need the workspace. 
If by any chance you saved that workspace and you can zip it to me or to Gilad, it'd be great! (david@bit.dev and gilad@bit.dev).

**Comment by solarstar101** [comment]
any resolution to this? experiencing the same issue

**Comment by davidfirst** [comment]
@solarstar101 , if you can zip your workspace and send it to me(david@bit.dev), I could try to reproduce the issue.

**Comment by itaymendel** [comment]
export refactored and got more robust in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
