### ISSUE TITLE
bit import results in "Invalid or unexpected token"

### ISSUE THREAD

**Issue by arutkowski00** [teambit/bit#2753]
### Description

Hello, I'm trying to initialize `bit` in my project, but I'm having troubles with `bit import`. On every project (even in an empty one with `package.json` and bit-initialized) after a couple of seconds I'm getting "Invalid or unexpected token":

```
$ bit import bit.envs/compilers/react-typescript --compiler
C:\Users\USER\AppData\Roaming\npm\node_modules\bit-bin\node_modules\ramda-adjunct\lib\index.js:1



SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _ramdaAdjunct (C:\Users\USER\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\workspace\workspace.js:51:16)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\workspace\workspace.js:326:35
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Users\USER\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\util.js:16:23)     
    at PromiseSpawn._promiseFulfilled (C:\Users\USER\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\generators.js:201:15
    at Workspace.getMany (C:\Users\USER\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\workspace\workspace.js:330:7)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\workspace\workspace.js:269:39
    at Generator.next (<anonymous>)
```

### Specifications

- Bit version: 14.7.6 & 14.8.0-dev.1
- Node version: 14.4.0
- npm / yarn version: 6.13.7 / 1.21.1
- Platform: Windows 10 (v1903 build 18362.900)
- Bit compiler (include version): N/A
- Bit tester (include version): N/A

### Context and additional information

It does not work on any project, so it may be something wrong with my dev environment configuration. Compiler/tester I'm trying to import doesn't matter.

**Comment by benjgil** [comment]
Hi @arutkowski00 - Apologies for the delayed response, did you manage to solve the issue?

If not can you please describe the steps you took from initialising the Bit workspace up to the error appearing?
If so, please describe instead what the issue was in case others come up against the same error and dont know what's causing it :)
