### ISSUE TITLE
Upgrading bit-bin from 14.8.7 to 14.8.8 causes "trim-right not found" error

### ISSUE THREAD

**Issue by JGJP** [teambit/bit#2899]
### Describe the bug

This error occurs when building storybook. Everything else has remained the same apart from upgrading bit-bin to 14.8.8 from 14.8.7

I can't provide a repro right now due to proprietary code, but maybe this issue is enough info to find out what went wrong.

**Comment by JGJP** [comment]
```sh
ERROR in ./node_modules/acorn-jsx/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'trim-right'
Require stack:
- /Users/user/project/node_modules/@babel/core/node_modules/@babel/generator/lib/buffer.js
- /Users/user/project/node_modules/@babel/core/node_modules/@babel/generator/lib/printer.js
- /Users/user/project/node_modules/@babel/core/node_modules/@babel/generator/lib/index.js
- /Users/user/project/node_modules/@babel/core/lib/transformation/file/generate.js
- /Users/user/project/node_modules/@babel/core/lib/transformation/index.js
- /Users/user/project/node_modules/@babel/core/lib/transform.js
- /Users/user/project/node_modules/@babel/core/lib/index.js
- /Users/user/project/node_modules/babel-loader/lib/index.js
- /Users/user/project/node_modules/loader-runner/lib/loadLoader.js
- /Users/user/project/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/user/project/node_modules/webpack/lib/NormalModule.js
- /Users/user/project/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/user/project/node_modules/webpack/lib/Compiler.js
- /Users/user/project/node_modules/webpack/lib/webpack.js
- /Users/user/project/node_modules/@storybook/core/dist/server/build-static.js
- /Users/user/project/node_modules/@storybook/core/server.js
- /Users/user/project/node_modules/@storybook/vue/dist/server/index.js
- /Users/user/project/node_modules/@storybook/vue/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at _trimRight (/Users/user/project/node_modules/@babel/core/node_modules/@babel/generator/lib/buffer.js:9:39)
    at Buffer.get (/Users/user/project/node_modules/@babel/core/node_modules/@babel/generator/lib/buffer.js:47:17)
    at Generator.generate (/Users/user/project/node_modules/@babel/core/node_modules/@babel/generator/lib/printer.js:74:22)
    at Generator.generate (/Users/user/project/node_modules/@babel/core/node_modules/@babel/generator/lib/index.js:24:18)
    at _default (/Users/user/project/node_modules/@babel/core/node_modules/@babel/generator/lib/index.js:91:14)
    at generateCode (/Users/user/project/node_modules/@babel/core/lib/transformation/file/generate.js:57:39)
    at runSync (/Users/user/project/node_modules/@babel/core/lib/transformation/index.js:50:51)
    at runAsync (/Users/user/project/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /Users/user/project/node_modules/@babel/core/lib/transform.js:34:34
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
 @ ./node_modules/@storybook/addon-docs/dist/frameworks/react/lib/inspection/acornParser.js 18:39-59
 @ ./node_modules/@storybook/addon-docs/dist/frameworks/react/lib/inspection/inspectValue.js
 @ ./node_modules/@storybook/addon-docs/dist/frameworks/react/lib/inspection/index.js
 @ ./node_modules/@storybook/addon-docs/dist/frameworks/react/propTypes/rawDefaultPropResolvers.js
 @ ./node_modules/@storybook/addon-docs/dist/frameworks/react/propTypes/handleProp.js
 @ ./node_modules/@storybook/addon-docs/dist/frameworks/react/extractProps.js
 @ ./node_modules/@storybook/addon-docs/dist/blocks/Props.js
 @ ./node_modules/@storybook/addon-docs/dist/blocks/index.js
 @ ./node_modules/@storybook/addon-docs/blocks.js
 @ ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./node_modules/@storybook/addon-docs/dist/frameworks/vue/config.js ./.storybook/config.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by itaymendel** [comment]
we're unable to reproduce the issue locally.
when you can build a mock that reproduces the issue, please reopen the issue.
