### ISSUE TITLE
TS2717 thrown in React Typescript when running bit tag on some specific files

### ISSUE THREAD

**Issue by thanawit-cmkl** [teambit/bit#3850]
### Description

I was trying to `bit tag` my components to export them to my collection on bit.dev.
My project consists of multiple components and most of them were tagged and exported without problems. 
However, these errors came up when I tried to export BaseStyle.ts file which exports a style-components's `createGlobalStyle` (https://styled-components.com/docs/api#createglobalstyle)

This is my first time using bit.dev and also first time posting an issue so sorry if I missed any information (please feel free to ask if you need more info). Thank you for your help.

```
// more errors like these above this line

.dependencies/text/cmkl-university.omega/1.0.0/node_modules/@types/react/index.d.ts:3171:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'text' must be of type 'SVGProps<SVGTextElement>', but here has type 'SVGProps<SVGTextElement>'.

3171             text: React.SVGProps<SVGTextElement>;
                 ~~~~

  node_modules/@types/react/index.d.ts:3168:13
    3168             text: React.SVGProps<SVGTextElement>;
                     ~~~~
    'text' was also declared here.

.dependencies/text/cmkl-university.omega/1.0.0/node_modules/@types/react/index.d.ts:3172:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'textPath' must be of type 'SVGProps<SVGTextPathElement>', but here has type 'SVGProps<SVGTextPathElement>'.

3172             textPath: React.SVGProps<SVGTextPathElement>;
                 ~~~~~~~~

  node_modules/@types/react/index.d.ts:3169:13
    3169             textPath: React.SVGProps<SVGTextPathElement>;
                     ~~~~~~~~
    'textPath' was also declared here.

.dependencies/text/cmkl-university.omega/1.0.0/node_modules/@types/react/index.d.ts:3173:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'tspan' must be of type 'SVGProps<SVGTSpanElement>', but here has type 'SVGProps<SVGTSpanElement>'.

3173             tspan: React.SVGProps<SVGTSpanElement>;
                 ~~~~~

  node_modules/@types/react/index.d.ts:3170:13
    3170             tspan: React.SVGProps<SVGTSpanElement>;
                     ~~~~~
    'tspan' was also declared here.

.dependencies/text/cmkl-university.omega/1.0.0/node_modules/@types/react/index.d.ts:3174:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'use' must be of type 'SVGProps<SVGUseElement>', but here has type 'SVGProps<SVGUseElement>'.

3174             use: React.SVGProps<SVGUseElement>;
                 ~~~

  node_modules/@types/react/index.d.ts:3171:13
    3171             use: React.SVGProps<SVGUseElement>;
                     ~~~
    'use' was also declared here.

.dependencies/text/cmkl-university.omega/1.0.0/node_modules/@types/react/index.d.ts:3175:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'view' must be of type 'SVGProps<SVGViewElement>', but here has type 'SVGProps<SVGViewElement>'.

3175             view: React.SVGProps<SVGViewElement>;
                 ~~~~

  node_modules/@types/react/index.d.ts:3172:13
    3172             view: React.SVGProps<SVGViewElement>;
                     ~~~~
    'view' was also declared here.

node_modules/@types/react/index.d.ts:2984:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

2984         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  .dependencies/text/cmkl-university.omega/1.0.0/node_modules/@types/react/index.d.ts:2985:14
    2985         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.


Found 177 errors.
```

```
error: bit failed to build layouts/basic-layout with the following exception:
error: bit failed to build base-style with the following exception:
Command failed with exit code 2: /Users/thanawit/CMKL/Projects/Omega/omega_hub/Frontend/.bit/components/compilers/react-typescript/bit.envs/4.0.0/components/.dependencies/compilers/typescript/bit.envs/3.1.53/node_modules/typescript/bin/tsc --declaration
Error: Command failed with exit code 2: /Users/thanawit/CMKL/Projects/Omega/omega_hub/Frontend/.bit/components/compilers/react-typescript/bit.envs/4.0.0/components/.dependencies/compilers/typescript/bit.envs/3.1.53/node_modules/typescript/bin/tsc --declaration
    at makeError (/Users/thanawit/CMKL/Projects/Omega/omega_hub/Frontend/.bit/components/compilers/react-typescript/bit.envs/4.0.0/components/.dependencies/compilers/typescript/bit.envs/3.1.53/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/thanawit/CMKL/Projects/Omega/omega_hub/Frontend/.bit/components/compilers/react-typescript/bit.envs/4.0.0/components/.dependencies/compilers/typescript/bit.envs/3.1.53/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

ExternalBuildErrors
    at /usr/local/lib/node_modules/bit-bin/dist/consumer/component-ops/build-component.js:559:23
    at Generator.throw (<anonymous>)
    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseRejected (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:107:10)
    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:611:26)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
```

### Specifications

- Bit version: 14.8.8
- Node version: 15.9.0
- npm / yarn version: yarn 1.22.10
- Platform: macOS
- Bit compiler (include version): React-typescript (4.0.0)
- Bit tester (include version): n/a

**Comment by itaymendel** [comment]
Hi @thanawit-cmkl 

component compilation process has been updated in Bit's upcoming release.
We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
