### ISSUE TITLE
breaks after modification in imported component 

### ISSUE THREAD

**Issue by javariahazoor** [teambit/bit#3925]
I am following the bit angular tutorial and when i import the isolated component in new angular app it works fine but when i made changes and run bit build command and than npm run start it is giving me following error

.(node:17452) UnhandledPromiseRejectionWarning: Error: Symbol ProductListModule declared in F:/Thesis/2021/tutorial/my-new-app/components/product-list/dist/product-list.module.d.ts is not exported from @bit/javariahazoor.angular-tutorial.product-list (import into F:/Thesis/2021/tutorial/my-new-app/src/app/app.module.ts)
    at AbsoluteModuleStrategy.emit (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\emitter.js:171:23)
    at ReferenceEmitter.emit (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\emitter.js:72:44)
    at Object.toR3Reference (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\util.js:251:18)
    at NgModuleDecoratorHandler._toR3Reference (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:490:31)
    at F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:264:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:264:38)
    at TraitCompiler.analyzeTrait (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:361:40)
    at analyze (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:312:58)
    at _loop_1 (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:334:21)
    at TraitCompiler.analyzeClass (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:340:35)
    at visit (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:110:27)
    at visitNodes (F:\Thesis\2021\tutorial\my-new-app\node_modules\typescript\lib\typescript.js:27858:30)
    at Object.forEachChild (F:\Thesis\2021\tutorial\my-new-app\node_modules\typescript\lib\typescript.js:28097:24)
    at visit (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:112:20)
    at TraitCompiler.analyze (F:\Thesis\2021\tutorial\my-new-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:114:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
\ Generating browser application bundles (phase: building)...(node:17452) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)

**and also this error**

Error: components/product-list/dist/product-list.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the dependency (@bit/javariahazoor.angular-tutorial.product-list) which declares ProductListModule has not been processed correctly by ngcc.

1 export declare class ProductListModule {
                       ~~~~~~~~~~~~~~~~~

**Comment by itaymendel** [comment]
please use https://github.com/teambit/bit-angular for angular with bit.
