### ISSUE TITLE
You do not have permissions to access 'undefined', were you running bit, npm or git as root?

### ISSUE THREAD

**Issue by 50l3r** [teambit/bit#3944]
### Describe the bug
When i try to execute ```bit login``` i give this error:

`error: you do not have permissions to access 'undefined', were you running bit, npm or git as root?`

### Steps to Reproduce
1. Install bit-bin with npm as global package
1. Open a terminal
1.  Execute `bit login`

### Specifications
* Bit version: 14.8.8
* Node version: 12.19.0
* npm / yarn version: 6.14.8
* Platform: Windows 10 x64 
* Bit compiler (include version): bit.envs/bundlers/vue@2.6.21

**Comment by GiladShoham** [comment]
can you please attach additional logs?
The log location is detailed here - https://docs.bit.dev/docs/workspace#logs

**Comment by 50l3r** [comment]
```
2021-03-16T08:31:10.285Z [34mdebug[39m: legacy-extensions.extensions-loader, start loading extensions 
2021-03-16T08:31:10.483Z [32minfo[39m: [*] started a new command: "login" with the following data: {
  "args": [],
  "flags": {}
}
2021-03-16T08:31:10.523Z [34mdebug[39m: login.loginToBitSrc, initializing login server on port: 8085 
2021-03-16T08:31:10.526Z [31merror[39m: got an error from command login: Error: listen EACCES: permission denied 0.0.0.0:8085 
2021-03-16T08:31:10.526Z [31merror[39m: Error: listen EACCES: permission denied 0.0.0.0:8085
    at Server.setupListenHandle [as _listen2] (net.js:1300:21)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1451:7)
    at C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\dist\consumer\login\login.js:225:12
    at new Promise (<anonymous>)
    at loginToBitSrc (C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\dist\consumer\login\login.js:136:10)
    at C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\dist\api\consumer\lib\login.js:32:33
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\generators.js:201:15
    at loginAction (C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\dist\api\consumer\lib\login.js:36:25)
    at Login.action (C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\dist\cli\commands\public-cmds\login-cmd.js:71:34)
    at C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\dist\extensions\cli\legacy-command-adapter.js:88:35
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Users\50l3r\AppData\Roaming\npm\node_modules\bit-bin\node_modules\bluebird\js\release\util.js:16:23) 
2021-03-16T08:31:10.642Z [31merror[39m: user gets the following error: [31merror: you do not have permissions to access 'undefined', were you running bit, npm or git as root?[39m 
2021-03-16T08:31:10.927Z [31merror[39m: [*] the command login has been terminated with an error code 1 

```

**Comment by itaymendel** [comment]
Is it possible that you installed Bit as an admin, and now you are trying to use it with a normal user account?

**Comment by 50l3r** [comment]
> Is it possible that you installed Bit as an admin, and now you are trying to use it with a normal user account?

Nope, im the only one and i'm admin

**Comment by GiladShoham** [comment]
which terminal did you use?
I believe it's something locally on your machine.

**Comment by davidfirst** [comment]
@50l3r , is this still an issue? if so, please update to the latest version and let us know.

**Comment by 50l3r** [comment]
> @50l3r , is this still an issue? if so, please update to the latest version and let us know.

I have to try it again but right now it is not possible. I tell you as soon as I know

**Comment by ashwanth1109** [comment]
Im facing the same issue on my local. I have updated to latest bit version:

```
$ bit doctor

  bit version   : 0.0.674
  node version  : v16.10.0
  npm version   : 7.24.0
  yarn version  : 1.22.17
  platform      : win32
  user details  : Ashwanth A R<ashwanth1109@gmail.com>


╔════════════════════╤═════════════════════════════════╤════════════════════════════════════════════════════════╤════════╗
║ category           │ name                            │ description                                            │ status ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ configuration      │ validate workspace's bit config │ validate workspace configuration object                │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate git exec               │ validate that git executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ internal store     │ check orphan refs               │ checks for empty internal refs in local workspace      │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ local environments │ check environment symlinks      │ validate generated symlinks for workspace environments │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate npm exec               │ validate that npm executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate yarn exec              │ validate that yarn executable found                    │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ core               │ validate bit version            │ validate that bit version is up to date                │ passed ║
╚════════════════════╧═════════════════════════════════╧════════════════════════════════════════════════════════╧════════╝
```

**Comment by ashwanth1109** [comment]
Okay, I was able to work around the issue by setting my port to 3000 by running the following command:
```
bit login -p 3000
```

And this worked. My best guess at this point is that for some reason the default port 8085 is blocked on my machine for some reason

**Comment by davidfirst** [comment]
@ashwanth1109 , thanks for providing the log! I fixed this issue to show the proper error in the PR above.
