### ISSUE TITLE
"Cannot find module 'react-is'" error received when using `bit tag`

### ISSUE THREAD

**Issue by tqmai** [teambit/bit#4126]
### Describe the bug

When I try to run `bit tag --all`, I now get this error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/Users/timothymai/Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist'
```

### Steps to Reproduce

1. Run `npm i` 
2. Run `bit add src/styles/tokens`
3. Run `bit add src/components/icon/search --namespace icon` (I originally used `bit create` for this component)
4. Run `bit add paclife.plds/button` (I originally used `bit create` for this component)
5. Run `bit tag --all`

### Expected Behavior

All components are tagged normally, like before.

### Screenshots, exceptions and logs

```
timothymai@ANMMJ-C02V60XCHTDF bit-sample % bit tag --all
✔ running pre install subscribers
✔ deduping dependencies for installation
...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 1, reused 0,...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 4, reused 4,...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 5, reused 4,...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 12, reused 1...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 13, reused 1...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 26, reused 2...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 27, reused 2...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 52, reused 5...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 53, reused 5...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 76, reused 7...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 77, reused 7...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 107, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 108, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 |  WARN  styled-components@5.2.3 requires a peer of react-is@>= 16.8.0 but none was installed.
...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 108, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | +111 +++++++++++
...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 108, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/timothymai/.pnpm-store
  Virtual store is at:             ../../../Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm
...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused ...3d99b9142b39b44c1a9eec9b2f0e28bd558f1 | Progress: resolved 111, reused 111, downloaded 0, added 111, done
../../../Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/core-js-pure@3.10.1/node_modules../../../Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/core-js-pure@3.10.1/node_modules/core-js-pure: Running postinstall script, done in 60ms
  -------------------------
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
✔ teambit.component/isolator, create capsules network (completed in 11s)
  running build pipe for 1 environments, total 6 tasks✔ teambit.component/isolator, create capsules network (completed in 7ms)
  generated graph for env "teambit.react/react", seeders total: 3, graph total: 3
✔ executing pre-build for all tasks
✔ env "teambit.react/react", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 866μs
✔ env "teambit.react/react", task "teambit.compilation/compiler:MultiCompiler (compile components for artifact dist)" has completed successfully in 4s
⠄⠀ teambit.pipelines/builder, running tasks (3/6). env "teambit.react/react", task "teambit.defender/tester:TestComponents"Determining test suites t PASS  ../../../Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/paclife.plds_icon_search@0.0.2/dist/search.spec.js
 FAIL  ../../../Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/paclife.plds_button@0.0.1/dist/button.spec.js
  ● Test suite failed to run

    Cannot find module 'react-is' from 'node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist/styled-components.cjs.js'

    Require stack:
      node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist/styled-components.cjs.js
      paclife.plds_button@0.0.1/dist/button.js
      paclife.plds_button@0.0.1/dist/button.spec.js

      1 | import React from "react";
    > 2 | import styled, { css } from "styled-components";
        | ^
      3 |
      4 | import {
      5 |   Colors,

      at Resolver.resolveModule (../../../../../.bvm/versions/0.0.361/bit-0.0.361/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist/styled-components.cjs.js:1:234)
      at Object.<anonymous> (paclife.plds_button@0.0.1/button.tsx:2:1)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.109 s
✖ env: teambit.react/react, task "teambit.defender/tester:TestComponents" has failed
✔ env "teambit.react/react", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 65μs
✔ env "teambit.react/react", task "teambit.pkg/pkg:PublishDryRun" has completed successfully in 2s
✖ env: teambit.react/react, task "teambit.preview/preview:GeneratePreview" has failed✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running build pipe for 1 environments, total 6 tasks (completed in 15s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.defender/tester:TestComponents" of env "teambit.react/react"
component: paclife.plds/button@0.0.1
  ● Test suite failed to run

    Cannot find module 'react-is' from 'node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist/styled-components.cjs.js'

    Require stack:
      node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist/styled-components.cjs.js
      paclife.plds_button@0.0.1/dist/button.js
      paclife.plds_button@0.0.1/dist/button.spec.js

      1 | import React from "react";
    > 2 | import styled, { css } from "styled-components";
        | ^
      3 |
      4 | import {
      5 |   Colors,

      at Resolver.resolveModule (../../../../../.bvm/versions/0.0.361/bit-0.0.361/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist/styled-components.cjs.js:1:234)
      at Object.<anonymous> (paclife.plds_button@0.0.1/button.tsx:2:1)


Found 1 errors in 1 components

Failed task 2: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react"
component: paclife.plds/button@0.0.1
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/Users/timothymai/Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/Users/timothymai/Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist'
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/Compilation.js:1668:28
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:712:13
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:628:24
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:782:8
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:902:5
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/neo-async/async.js:6883:13
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:885:45
    at finishWithoutResolve (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

component: paclife.plds/tokens@0.0.1
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/Users/timothymai/Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/Users/timothymai/Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist'
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/Compilation.js:1668:28
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:712:13
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:628:24
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:782:8
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:902:5
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/neo-async/async.js:6883:13
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:885:45
    at finishWithoutResolve (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

component: paclife.plds/icon/search@0.0.2
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/Users/timothymai/Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/Users/timothymai/Library/Caches/Bit/capsules/1093d99b9142b39b44c1a9eec9b2f0e28bd558f1/node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_react-dom@16.13.1+react@16.13.1/node_modules/styled-components/dist'
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/Compilation.js:1668:28
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:712:13
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:628:24
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:782:8
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:902:5
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/neo-async/async.js:6883:13
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/lib/NormalModuleFactory.js:885:45
    at finishWithoutResolve (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/timothymai/.bvm/versions/0.0.361/bit-0.0.361/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

Found 3 errors in 3 components


✖ Total 6 tasks. 4 succeeded. 2 failed. 0 skipped. Total errors: 4.
```

### Specifications

- Bit version: 0.0.361
- Node version: 14.4.0
- npm / yarn version: 6.14.5
- Platform: MacOS Catalina 10.15.7
- bvm version: 0.0.20

### Additional context

Checkout `bit` branch in this repo to reproduce: 
https://github.com/tqmai/bit-sample

**Comment by davidfirst** [comment]
@tqmai , I cloned your project and was able to reproduce the issue.
I'm not sure why this dependency was not installed. @GiladShoham , could take a look into this later.

For now, you can just add it manually to the policies of the dependency-resolver. As follows:
```
"*": {
      /**
       * uncomment to apply the react environment on all components.
       **/
      "teambit.react/react": {},
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "dependencies": {
            "react-is": "17.0.2"
          }
        }
      }
    }
```
You can see more info here:
https://harmony-docs.bit.dev/aspects/dependency-resolver#apply-policies-on-a-selected-group-of-components

**Comment by GiladShoham** [comment]
I'm not in front of a computer but I think I'm this case it will be better to put it into the policy of the root under the peer dependencies. In case you will do what @davidfirst suggests it will work but you might end with multiple instances of this package in case you will change the version later.
However with my solution the consumer of your components will have to install it. 
So both solutions are fine. Just decide what you prefer.

**Comment by tqmai** [comment]
I tried Gilad's approach and it worked! Thank you all for the help.
