### ISSUE TITLE
Error when tagging dependencies that have typescript files

### ISSUE THREAD

**Issue by SC7639** [teambit/bit#4157]
### Describe the bug

Keep getting errors when a component is tagged due to its dependency being modified. I'm using react with typescript in my project and the error seems to be something to do with it not being converted from typescript or it not recognizing the typescript syntax.

Error output: https://gist.github.com/SC7639/0c963c7c9c9c59ebc7affac4543a209a

### Steps to Reproduce

1. Create a component that has multiple files with typescript syntax e.g. ` fontSize: ({ featured = false }: StyleProps)`
2. Modify a component that is a dependency of other components
3. Then when trying to tag the component for a new version the component with typescript syntax causes the tag command to error.

### Expected Behavior

All components are tagged correctly

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:  `bit doctor`: 1.0.62 | `bvm version`: 0.0.369
- Node version: 14.15.2
- npm version: 6.14.9
- Platform: linux

**Comment by SC7639** [comment]
I've removed the offending syntax but getting a different error now :(. Added a new file to the gist that has the error

**Comment by davidfirst** [comment]
@SC7639 , do these two components have different env? Please run `bit env <component-name>` for each one of them and paste the env here. Also, if you could create a minimal reproducible project, it'd be very helpful with debugging the issue.

**Comment by SC7639** [comment]
mobile-card environment: 
```
Environment: teambit.react/react                                                                                                                                                                        [48/48]teambit.pipelines/builder

total 6 tasks are configured to be executed in the following order
1. teambit.harmony/aspect:CoreExporter
2. teambit.compilation/compiler:TSCompiler
3. teambit.defender/tester:TestComponents
4. teambit.pkg/pkg:PreparePackages
5. teambit.pkg/pkg:PublishDryRun
6. teambit.preview/preview:GeneratePreview

teambit.defender/tester

configured tester: teambit.defender/jest (Jest @ 26.6.3)
tester config:
"use strict";

module.exports = {
  // "roots": [
  //   "<rootDir>/src"
  // ],
  // "collectCoverageFrom": [
  //   "src/**/*.{js,jsx,ts,tsx}",
  //   "!src/**/*.d.ts"
  // ],
  setupFiles: [require.resolve('react-app-polyfill/jsdom')],
  setupFilesAfterEnv: [require.resolve('./setupTests.js')],
  // "testMatch": [                            
  // "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}",
  // "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"
  // ],
  testEnvironment: require.resolve('jest-environment-jsdom'),
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': require.resolve('./transformer'),
    '^.+\\.css$': require.resolve('./css-transform.js'),
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': require.resolve('./file-transform.js')
  },
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$'],
  modulePaths: [],
  moduleNameMapper: {
    '^react-native$': require.resolve('react-native-web'),
    '^.+\\.module\\.(css|sass|scss)$': require.resolve('identity-obj-proxy')
  },
  moduleFileExtensions: ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'] // watchPlugins: [require.resolve('jest-watch-typeahead/filename'), 
require.resolve('jest-watch-typeahead/testname')],

};

//# sourceMappingURL=jest/jest.config.js.map
teambit.compilation/compiler

configured compiler: teambit.typescript/typescript (TypeScript @ 4.1.5)
compiler config:
{
 "compilerOptions": {
    "lib": [
      "es2019",
      "DOM",
      "ES6",
      "DOM.Iterable"
    ],
    "target": "es2015",
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "esModuleInterop": true
  },
  "exclude": [
    "dist"
  ]
}
```

**Comment by SC7639** [comment]
desktop-card environment:
```
Environment: teambit.react/react                                                                                                                                                                        [48/48]teambit.pipelines/builder

total 6 tasks are configured to be executed in the following order
1. teambit.harmony/aspect:CoreExporter
2. teambit.compilation/compiler:TSCompiler
3. teambit.defender/tester:TestComponents
4. teambit.pkg/pkg:PreparePackages
5. teambit.pkg/pkg:PublishDryRun
6. teambit.preview/preview:GeneratePreview

teambit.defender/tester

configured tester: teambit.defender/jest (Jest @ 26.6.3)
tester config:
"use strict";

module.exports = {
  // "roots": [
  //   "<rootDir>/src"
  // ],
  // "collectCoverageFrom": [
  //   "src/**/*.{js,jsx,ts,tsx}",
  //   "!src/**/*.d.ts"
  // ],
  setupFiles: [require.resolve('react-app-polyfill/jsdom')],
  setupFilesAfterEnv: [require.resolve('./setupTests.js')],
  // "testMatch": [
  // "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}",
  // "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"
  // ],
  testEnvironment: require.resolve('jest-environment-jsdom'),
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': require.resolve('./transformer'),
    '^.+\\.css$': require.resolve('./css-transform.js'),
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': require.resolve('./file-transform.js')
  },
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$'],
  modulePaths: [],
  moduleNameMapper: {
    '^react-native$': require.resolve('react-native-web'),
    '^.+\\.module\\.(css|sass|scss)$': require.resolve('identity-obj-proxy')
  },
  moduleFileExtensions: ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'] // watchPlugins: [require.resolve('jest-watch-typeahead/filename'), 
require.resolve('jest-watch-typeahead/testname')],

};

//# sourceMappingURL=jest/jest.config.js.map
teambit.compilation/compiler

configured compiler: teambit.typescript/typescript (TypeScript @ 4.1.5)
compiler config:
{
  "compilerOptions": {
    "lib": [
      "es2019",
      "DOM",
      "ES6",
      "DOM.Iterable"
    ],
    "target": "es2015",
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "esModuleInterop": true
  },
  "exclude": [
    "dist"
  ]
}
```

**Comment by davidfirst** [comment]
Interesting. Both components use the React env, which uses Typescript as the main compiler. I don't see any reason why it wouldn't recognize this syntax. It must be something else. 
Can you attach a tar or git-repo with these two components and the workspace.jsonc? this way we can try to reproduce the issue.
Before that, I'd suggest updating Bit to the latest version and trying again.

**Comment by SC7639** [comment]
I've updated the component that was giving the error and when trying to tag it's failing again at the `piplines/builder` with:
```shell
component: skiddle.web/events/filters/location@0.0.4
Module build failed (from ../../../.bvm/versions/0.0.376/bit-0.0.376/node_modules/@teambit/react/node_modules/babel-loader/lib/index.js):
SyntaxError: /home/sc7639/Library/Caches/Bit/capsules/44d3c4c31aa12cfb24ae2ccae4be23a0ed66eea5/skiddle.web_events_store_filters@0.0.4/actions.ts: Unexpected token, expected "," (22:9)

  20 |
  21 | export const updateOrderBy = (
> 22 |     order: FiltersState["orderBy"],
     |          ^
  23 | ): UpdateOrderBy => ({
  24 |     type: "UPDATE_FILTERS_ORDER_BY",
  25 |     value: order,
    at Object._raise (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:776:17)
    at Object.raiseWithData (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:769:17)
    at Object.raise (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:737:17)
    at Object.unexpected (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:9736:16)
    at Object.expect (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:9722:28)
    at Object.parseParenAndDistinguishExpression (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:11293:14)
    at Object.parseExprAtom (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:11027:21)
    at Object.parseExprAtom (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:5170:20)
    at Object.parseExprSubscripts (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:10709:23)
    at Object.parseUpdate (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:10689:21)
    at Object.parseMaybeUnary (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:10667:23)
    at Object.parseExprOps (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:10524:23)
    at Object.parseMaybeConditional (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:10498:23)
    at Object.parseMaybeAssign (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:10461:21)
    at /home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:10428:39
    at Object.allowInAnd (/home/sc7639/.bvm/versions/0.0.376/bit-0.0.376/node_modules/@babel/parser/lib/index.js:12099:16)
```

**Comment by SC7639** [comment]
My only option at this point is to run tag with `--force-deploy`

**Comment by SC7639** [comment]
I think I've found the issue. It was that I was importing as `import { actionFunc } from "@skiddle/web.events.store.filters/action"`. I've updated the `index.ts` to export everything and updated the imports the `import { actionFunc } from "@skiddle/web.events.stor.efilters`

**Comment by davidfirst** [comment]
Oh that's interesting. We know that importing internal component files causes issues. We might need to show a warning about it in `bit status`. 
@GiladShoham , I remember we discussed this option, what do you think?

**Comment by GiladShoham** [comment]
I think we should add a warning about requiring internal files. Not blocking but warning in status

**Comment by davidfirst** [comment]
@GiladShoham , I just recall that you said that sometimes users do need to import internal files, such as webpack/babel config files. How do we know when it's legit?

**Comment by GiladShoham** [comment]
@davidfirst I think at the first step we can add the warning only if the internal file is .ts / tsx file.
