### ISSUE TITLE
received 404 Error when install bit component 

### ISSUE THREAD

**Issue by bakudan00** [teambit/bit#4181]
Hi everyone,  I am new to bit,  I have a private collection and having trouble on installing one of the component, I have no issue installing it before but after I  do the changes, exported it and install on friday evening I am getting 404 error, also I have already update the compiler and configure the @bit registry manually by doing `npm login --registry=https://node.bit.dev --scope=@bit` but still having the same issue. I am stuck and not sure what to do, Please help. Thank you very much

## Expected Behavior
No error after installing the component and install success

## Actual Behavior
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://node.bit.dev/@bit%2fhorizon-am-dev.horizon.component-panel - Not found
npm ERR! 404 
npm ERR! 404  '@bit/horizon-am-dev.horizon.component-panel@4.0.84' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/msuradi/.npm/_logs/2021-04-26T09_10_43_473Z-debug.log
```

logs
```
137 verbose stack Error: 404 Not Found - GET https://node.bit.dev/@bit%2fhorizon-am-dev.horizon.component-panel - Not found
137 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:123:15
137 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
137 verbose stack     at async Promise.all (index 0)
137 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:923:5)
137 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:7)
137 verbose stack     at async Promise.all (index 1)
137 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
137 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:137:5)
138 verbose statusCode 404
139 verbose pkgid @bit/horizon-am-dev.horizon.component-panel@4.0.84
140 verbose cwd /Users/msuradi/Desktop/hrznDev/frontend/react-horizon
141 verbose Darwin 20.3.0
142 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
143 verbose node v14.15.3
144 verbose npm  v7.9.0
145 error code E404
146 error 404 Not Found - GET https://node.bit.dev/@bit%2fhorizon-am-dev.horizon.component-panel - Not found
147 error 404
148 error 404 '@bit/horizon-am-dev.horizon.component-panel@4.0.84' is not in the npm registry.
149 error 404 You should bug the author to publish it (or use the name yourself!)
150 error 404 Note that you can also install from a
151 error 404 tarball, folder, http url, or git url.
152 verbose exit 1
```

## Steps to Reproduce the Problem

  1. install @bit/horizon-am-dev.horizon.pages.page-dashboard
  2. return 404 Error

## Specifications

  - Bit version: 14.8.8
  - Node version: v14.15.3
  - npm: 7.9.0
  - Platform: darwin
  - Bit compiler (include version):  compilers/react@2.0.0
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
looks like you are not authenticated with npm.
Can you check your npmrc file and see if you have token for the bit registry? (do not share the token here)
If it's your own machine, you can run `bit login` (or `bit logout` and `bit login`) and it will setup your npmrc file

**Comment by itaymendel** [comment]
hi,

You should not use `npm login` to authenticate to Bit. Please use `bit login`, as it configures `.npmrc` file with the Bit-token.
