### ISSUE TITLE
bit export throws 'Error: Cannot find module '/tmp/symphony/http-resolver.js'

### ISSUE THREAD

**Issue by nelsonkent** [teambit/bit#4285]
### Describe the bug

I have used bit to hold my react library, and updated for 20 times, current version is 1.0.22, but suddenly it report error, after i revert to last success version still report error.

### Steps to Reproduce
1. bit tag --all
2. bit export xxxxxx

### Screenshots, exceptions and logs

`
2021-05-14T07:28:42.924Z [34mdebug[39m: legacy-extensions.extensions-loader, start loading extensions
2021-05-14T07:28:43.035Z [34mdebug[39m: scope.load, found scope at /Users/nelson/projects/map-web-new/library/.bit from cache
2021-05-14T07:28:43.202Z [32minfo[39m: [*] started a new command: "export [remote] [id...]" with the following data: {
"args": [
"xx.test",
[]
],
"flags": {}
}
2021-05-14T07:28:43.206Z [34mdebug[39m: Checking if a migration is needed
2021-05-14T07:28:43.212Z [32minfo[39m: triggering hook pre-export
2021-05-14T07:28:43.235Z [34mdebug[39m: scope.exportMany, ids: components
2021-05-14T07:28:43.238Z [34mdebug[39m: enrich context from global config
2021-05-14T07:28:43.292Z [34mdebug[39m: reading ssh public key from /Users/xx/.ssh/id_rsa.pub
2021-05-14T07:28:43.327Z [34mdebug[39m: export-scope-components, export all ids to one remote
2021-05-14T07:28:44.074Z [34mdebug[39m: Establishing a new SSH connection to ssh://bit@hub.bit.dev:xx.test
2021-05-14T07:28:44.080Z [34mdebug[39m: ssh, trying to connect using token
2021-05-14T07:28:44.099Z [34mdebug[39m: ssh, failed to connect using token. user token not defined in bit-config. please run `bit login` to authenticate.
2021-05-14T07:28:44.099Z [34mdebug[39m: ssh, trying to connect using ssh-agent
2021-05-14T07:28:46.450Z [34mdebug[39m: ssh, failed to connect using ssh-agent. no matching private key found in ssh-agent to authenticate to remote server.
2021-05-14T07:28:46.451Z [34mdebug[39m: ssh, trying to connect using ssh-key
2021-05-14T07:28:46.468Z [34mdebug[39m: ssh, reading ssh key at /Users/xx/.ssh/id_rsa
2021-05-14T07:28:46.471Z [31merror[39m: ssh Cannot parse privateKey: Unsupported key format {
"stack": "Error: Cannot parse privateKey: Unsupported key format\n    at Client.connect (/usr/local/lib/node_modules/bit-bin/node_modules/ssh2/lib/client.js:230:13)\n    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:507:14\n    at new Promise (<anonymous>)\n    at connectWithConfigP (/usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:502:16)\n    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:512:35\n    at Generator.next (<anonymous>)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n    at /usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:201:15\n    at SSH._connectWithConfig (/usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:543:7)\n    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:423:21\n    at Generator.next (<anonymous>)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n    at Promise._settlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:609:26)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:649:10)"
}
2021-05-14T07:28:46.472Z [34mdebug[39m: ssh, failed to connect using ssh-key. error connecting with private ssh key. in case passphrase is used, use ssh-agent.
2021-05-14T07:28:46.472Z [34mdebug[39m: ssh, trying to connect using user-password
2021-05-14T07:29:13.136Z [34mdebug[39m: ssh, authenticated successfully using user-password
2021-05-14T07:29:14.071Z [34mdebug[39m: ssh: going to run a remote command _put, path: xx.test
2021-05-14T07:29:25.878Z [31merror[39m: ssh: got an error, {"payload":{"code":"MODULE_NOT_FOUND","name":"Error","message":"Cannot find module '/tmp/symphony/http-resolver.js'","stack":"Error: Cannot find module '/tmp/symphony/http-resolver.js'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at remoteResolver (/usr/local/lib/node_modules/bit-bin/dist/remotes/remote-resolver/remote-resolver.js:58:24)\n    at Map.resolve (/usr/local/lib/node_modules/bit-bin/dist/remotes/remotes.js:116:42)\n    at /usr/local/lib/node_modules/bit-bin/dist/remotes/remotes.js:137:15\n    at keys.forEach.key (/usr/local/lib/node_modules/bit-bin/dist/utils/object/foreach.js:21:23)\n    at Array.forEach (<anonymous>)\n    at forEach (/usr/local/lib/node_modules/bit-bin/dist/utils/object/foreach.js:21:8)\n    at /usr/local/lib/node_modules/bit-bin/dist/remotes/remotes.js:135:28\n    at Generator.next (<anonymous>)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n    at /usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:201:15\n    at Map.fetch (/usr/local/lib/node_modules/bit-bin/dist/remotes/remotes.js:147:7)"},"headers":{"version":"14.8.8","compressed":false}}
2021-05-14T07:29:25.879Z [34mdebug[39m: ssh: exit. Exit code: null
2021-05-14T07:29:26.115Z [34mdebug[39m: ssh: returned with code: null, signal: SIGMODULE_NOT_FOUND.
2021-05-14T07:29:26.119Z [31merror[39m: unpackCommand found on error "SyntaxError: Unexpected end of JSON input", while parsing the following string:  
2021-05-14T07:29:26.124Z [33mwarn[39m: exportMany, failed pushing ids to the bare-scope
2021-05-14T07:29:26.125Z [31merror[39m: got an error from command export [remote] [id...]: SSHInvalidResponse
2021-05-14T07:29:26.125Z [31merror[39m: SSHInvalidResponse
at SSH._unpack (/usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:680:13)
at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:691:16
at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-05-14T07:29:26.225Z [31merror[39m: user gets the following error: error: received an invalid response from the remote SSH server.
to see the invalid response, have a look at the log, located at /Users/xx/Library/Caches/Bit/logs/debug.log

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
2021-05-14T07:29:26.228Z [31merror[39m: [*] the command export [remote] [id...] has been terminated with an error code 1 
`

### Specifications

- Bit version:   14.8.8
- Node version:  14.16.0
- npm / yarn version: 6.14.11
- Platform: mac
- Bit compiler (include version):  bit.envs/compilers/react@2.0.0
- Bit tester (include version):

**Comment by davidfirst** [comment]
@nelsonkent , something very strange there. Please try to run `bit logout` and then `bit login` and export.

**Comment by nelsonkent** [comment]
Hi davidfirst,   run bit logout and then bit login is not working, but somehow i add extra package.json on subcategory of project root and run bit init again ... , the error and related java-script heap out of memory is solved.
I think the error might lies on self calculating dependencies.
I'll close this error now.

**Comment by nelsonkent** [comment]
Hi davidfirst,   run bit logout and then bit login is not working, but somehow i add extra package.json on subcategory of project root and run bit init again ... , the error and related java-script heap out of memory is solved.
I think the error might lies on self calculating dependencies.
I'll close this error now.
