### ISSUE TITLE
Link does not work within Docker

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#4525]
### Describe the bug
Could not make dockerfile works, do not understand the problem.

### Steps to Reproduce
```sh
docker build --rm --platform linux/amd64  --progress=plain .
```

Note: Added --platform linux/amd64 due to using m1 mac.

```Dockerfile
FROM node:14.16.0-alpine3.11 AS bvm

# Install Bvm and Bit for reusable components
RUN yarn global add @teambit/bvm && bvm install
RUN ln -s ~/bin/bit /usr/local/bin/bit &&  bit -v
#RUN yarn global add @teambit/bit \
#   && ln -s /usr/local/bin/bbit /usr/local/bin/bit \
#   && ln -s /tmp/symphony/etc/.bitrc.jsonc ~/.bitrc.jsonc \
#  && bit -v

# config bit analytics
RUN bit config set analytics_reporting false \
 && bit config set error_reporting false \
# && bit config set no_warnings true \
 && bit config set interactive false

# ---- Base Node ----
FROM bvm AS base
WORKDIR /usr/src/app
# copy dependencies confs
COPY package.json  .
COPY yarn.lock  .
COPY .yarnrc .
# copy build/infrastructure scripts
COPY scripts scripts

# ---- Dependencies ----
FROM base AS prod-dependencies
# install only production node_modules
RUN SKIP_POSTSCRIPT=1 yarn install --production

# ---- Dependencies ----
FROM prod-dependencies AS dependencies
# install ALL node_modules, including 'devDependencies'
RUN SKIP_POSTSCRIPT=1 yarn install

# ---- Bit Dependencies ----
FROM dependencies AS bit-dependencies
LABEL step=bit
# copy essential components folders
COPY extensions extensions
COPY components components
COPY constants constants
COPY graphql graphql
COPY lib lib
# copy bitmap and bit workspace config
COPY .bitmap .
COPY workspace.jsonc .
# link bit dependencies
# RUN bit init --harmony --log
RUN bit link --log

# ---- Test ----
# run type-checks and tests
FROM bit-dependencies AS test
# to define ID for images will be created
ARG PROFILING
ENV PROFILING=$PROFILING
ARG VERSION
ENV VERSION=$VERSION
LABEL version=$VERSION
LABEL step=test
COPY . .
RUN yarn type-check
RUN yarn test
RUN yarn lint-as-markdown

# ---- Build ----
FROM test AS build
LABEL step=build
RUN yarn build

# ---- Release ----
FROM base AS release
LABEL step=release
# copy production node_modules
COPY --from=prod-dependencies /usr/src/app/node_modules ./node_modules
# copy app bundles (next/server/storybook)
COPY --from=build /usr/src/app/.next .next
COPY --from=build /usr/src/app/dist dist
COPY --from=build /usr/src/app/.out .out
# Copy tsconfig confs for server import absolute paths
COPY --from=build /usr/src/app/tsconfig.server.json .
# Copy scripts
COPY --from=build /usr/src/app/scripts scripts
# Copy locales
COPY --from=build /usr/src/app/static static
# Copy public dir
COPY --from=build /usr/src/app/public public

# ---- Define CMD ----
CMD [ "yarn", "run", "start" ]
```

### Expected Behavior
The same behaviour as without Docker.

### Screenshots, exceptions and logs
```
#25 [bit-dependencies 8/8] RUN bit link --log
#25 sha256:46df484e972200986b281c77d7b7550ca837f9a0a908396f75c5bc519dbe0fa5
#25 2.158 /bin/sh: git: not found
#25 2.191 /bin/sh: git: not found
#25 2.563 /bin/sh: git: not found
#25 2.568 Warning: running bit as root might cause permission issues later
#25 3.498 /bin/sh: git: not found
#25 4.097 /bin/sh: git: not found
#25 4.191 /bin/sh: git: not found
#25 4.597 /bin/sh: git: not found
#25 6.583 - loading aspects...
#25 6.747 /bin/sh: git: not found
#25 6.767 /bin/sh: git: not found
#25 6.807 - running command "link"...
#25 6.846 teambit.workspace/workspace, Linking components and core aspects to node_modules for workspaces: 'company'
#25 6.847   Linking components and core aspects to node_modules for workspaces: 'company'
#25 6.914 teambit.workspace/workspace, loading components (total: 6)
#25 6.914 - teambit.workspace/workspace, loading components (total: 6)
#25 6.920 teambit.workspace/workspace, loading components (1/6). company.bit-extensions/config/jest@0.0.1
#25 6.920 - teambit.workspace/workspace, loading components (1/6). company.bit-extensions/config/jest@0.0.1
#25 6.931 ComponentLoader, loading consumer-components from the file-system, ids: company.bit-extensions/config/jest@0.0.1
#25 6.943 ComponentLoader, the following 0 components have been already loaded, get them from the cache.
#25 6.979 failed finding a component company.bit-extensions/config/jest with hash: b0a62a18f3ecf084677b3ae280dcee94f6bf5a1f
#25 6.988 failed finding a component company.bit-extensions/config/jest with hash: b0a62a18f3ecf084677b3ae280dcee94f6bf5a1f
#25 7.007 got an error from command link: ComponentsPendingImport
#25 7.009 ComponentsPendingImport
#25 7.009     at Function.loadFromFileSystem (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/legacy/dist/consumer/component/consumer-component.js:1399:41)
#25 7.009     at async ComponentLoader.loadOne (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/legacy/dist/consumer/component/component-loader.js:345:19)
#25 7.009     at async /root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/legacy/dist/consumer/component/component-loader.js:297:25
#25 7.009     at async pMapSeries (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/p-map-series/index.js:9:15)
#25 7.009     at async ComponentLoader.loadMany (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/legacy/dist/consumer/component/component-loader.js:296:5)
#25 7.009     at async Consumer.loadComponent (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/legacy/dist/consumer/consumer.js:787:9)
#25 7.009     at async WorkspaceComponentLoader.getConsumerComponent (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/workspace/dist/workspace-component/workspace-component-loader.js:333:95)
#25 7.009     at async WorkspaceComponentLoader.get (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/workspace/dist/workspace-component/workspace-component-loader.js:256:51)
#25 7.009     at async pMapSeries (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/p-map-series/index.js:9:15)
#25 7.009     at async WorkspaceComponentLoader.getMany (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/workspace/dist/workspace-component/workspace-component-loader.js:209:24)
#25 7.009     at async Workspace.getComponentsDirectory (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/workspace/dist/workspace.js:1364:63)
#25 7.009     at async Workspace.link (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/workspace/dist/workspace.js:1452:24)
#25 7.009     at async LinkCommand.json (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/workspace/dist/link/link.cmd.js:171:25)
#25 7.009     at async LinkCommand.report (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/workspace/dist/link/link.cmd.js:129:25)
#25 7.009     at async CommandRunner.runReportHandler (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/cli/dist/command-runner.js:214:20)
#25 7.009     at async CommandRunner.runCommand (/root/.bvm/versions/0.0.443/bit-0.0.443/node_modules/@teambit/cli/dist/command-runner.js:140:16)
#25 7.243 user gets the following error: your workspace has outdated objects. please use "bit import" to pull the latest objects from the remote scope
#25 7.245 your workspace has outdated objects. please use "bit import" to pull the latest objects from the remote scope
#25 7.246 [*] the command "link" has been terminated with an error code 1
#25 ERROR: executor failed running [/bin/sh -c bit link --log]: exit code: 1
------
 > [bit-dependencies 8/8] RUN bit link --log:
------
executor failed running [/bin/sh -c bit link --log]: exit code: 1
```

### Specifications
* Bit version: 0.0.443
* Workspace type: harmony
* Node version: 14 LTS
* yarn version: 1.22.10
* Platform: Mac M1

_for harmony workspace_

* relevant env
* relevant aspects

```json
{
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  "teambit.workspace/workspace": {
    "name": "company",
    "icon": "https://static.bit.dev/bit-logo.svg",
    "defaultDirectory": "{scope}/{name}",
    "defaultScope": "company.components"
  },
  "teambit.dependencies/dependency-resolver": {
    "packageManager": "teambit.dependencies/yarn",
    "policy": {
      "dependencies": {},
      "peerDependencies": {
        "react": "16.14.0",
        "react-dom": "16.14.0",
        "typescript": "3.8.3",
        "jest": {
          "version": "26.6.3",
          "resolveFromEnv": true
        },
        "@types/jest": "26.0.23"
      }
    }
  },
  "teambit.ui-foundation/ui": {
    "port": 3040,
    "portRange": [
      3000,
      3100
    ],
    "host": "localhost",
    "publicDir": ".bit/public"
  },
  "teambit.workspace/variants": {
    "extensions": {
      "defaultScope": "company.bit-extensions",
      "teambit.harmony/aspect": {}
    },
    "extensions/config": {
      "defaultScope": "company.bit-extensions",
      "teambit.harmony/node": {},
      "teambit.envs/envs": {
        "env": "teambit.harmony/node"
      }
    },
    "extensions/config/jest": {
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "dependencies": {
            "jest": "26.6.3"
          },
          "peerDependencies": {
            "babel-jest": "*"
          }
        }
      }
    },
    "components": {
      "defaultScope": "company.components",
      "teambit.react/react": {}
    },
    "constants": {
      "defaultScope": "company.constants",
      "company.bit-extensions/custom-node": {}
    },
    "lib": {
      "defaultScope": "company.libs",
      "company.bit-extensions/custom-node": {}
    },
    "graphql": {
      "defaultScope": "company.graphql",
      "teambit.react/react": {}
    }
  }
}
```

```json
{
    "config/jest": {
        "scope": "company.bit-extensions",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "extensions/config/jest"
    },
    "constants": {
        "scope": "company.constants",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "constants"
    },
    "contexts": {
        "scope": "company.graphql",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "graphql/contexts"
    },
    "custom-node": {
        "scope": "company.bit-extensions",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "extensions/custom-node"
    },
    "custom-react": {
        "scope": "company.bit-extensions",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "extensions/custom-react"
    },
    "types": {
        "scope": "company.graphql",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "graphql/types"
    },
    "$schema-version": "14.9.0"
}
```

**Comment by itaymendel** [comment]
hi, try and add `bit import` step before running `bit link`.

**Comment by ivansky** [comment]
Hi @itaymendel, the thing is, why I need import anything when there are local components that are added to Docker context?
Bit Import means that it needs authentication, SSH keys and something else, right? Why I need it in Docker?

**Comment by ivansky** [comment]
I've tried `bit import` before link, and as expected it returns 403. Why it needs remote when there are local components that are the same? I could not get it. 
I also added installing git to get rid of error messages about missing git.

**Comment by GiladShoham** [comment]
@davidfirst why do we need import in order for bit link to work?

@ivansky By the way, I would replace this line (in the bvm docker) `RUN ln -s ~/bin/bit /usr/local/bin/bit &&  bit -v`
with `bvm link` and adding the relevant dir to the path.
Or replace the `bvm install` with `bvm upgrade` which will perform the link already. and mutate the path env variable.
see here - https://github.com/teambit/bit/blob/master/scripts/docker-teambit-bit/Dockerfile-bit#L6

**Comment by ivansky** [comment]
Well I tried with bit token it works but it does not find components, just download new ones for some reason, there is somewhere a problem with checking local workspace.

**Comment by davidfirst** [comment]
@GiladShoham , maybe it's part of loading the components, which does the import for out-of-sync scenarios.

**Comment by itaymendel** [comment]
please use this for setting up your workspace - https://github.com/RWransky/bit-docker
