### ISSUE TITLE
Import freezes and fails on resolution step

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#4563]
### Describe the bug
Could not pass Resolution step even for package that does not have any dependencies.

### Steps to Reproduce
1. bitmap is empty
1. `some-package` might be already download to folder, but bitmap was not changed.
1. `bit import some-package --override --log`

### Expected Behavior
Do not stuck.

### Screenshots, exceptions and logs
```
✗ bit import company.bit-extensions/config/jest -p extensions/config/jest --override --log
⢀⠀ loading aspects...importSpecificComponents, Ids: company.bit-extensions/config/jest
scope.getManyWithAllVersions, Ids: company.bit-extensions/config/jest
importMany, cache false, throwForDependencyNotFound: false. ids: company.bit-extensions/config/jest
sources.getMany, Ids: company.bit-extensions/config/jest
total missing externals: 1
⡀⠀ importing componentsScopeComponentsImporter.getExternalMany, fetching from remote scope. Ids: company.bit-extensions/config/jest
enrich context from global config
reading ssh public key from /Users/user/.ssh/id_rsa.pub
[-] Running fetch on remotes, with the following options
    type: "component"
    withoutDependencies: false
    includeArtifacts: false
⠉⠩ importing componentsHttp.fetch, scopeName: company.bit-extensions, url: https://ovvniw8.scopes.bit.dev/api/scope/fetch
⠍⡐ importing componentsHttp.fetch got a response, scopeName: company.bit-extensions, url: https://ovvniw8.scopes.bit.dev/api/scope/fetch, status 200, statusText OK
fromTarToObjectStream, start getting data
    schema: "1.0.0"
    scopeName: "company.bit-extensions"
⢋⠠ importing componentsfromTarToObjectStream, finished getting data
    numOfFiles: 6
    scopeName: "company.bit-extensions"
fromTarToObjectStream, pipeline is completed
[-] fetchFromRemoteAndWrite, completed writing all objects
sources.getMany, Ids: company.bit-extensions/config/jest
bitIdsToVersionDeps, 1 ids
sources.getMany, Ids: company.bit-extensions/config/jest
importMany, completed!
importWithoutDeps, ids: company.bit-extensions/config/jest@d12b9746e777b2d6d5de17d537a103a8669c6600
getExternalManyWithoutDeps, ids: company.bit-extensions/config/jest@d12b9746e777b2d6d5de17d537a103a8669c6600, localFetch: true
sources.getMany, Ids: company.bit-extensions/config/jest@d12b9746e777b2d6d5de17d537a103a8669c6600
getExternalManyWithoutDeps, no more ids left, all found locally
model-component, converting company.bit-extensions/config/jest, version: 0.0.1 to ConsumerComponent
ManyComponentsWriter, _writeComponentsAndDependencies
adding to bit.map company.bit-extensions/config/jest@0.0.1
adding to bit.map company.bit-extensions/config/jest@0.0.1
package-json.preparePackageJsonToWrite. bitDir node_modules/@company/bit-extensions.config.jest. override true
⡋⢀ all objects were processed and written to the filesystem successfullyteambit.workspace/workspace, get company.bit-extensions/config/jest@0.0.1
ComponentLoader, loading consumer-components from the file-system, ids: company.bit-extensions/config/jest@0.0.1
ComponentLoader, the following 0 components have been already loaded, get them from the cache.
model-component, converting company.bit-extensions/config/jest, version: 0.0.1 to ConsumerComponent
componentConfigLoad, running on load even for component company.bit-extensions/config/jest@0.0.1
teambit.scope/scope, ScopeComponentLoader.get, loading company.bit-extensions/config/jest@0.0.1
model-component, converting company.bit-extensions/config/jest, version: 0.0.1 to ConsumerComponent
⡋⠁ all objects were processed and written to the filesystem successfullyteambit.workspace/workspace, get company.bit-extensions/config/jest@0.0.1
⠍⠉ all objects were processed and written to the filesystem successfullyteambit.workspace/workspace, get company.bit-extensions/config/jest@0.0.1
ComponentLoader, Finished loading the component "company.bit-extensions/config/jest@0.0.1"
DataToPersist, paths-to-delete:
/Users/user/Workspace/pj/project-frontend/extensions/config/jest
DataToPersist, paths-to-write:
/Users/user/Workspace/pj/project-frontend/extensions/config/jest/index.ts
/Users/user/Workspace/pj/project-frontend/extensions/config/jest/jest.config.js
/Users/user/Workspace/pj/project-frontend/extensions/config/jest/jest.setup.js
/Users/user/Workspace/pj/project-frontend/node_modules/@company/bit-extensions.config.jest/package.json
writing a file to the file-system at /Users/user/Workspace/pj/project-frontend/extensions/config/jest/index.ts, force: true
writing a file to the file-system at /Users/user/Workspace/pj/project-frontend/extensions/config/jest/jest.config.js, force: true
writing a file to the file-system at /Users/user/Workspace/pj/project-frontend/extensions/config/jest/jest.setup.js, force: true
package-json-vinyl.write, path /Users/user/Workspace/pj/project-frontend/node_modules/@company/bit-extensions.config.jest/package.json
ManyComponentsWriter, _installPackages
teambit.workspace/workspace, installing dependencies in workspace using teambit.dependencies/yarn
  installing dependencies in workspace using teambit.dependencies/yarn
teambit.workspace/workspace, installing dependencies in workspace with options
    dedupe: true
    updateExisting: false
    import: false
teambit.workspace/workspace, clearing the workspace and scope caches
repository.clearCache
teambit.workspace/workspace, loading components (total: 1)
⢀⠀ teambit.workspace/workspace, loading components (total: 1)teambit.workspace/workspace, loading components (1/1). company.bit-extensions/config/jest@0.0.1
⢀⠀ teambit.workspace/workspace, loading components (1/1). company.bit-extensions/config/jest@0.0.1ComponentLoader, loading consumer-components from the file-system, ids: company.bit-extensions/config/jest@0.0.1
ComponentLoader, the following 1 components have been already loaded, get them from the cache. company.bit-extensions/config/jest@0.0.1
teambit.scope/scope, ScopeComponentLoader.get, loading company.bit-extensions/config/jest@0.0.1
model-component, converting company.bit-extensions/config/jest, version: 0.0.1 to ConsumerComponent
⢀⠀ running pre install subscribersteambit.dependencies/dependency-resolver, running pre install subscribers
✔ running pre install subscribers
✔ deduping dependencies for installation
(workspace): teambit.dependencies/yarn, root manifest for installation
    version: "1.0.0"
    dependencies: {
      "babel-jest": "*",
      "jest": "26.6.3",
      "styled-components": "5.3.0",
      "react-dom": "17.0.2",
      "react": "17.0.2",
      "next-with-apollo": "5.2.1",
      "next-i18next": "8.5.3",
      "next": "11.0.1",
      "express": "4.17.1",
      "envalid": "7.1.1",
      "core-js": "3.12.1",
      "cookie-parser": "1.4.5",
      "apollo-link-retry": "2.2.16",
      "apollo-link-http": "1.5.17",
      "apollo-link-error": "1.1.13",
      "apollo-link-context": "1.0.20",
      "apollo-link": "1.2.14",
      "apollo-client": "2.6.10",
      "apollo-cache-inmemory": "1.6.6",
      "@opentelemetry/tracing": "0.20.0",
      "@opentelemetry/propagator-b3": "0.20.0",
      "@opentelemetry/node": "0.20.0",
      "@opentelemetry/instrumentation-http": "0.20.0",
      "@opentelemetry/instrumentation-express": "0.16.0",
      "@opentelemetry/exporter-jaeger": "0.20.0",
      "@opentelemetry/core": "0.20.0",
      "@opentelemetry/api": "0.20.0",
      "@apollo/react-testing": "3.1.3",
      "@apollo/react-ssr": "3.1.3",
      "@apollo/react-hooks": "3.1.3",
      "typescript": "4.3.5",
      "svgo": "2.3.1",
      "rollup": "2.53.1",
      "prettier": "2.3.2",
      "next-optimized-images": "2.6.2",
      "next-compose-plugins": "2.2.1",
      "imagemin-svgo": "9.0.0",
      "eslint-plugin-react-hooks": "4.2.0",
      "eslint-plugin-react": "7.22.0",
      "eslint-plugin-prettier": "3.3.1",
      "eslint-plugin-jsx-a11y": "6.4.1",
      "eslint-plugin-import": "2.22.1",
      "eslint-plugin-i18next": "4.3.0",
      "eslint-import-resolver-typescript": "2.4.0",
      "eslint-import-resolver-custom-alias": "1.2.0",
      "eslint-config-prettier": "8.1.0",
      "eslint": "7.22.0",
      "babel-plugin-styled-components": "1.11.1",
      "babel-plugin-module-resolver": "4.1.0",
      "babel-plugin-lodash": "3.3.4",
      "babel-loader": "8.2.2",
      "@types/react": "17.0.14",
      "@types/express": "4.17.13",
      "@rollup/plugin-run": "2.0.2",
      "@rollup/plugin-node-resolve": "13.0.0",
      "@rollup/plugin-commonjs": "19.0.0",
      "@rollup/plugin-babel": "5.3.0",
      "@next/bundle-analyzer": "11.0.1",
      "@company/platform-graphql-api": "1.5.0-alpha.1030",
      "@graphql-codegen/typescript-resolvers": "1.17.10",
      "@graphql-codegen/typescript-react-apollo": "1.17.7",
      "@graphql-codegen/typescript-operations": "1.17.7",
      "@graphql-codegen/typescript": "1.17.8",
      "@graphql-codegen/near-operation-file-preset": "1.17.11",
      "@graphql-codegen/fragment-matcher": "1.17.8",
      "@graphql-codegen/cli": "1.17.8",
      "@flyke/svg-sprite-generator": "0.0.7",
      "@babel/preset-typescript": "7.14.5",
      "@babel/preset-env": "7.14.7",
      "@babel/core": "7.14.6",
      "@arkweid/lefthook": "0.7.0"
    }
    devDependencies: {
      "@babel/runtime": "7.12.18",
      "@types/node": "12.20.4",
      "@types/jest": "26.0.20"
    }
    peerDependencies: {
      "babel-jest": "*"
    }
teambit.dependencies/yarn, components manifests for installation
    /Users/user/Workspace/pj/project-frontend/extensions/config/jest: {
      "name": "@company/bit-extensions.config.jest",
      "version": "0.0.1",
      "dependencies": {},
      "devDependencies": {},
      "peerDependencies": {}
    }
➤ YN0000: ┌ Resolution step
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ sane@npm:4.1.0 is deprecated: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0001: │ ReadError: The server aborted pending request
    at IncomingMessage.<anonymous> (/Users/user/.bvm/versions/0.0.451/bit-0.0.451/node_modules/got/dist/source/core/index.js:803:31)
    at Object.onceWrapper (events.js:481:28)
    at IncomingMessage.emit (events.js:375:28)
    at IncomingMessage.origin.emit (/Users/user/.bvm/versions/0.0.451/bit-0.0.451/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketCloseListener (_http_client.js:432:11)
    at TLSSocket.emit (events.js:387:35)
    at net.js:675:12
    at TCP.done (_tls_wrap.js:563:7)
➤ YN0000: └ Completed in 7m 60s
➤ YN0000: Failed with errors in 7m 60s
```

### Specifications
* Bit version: 0.0.451
* Workspace type: harmony
* Node version: 14 lts
* yarn version: 1
* Platform: osx m1

**Comment by ivansky** [comment]
Also tried with `0.0.443` version, no luck

**Comment by ivansky** [comment]
Hi @GiladShoham Yes all the packages went from private Nexus artifactory, this artifactory is also configured as proxy to original one.

**Comment by GiladShoham** [comment]
how do the npmrc look like?
did you change the default registry?
(if you can paste here the npmrc, with fake tokens / fake URLs)
And does your nexus proxy node.bit.dev as well? (with auth?)

**Comment by ivansky** [comment]
@GiladShoham 
`.yarnrc` anyway does not work yet due to #3975 
```
registry "https://nexus.hotelplan.net/repository/npm/"
"@bit:registry" "https://node.bit.dev"
```
`.npmrc`
```
registry=https://nexus.hotelplan.net/repository/npm/
```
No we don't have Nexus proxy to node.bit.dev, is it documented somewhere?

**Comment by ivansky** [comment]
@GiladShoham 
`.yarnrc` anyway does not work yet due to #3975 
```
registry "https://nexus.company.net/repository/npm/"
"@bit:registry" "https://node.bit.dev"
```
`.npmrc`
```
registry=https://nexus.company.net/repository/npm/
```
No we don't have Nexus proxy to node.bit.dev, is it documented somewhere?

**Comment by GiladShoham** [comment]
Did you configured the pkg aspect so your packages will be published to another registry instead of bit.dev registry?
If not, then any component that you export will have its package in the bit.dev registry (node.bit.dev)
In that case, when you try to install them, since you configured nexus as default, yarn will go to nexus, and won't find those packages.

**Comment by ivansky** [comment]
@GiladShoham just to be clear what kind of scope it uses? `@company` or `@bit`?

**Comment by GiladShoham** [comment]
For legacy scope its @bit for harmony scopes @organization or @user (the scope owner)

**Comment by ivansky** [comment]
@GiladShoham Thanks! It leads to the existing issue with organization npm scope intersection #4560 
There was already private registry with the same scope name as name of organization in bit.dev.
How to resolve this scenario? Now it's kind of hard to change name in private registry and in bit.dev, the huge work is done. 
Could we figure out a workaround to keep names the same?

**Comment by itaymendel** [comment]
sadly we can't resolve this issue with npmrc, as this is an npm problem.
closing the issue as item is resolved 2 years ago.
