### ISSUE TITLE
bit start warning when deleting tagged component 

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4577]
When deleting a tagged component, getting this sticky error in blue:

```
watcher found an error while handling /Users/kutner/projects/temp/add-compo-bug/exp/react/react01/react01.spec.tsx,
Cannot read property 'getFilesRelativeToConsumer' of undefined
watcher found an error while handling /Users/kutner/projects/temp/add-compo-bug/exp/react/react01/index.ts,
Cannot read property 'getFilesRelativeToConsumer' of undefined
watcher found an error while handling /Users/kutner/projects/temp/add-compo-bug/
file removed                        
correctly removing kutnerjs.exp/react/react01@0.0.1
```

Not critical, but needs to be handled.

(detailed log in the next comment)

### Steps to Reproduce
1. bit init --harmony
1. set default scope
1. set react as env
1. `bd create react-component react/react01`
1. `bd start`
1. `bd remove -d react/react01` (+ approve)

### Expected Behavior
should not show error

### Specifications
* Bit version: 445
* Workspace type: harmony
* Platform: MacOS

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by KutnerUri** [comment]
log:
```
[2021-07-14 18:29:59.324 +0300] DEBUG (73253): teambit.workspace/workspace, failed loading component "kutnerjs.exp/react/react01@0.0.1" from the workspace due to "ComponentNotFoundInPath" error
   error: component in path "/Users/kutner/projects/temp/add-compo-bug/exp/react/react01" was not found
[2021-07-14 18:29:59.324 +0300] ERROR (73253): watcher found an error while handling /Users/kutner/projects/temp/add-compo-bug/exp/react/react01/react01.spec.tsx
    TypeError: Cannot read property 'getFilesRelativeToConsumer' of undefined
        at Watcher.getComponentIdAndClearItsCache (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:375:22)
        at async Watcher.handleChange (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:228:27)
        at async FSWatcher.<anonymous> (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:209:9)
[2021-07-14 18:29:59.330 +0300] DEBUG (73253): teambit.workspace/workspace, failed loading component "kutnerjs.exp/react/react01@0.0.1" from the workspace due to "ComponentNotFoundInPath" error
error: component in path "/Users/kutner/projects/temp/add-compo-bug/exp/react/react01" was not found
[2021-07-14 18:29:59.330 +0300] ERROR (73253): watcher found an error while handling /Users/kutner/projects/temp/add-compo-bug/exp/react/react01/index.ts
    TypeError: Cannot read property 'getFilesRelativeToConsumer' of undefined
        at Watcher.getComponentIdAndClearItsCache (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:375:22)
        at async Watcher.handleChange (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:228:27)
        at async FSWatcher.<anonymous> (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:209:9)
[2021-07-14 18:29:59.331 +0300] DEBUG (73253): teambit.workspace/workspace, failed loading component "kutnerjs.exp/react/react01@0.0.1" from the workspace due to "ComponentNotFoundInPath" error
error: component in path "/Users/kutner/projects/temp/add-compo-bug/exp/react/react01" was not found
[2021-07-14 18:29:59.331 +0300] ERROR (73253): watcher found an error while handling /Users/kutner/projects/temp/add-compo-bug/exp/react/react01/react01.composition.tsx
    TypeError: Cannot read property 'getFilesRelativeToConsumer' of undefined
        at Watcher.getComponentIdAndClearItsCache (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:375:22)
        at async Watcher.handleChange (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:228:27)
        at async FSWatcher.<anonymous> (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:209:9)
[2021-07-14 18:29:59.332 +0300] DEBUG (73253): teambit.workspace/workspace, failed loading component "kutnerjs.exp/react/react01@0.0.1" from the workspace due to "ComponentNotFoundInPath" error
error: component in path "/Users/kutner/projects/temp/add-compo-bug/exp/react/react01" was not found
[2021-07-14 18:29:59.332 +0300] ERROR (73253): watcher found an error while handling /Users/kutner/projects/temp/add-compo-bug/exp/react/react01/react01.docs.mdx
    TypeError: Cannot read property 'getFilesRelativeToConsumer' of undefined
        at Watcher.getComponentIdAndClearItsCache (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:375:22)
        at async Watcher.handleChange (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:228:27)
        at async FSWatcher.<anonymous> (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:209:9)
[2021-07-14 18:29:59.336 +0300] DEBUG (73253): teambit.workspace/workspace, failed loading component "kutnerjs.exp/react/react01@0.0.1" from the workspace due to "ComponentNotFoundInPath" error
error: component in path "/Users/kutner/projects/temp/add-compo-bug/exp/react/react01" was not found
[2021-07-14 18:29:59.337 +0300] ERROR (73253): watcher found an error while handling /Users/kutner/projects/temp/add-compo-bug/exp/react/react01/react01.tsx
    TypeError: Cannot read property 'getFilesRelativeToConsumer' of undefined
        at Watcher.getComponentIdAndClearItsCache (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:375:22)
        at async Watcher.handleChange (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:228:27)
        at async FSWatcher.<anonymous> (/Users/kutner/projects/bit-bin/node_modules/@teambit/workspace/dist/watch/watcher.js:209:9)
```

**Comment by itaymendel** [comment]
no longer relevant
