### ISSUE TITLE
can't removed tagged component with custom env

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4578]
When running `bit remove` on a component with a custom env, failing with this error:

```
failed loading version 0.0.1 of enved/react01 from the scope
```

Very odd. 

### Steps to Reproduce
1. init new project (+ install `react` / `react-dom`, needed for tests)
1. create new env (`ev`
1. set `ev` as env
1. `bit create react-component enved/react01`
1. `bit tag -a`
1. `bd remove -d enved/react01` (+ confirm)
--> failing with the error.

see attached file for a workspace with reproduction:
[reproduction.zip](https://github.com/teambit/bit/files/6817392/reproduction.zip)

### Expected Behavior
Should delete `enved/react01` with no problems.

### Specifications
* Bit version: 0.0.455
* Workspace type: harmony
* Platform: MacOS

_for harmony workspace_

* relevant env
* relevant aspects

**Comment by KutnerUri** [comment]
log:

```
[2021-07-14 18:45:42.598 +0300] DEBUG (73856): workspace-config, isLegacy: false
[2021-07-14 18:45:42.839 +0300] DEBUG (73856): workspace-config, isLegacy: false
[2021-07-14 18:45:42.847 +0300] DEBUG (73856): legacy-extensions.extensions-loader, start loading extensions
[2021-07-14 18:45:43.162 +0300] DEBUG (73856): base-extension loading bit.extensions/workspace/reset-to-add@1.0.0
[2021-07-14 18:45:43.164 +0300] DEBUG (73856): base-extension, loading extension bit.extensions/workspace/reset-to-add@1.0.0 from /Users/kutner/projects/tools/reset-to-add/components/workspace/reset-to-add
[2021-07-14 18:45:43.206 +0300] DEBUG (73856): base-extension - loadDynamicConfig
[2021-07-14 18:45:43.209 +0300] INFO (73856): registering new command reset-to-add
[2021-07-14 18:45:43.550 +0300] DEBUG (73856): scope.load, found scope at /Users/kutner/projects/temp/add-compo-bug/.git/bit from cache
[2021-07-14 18:45:44.006 +0300] INFO (73856): [*] started a new command: "remove" with the following data:
    args: [
      [
        "enved/react01"
      ]
    ]
    flags: {
      "delete-files": true,
      "deleteFiles": true,
      "ids": [
        "enved/react01"
      ]
    }
[2021-07-14 18:45:44.007 +0300] DEBUG (73856): Checking if a migration is needed
[2021-07-14 18:45:45.804 +0300] DEBUG (73856): removeComponents, enved/react01. force: false
[2021-07-14 18:45:45.842 +0300] DEBUG (73856): ComponentLoader, loading consumer-components from the file-system, ids: enved/react01
[2021-07-14 18:45:45.845 +0300] DEBUG (73856): ComponentLoader, the following 0 components have been already loaded, get them from the cache. 
[2021-07-14 18:45:45.848 +0300] DEBUG (73856): sources.get, found enved/react01, however version 0.0.1 object was not found on the filesystem
[2021-07-14 18:45:45.852 +0300] DEBUG (73856): componentConfigLoad, running on load even for component enved/react01@0.0.1
[2021-07-14 18:45:45.895 +0300] DEBUG (73856): teambit.scope/scope, ScopeComponentLoader.get, loading kutnerjs.exp/enved/react01@0.0.1
[2021-07-14 18:45:45.896 +0300] DEBUG (73856): sources.get, found enved/react01, however version 0.0.1 object was not found on the filesystem
[2021-07-14 18:45:45.896 +0300] DEBUG (73856): failed finding a component add-compo-bug/enved/react01 with hash: 1353507d49662762b4596479129784808f64bb29
[2021-07-14 18:45:45.901 +0300] DEBUG (73856): importMany, cache true, throwForDependencyNotFound: false. ids: 
[2021-07-14 18:45:45.902 +0300] DEBUG (73856): teambit.scope/scope, ScopeComponentLoader.get, loading kutnerjs.exp/envs/react@0.0.1
[2021-07-14 18:45:45.910 +0300] DEBUG (73856): model-component, converting envs/react, version: 0.0.1 to ConsumerComponent
[2021-07-14 18:45:45.994 +0300] INFO (73856): teambit.workspace/workspace, loading components (total: 1)
[2021-07-14 18:45:45.995 +0300] DEBUG (73856): teambit.workspace/workspace, loading components (1/1). kutnerjs.exp/envs/react@0.0.1
[2021-07-14 18:45:45.995 +0300] DEBUG (73856): ComponentLoader, loading consumer-components from the file-system, ids: envs/react@0.0.1
[2021-07-14 18:45:45.996 +0300] DEBUG (73856): ComponentLoader, the following 0 components have been already loaded, get them from the cache. 
[2021-07-14 18:45:45.997 +0300] DEBUG (73856): model-component, converting envs/react, version: 0.0.1 to ConsumerComponent
[2021-07-14 18:45:45.999 +0300] DEBUG (73856): componentConfigLoad, running on load even for component envs/react@0.0.1
[2021-07-14 18:45:46.117 +0300] DEBUG (73856): dependencies-loader, getting the dependencies data for envs/react@0.0.1 from the cache
[2021-07-14 18:45:46.149 +0300] DEBUG (73856): teambit.workspace/workspace, get kutnerjs.exp/envs/react@0.0.1
[2021-07-14 18:45:46.164 +0300] DEBUG (73856): ComponentLoader, Finished loading the component "envs/react@0.0.1"
[2021-07-14 18:45:46.187 +0300] INFO (73856): teambit.workspace/workspace, loading components (completed in 177ms)
[2021-07-14 18:45:46.289 +0300] DEBUG (73856): GraphFromFsBuilder, buildGraph with 1 seeders
[2021-07-14 18:45:46.290 +0300] DEBUG (73856): ComponentLoader, loadForCapsule, id: envs/react@0.0.1
[2021-07-14 18:45:46.290 +0300] DEBUG (73856): ComponentLoader, loading consumer-components from the file-system, ids: envs/react@0.0.1
[2021-07-14 18:45:46.291 +0300] DEBUG (73856): ComponentLoader, the following 1 components have been already loaded, get them from the cache. envs/react@0.0.1
[2021-07-14 18:45:46.291 +0300] DEBUG (73856): ComponentLoader, loadForCapsule finished loading the component "envs/react@0.0.1"
[2021-07-14 18:45:46.292 +0300] DEBUG (73856): GraphFromFsBuilder.processManyComponents depth 1, 1 components
[2021-07-14 18:45:46.295 +0300] DEBUG (73856): importMany, cache true, throwForDependencyNotFound: true. ids: 
[2021-07-14 18:45:46.297 +0300] INFO (73856): teambit.workspace/workspace, loading components (total: 1)
[2021-07-14 18:45:46.297 +0300] DEBUG (73856): teambit.workspace/workspace, loading components (1/1). kutnerjs.exp/envs/react@0.0.1
[2021-07-14 18:45:46.298 +0300] INFO (73856): teambit.workspace/workspace, loading components (completed in 1ms)
[2021-07-14 18:45:46.404 +0300] DEBUG (73856): sources.get, found enved/react01, however version 0.0.1 object was not found on the filesystem
[2021-07-14 18:45:46.405 +0300] DEBUG (73856): bit-map: no need to update enved/react01@0.0.1
[2021-07-14 18:45:46.407 +0300] DEBUG (73856): dependencies-loader, getting the dependencies data for enved/react01@0.0.1 from the cache
[2021-07-14 18:45:46.408 +0300] DEBUG (73856): found dependency version 0.0.1 for envs/react@0.0.1 in strategy getCurrentVersion
[2021-07-14 18:45:46.409 +0300] DEBUG (73856): teambit.workspace/workspace, get kutnerjs.exp/enved/react01@0.0.1
[2021-07-14 18:45:46.409 +0300] DEBUG (73856): teambit.scope/scope, ScopeComponentLoader.get, loading kutnerjs.exp/enved/react01@0.0.1
[2021-07-14 18:45:46.410 +0300] DEBUG (73856): sources.get, found enved/react01, however version 0.0.1 object was not found on the filesystem
[2021-07-14 18:45:46.410 +0300] DEBUG (73856): failed finding a component add-compo-bug/enved/react01 with hash: 1353507d49662762b4596479129784808f64bb29
[2021-07-14 18:45:46.896 +0300] DEBUG (73856): teambit.workspace/workspace, get kutnerjs.exp/envs/react@0.0.1
[2021-07-14 18:45:46.898 +0300] DEBUG (73856): ComponentLoader, Finished loading the component "enved/react01@0.0.1"
[2021-07-14 18:45:46.909 +0300] ERROR (73856): got an error from command remove: ShowDoctorError
[2021-07-14 18:45:46.909 +0300] ERROR (73856): ShowDoctorError
    at ComponentStatusLoader.getStatus (/Users/kutner/projects/bit-bin/node_modules/@teambit/legacy/dist/consumer/component-ops/component-status-loader.js:196:13)
    at async ComponentStatusLoader.getComponentStatusById (/Users/kutner/projects/bit-bin/node_modules/@teambit/legacy/dist/consumer/component-ops/component-status-loader.js:136:52)
    at async /Users/kutner/projects/bit-bin/node_modules/@teambit/legacy/dist/consumer/component-ops/remove-components.js:246:33
    at async Promise.all (index 0)
    at async removeLocal (/Users/kutner/projects/bit-bin/node_modules/@teambit/legacy/dist/consumer/component-ops/remove-components.js:244:5)
    at async removeComponents (/Users/kutner/projects/bit-bin/node_modules/@teambit/legacy/dist/consumer/component-ops/remove-components.js:201:33)
    at async remove (/Users/kutner/projects/bit-bin/node_modules/@teambit/legacy/dist/api/consumer/lib/remove.js:153:21)
    at async LegacyCommandAdapter.action (/Users/kutner/projects/bit-bin/node_modules/@teambit/cli/dist/legacy-command-adapter.js:55:17)
    at async LegacyCommandAdapter.report (/Users/kutner/projects/bit-bin/node_modules/@teambit/cli/dist/legacy-command-adapter.js:72:26)
    at async CommandRunner.runReportHandler (/Users/kutner/projects/bit-bin/node_modules/@teambit/cli/dist/command-runner.js:216:20)
    at async CommandRunner.runCommand (/Users/kutner/projects/bit-bin/node_modules/@teambit/cli/dist/command-runner.js:142:16)
[2021-07-14 18:45:47.010 +0300] ERROR (73856): user gets the following error: failed loading version 0.0.1 of enved/react01 from the scope
```

**Comment by itaymendel** [comment]
no longer relevant
