### ISSUE TITLE
Export error: server responded with: "target node does not exist"

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#4765]
### Describe the bug
```
unexpected network error has occurred.
server responded with: "target node does not exist"

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```

### Steps to Reproduce
1. use 0.0.485, because it has overrideTs... already legacy API that at least works
1. `bit tag --all`
1. tag successfully completed
1. `bit export`
1. got error

### Expected Behavior
It should be exported.

### Screenshots, exceptions and logs
```
bit export --log
⢀⠀ running command "export"...triggering hook pre-export
scope.exportMany, ids: org.libs/auth-next, org.libs/auth-next-api, org.components/common/language-control, org.components/common/select-input, org.components/common/error-message, org.bit-extensions/custom-react, org.libs/router-config, org.libs/router-link-utils, org.graphql/types, org.components/common/icon, org.components/common/link, org.components/common/router-link, org.components/common/header, org.components/common/image, org.components/common/logo, org.components/common/menu, org.components/common/placeholder-loader, org.components/common/modals, org.components/common/lazy-render, org.components/common/buttons, org.components/common/label
export-scope-components, export to the following scopes scope "org.libs": org.libs/auth-next, org.libs/auth-next-api, org.libs/router-config, org.libs/router-link-utils, scope "org.components": org.components/common/language-control, org.components/common/select-input, org.components/common/error-message, org.components/common/icon, org.components/common/link, org.components/common/router-link, org.components/common/header, org.components/common/image, org.components/common/logo, org.components/common/menu, org.components/common/placeholder-loader, org.components/common/modals, org.components/common/lazy-render, org.components/common/buttons, org.components/common/label, scope "org.bit-extensions": org.bit-extensions/custom-react, scope "org.graphql": org.graphql/types
⠍⠀ exporting componentsrepository.clearCache
⠈⡙ exporting componentsrepository.clearCache
⠀⡘ exporting componentsrepository.clearCache
⠄⠀ exporting componentsrepository.clearCache
⢂⠀ exporting componentsHttp.pushToCentralHub, started. url: https://symphony.bit.dev/exporter/api/put. total objects 488
⢃⠨ exporting componentsHttp.pushToCentralHub, completed. url: https://symphony.bit.dev/exporter/api/put, status 200 statusText OK
got an error from command export: UnexpectedNetworkError: target node does not exist
UnexpectedNetworkError: target node does not exist
    at Http.pushToCentralHub (/Users/user/.bvm/versions/0.0.485/bit-0.0.485/node_modules/@teambit/legacy/dist/scope/network/http/http.js:357:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async pushAllToCentralHub (/Users/user/.bvm/versions/0.0.485/bit-0.0.485/node_modules/@teambit/legacy/dist/scope/component-ops/export-scope-components.js:396:25)
    at async exportMany (/Users/user/.bvm/versions/0.0.485/bit-0.0.485/node_modules/@teambit/legacy/dist/scope/component-ops/export-scope-components.js:359:5)
    at async exportComponents (/Users/user/.bvm/versions/0.0.485/bit-0.0.485/node_modules/@teambit/legacy/dist/api/consumer/lib/export.js:403:7)
    at async exportAction (/Users/user/.bvm/versions/0.0.485/bit-0.0.485/node_modules/@teambit/legacy/dist/api/consumer/lib/export.js:329:7)
    at async ExportCmd.report (/Users/user/.bvm/versions/0.0.485/bit-0.0.485/node_modules/@teambit/export/dist/export-cmd.js:133:9)
    at async CommandRunner.runReportHandler (/Users/user/.bvm/versions/0.0.485/bit-0.0.485/node_modules/@teambit/cli/dist/command-runner.js:214:20)
    at async CommandRunner.runCommand (/Users/user/.bvm/versions/0.0.485/bit-0.0.485/node_modules/@teambit/cli/dist/command-runner.js:142:16)
user gets the following error: unexpected network error has occurred.
server responded with: "target node does not exist"

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
unexpected network error has occurred.
server responded with: "target node does not exist"

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
[*] the command "export" has been terminated with an error code 1
```

`bit doctor` shows everything OK except not latest version, but we could not upgrade to latest due to breaking changes

### Specifications
* Bit version: 0.0.485
* Workspace type: harmony
* Node version: 14 lts
* yarn version: 1.22.10
* Platform: mac m1

**Comment by GiladShoham** [comment]
It was an issue on our server. It's fixed now.
