### ISSUE TITLE
Tests fail on syntax assuming it's flow

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#4779]
### Describe the bug
TestComponents step fails on compiling with message about flow syntax, but there is no flow at all.

```
Support for the experimental syntax 'flow' isn't currently enabled
```

### Steps to Reproduce
1. `bit tag common/social-media`
1. witness errors about tests are failed in other components, but why?

### Expected Behavior
Compile typescript files with typescript babel presets not flow.

### Screenshots, exceptions and logs
```
✔ env "org.bit-extensions/custom-react@0.0.10", task "teambit.defender/tester:TestComponents" has completed successfully in 2s
 FAIL  ../../../Library/Caches/Bit/capsules/5c444c1404588a87a9de3e2639b073a89738d75f/org.libs_router-link-utils@0.0.7/dist/getTargetPageData.test.js
  ● Test suite failed to run

    SyntaxError: /Users/user/Library/Caches/Bit/capsules/5c444c1404588a87a9de3e2639b073a89738d75f/org.libs_router-link-utils@0.0.7/index.ts: Support for the experimental syntax 'flow' isn't currently enabled (1:8):

    > 1 | export type { TOpenMethod } from './getOpenMethod';
        |        ^
      2 | export { default as getOpenMethod } from './getOpenMethod';
      3 | export {
      4 |   default as getTargetPageData,

    Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
    If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.

      at Parser._raise (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/error.js:134:45)
      at Parser._raise [as raiseWithData] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/error.js:129:17)
      at Parser.raiseWithData [as expectOnePlugin] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/util.js:199:18)
      at Parser.expectOnePlugin [as isExportDefaultSpecifier] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:1949:16)
      at Parser.isExportDefaultSpecifier [as maybeParseExportDefaultSpecifier] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:1826:14)
      at Parser.maybeParseExportDefaultSpecifier [as parseExport] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:1771:29)
      at Parser.parseExport [as parseStatementContent] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:329:25)
      at Parser.parseStatementContent [as parseStatement] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:231:17)
      at Parser.parseStatement [as parseBlockOrModuleBlockBody] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:967:25)
      at Parser.parseBlockOrModuleBlockBody [as parseBlockBody] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:943:10)
      at Parser.parseBlockBody [as parseProgram] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:117:10)
      at Parser.parseProgram [as parseTopLevel] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/statement.js:102:25)
      at Parser.parseTopLevel [as parse] (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/parser/index.js:41:10)
      at parse (../frontend/node_modules/@babel/core/node_modules/@babel/parser/src/index.js:58:38)
      at parser (../frontend/node_modules/@babel/core/lib/parser/index.js:52:34)
          at parser.next (<anonymous>)
```

### Specifications
* Bit version: 0.0.485
* Workspace type: harmony
* Node version: 14 lts
* yarn version: 1+
* Platform: mac m1

**Comment by GiladShoham** [comment]
This is usually a result of having a file that requires an internal file of another component.
Or a missing bit compile.

**Comment by GiladShoham** [comment]
We have thousands of ts components compiled fine with bit.
Getting this error is always one of the reasons mentioned above.
If that's not the case, please provide a tar with the workspace, or a github repo with a workspace so we can reproduce it.
Then re-open the issue.
