### ISSUE TITLE
Component re-export fails with error

### ISSUE THREAD

**Issue by dhruvit-r** [teambit/bit#4789]
### Describe the bug
Same as #4285, but it was closed without a proper resolution.

Re-exporting the component fails with an error: 

```
error: received an invalid response from the remote SSH server.
to see the invalid response, have a look at the log, located at /Users/dhruvit_r/Library/Caches/Bit/logs/debug.log
```

### Steps to Reproduce
```
mkdir x
cd x
git init
npm init -y
echo "node_modules" > .gitignore
bit init
bit import bit.envs/bundlers/webpack
cd components/bundlers/webpack
npm i webpack@latest
cd ../../../
bit tag --all
bit export dhruvit_r.facade-app-shell -s
```

### Expected Behavior
Component export succeeds.

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/5932865/130375123-d2f0193f-efe7-48fd-8c3e-fce63f9521dd.png)

`bit doctor` output:

```

  bit version   : 14.8.8
  node version  : v14.17.0
  npm version   : 6.14.14
  yarn version  : 1.22.10
  platform      : darwin
  user details  : Dhruvit Raithatha<dhruvit.raithatha@gmail.com>


╔════════════════════╤═════════════════════════════════╤════════════════════════════════════════════════════════╤════════╗
║ category           │ name                            │ description                                            │ status ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ configuration      │ validate workspace's bit config │ validate workspace configuration object                │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate git exec               │ validate that git executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ internal store     │ check orphan refs               │ checks for empty internal refs in local workspace      │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ local environments │ check environment symlinks      │ validate generated symlinks for workspace environments │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate npm exec               │ validate that npm executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate yarn exec              │ validate that yarn executable found                    │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ core               │ validate bit version            │ validate that bit version is up to date                │ passed ║
╚════════════════════╧═════════════════════════════════╧════════════════════════════════════════════════════════╧════════╝
```

Log file:

    2021-08-23T00:20:38.526Z [debug]: legacy-extensions.extensions-loader, start loading extensions 
    2021-08-23T00:20:38.652Z [debug]: scope.load, found scope at <redact>/.git/bit from cache 
    2021-08-23T00:20:38.836Z [info]: [*] started a new command: "export [remote] [id...]" with the following data: {
      "args": [
        "dhruvit_r.facade-app-shell",
        []
      ],
      "flags": {
        "setCurrentScope": true
      }
    }
    2021-08-23T00:20:38.841Z [debug]: Checking if a migration is needed 
    2021-08-23T00:20:38.850Z [info]: triggering hook pre-export 
    2021-08-23T00:20:40.764Z [debug]: scope.exportMany, ids: bit.envs/bundlers/webpack 
    2021-08-23T00:20:40.785Z [debug]: enrich context from global config 
    2021-08-23T00:20:40.873Z [debug]: reading ssh public key from /Users/dhruvit_r/.ssh/id_rsa.pub 
    2021-08-23T00:20:40.924Z [debug]: export-scope-components, export all ids to one remote 
    2021-08-23T00:20:41.074Z [debug]: Establishing a new SSH connection to ssh://bit@hub.bit.dev:dhruvit_r.facade-app-shell 
    2021-08-23T00:20:41.079Z [debug]: ssh, trying to connect using token 
    2021-08-23T00:20:41.100Z [debug]: ssh, failed to connect using token. user token not defined in bit-config. please run `bit login` to authenticate. 
    2021-08-23T00:20:41.100Z [debug]: ssh, trying to connect using ssh-agent 
    2021-08-23T00:20:43.894Z [debug]: ssh, failed to connect using ssh-agent. no matching private key found in ssh-agent to authenticate to remote server. 
    2021-08-23T00:20:43.894Z [debug]: ssh, trying to connect using ssh-key 
    2021-08-23T00:20:43.922Z [debug]: ssh, reading ssh key at /Users/dhruvit_r/.ssh/id_rsa 
    2021-08-23T00:20:47.271Z [debug]: ssh, failed to connect using ssh-key. failed connecting to remote server using `~/.ssh/id_rsa` or `ssh_key_file` in `bit config`. 
    2021-08-23T00:20:47.271Z [debug]: ssh, trying to connect using user-password 
    2021-08-23T00:21:03.091Z [debug]: ssh, authenticated successfully using user-password 
    2021-08-23T00:21:03.116Z [debug]: ssh: going to run a remote command _put, path: dhruvit_r.facade-app-shell 
    2021-08-23T00:21:05.835Z [error]: ssh: got an error, {"payload":{"code":"MODULE_NOT_FOUND","name":"Error","message":"Cannot find module '/tmp/symphony/http-resolver.js'","stack":"Error: Cannot find module '/tmp/symphony/http-resolver.js'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at remoteResolver (/usr/local/lib/node_modules/bit-bin/dist/remotes/remote-resolver/remote-resolver.js:58:24)\n    at Map.resolve (/usr/local/lib/node_modules/bit-bin/dist/remotes/remotes.js:116:42)\n    at /usr/local/lib/node_modules/bit-bin/dist/remotes/remotes.js:137:15\n    at keys.forEach.key (/usr/local/lib/node_modules/bit-bin/dist/utils/object/foreach.js:21:23)\n    at Array.forEach (<anonymous>)\n    at forEach (/usr/local/lib/node_modules/bit-bin/dist/utils/object/foreach.js:21:8)\n    at /usr/local/lib/node_modules/bit-bin/dist/remotes/remotes.js:135:28\n    at Generator.next (<anonymous>)\n    at Generator.tryCatcher (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)\n    at /usr/local/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:201:15\n    at Map.fetch (/usr/local/lib/node_modules/bit-bin/dist/remotes/remotes.js:147:7)"},"headers":{"version":"14.8.8","compressed":false}} 
    2021-08-23T00:21:05.837Z [debug]: ssh: exit. Exit code: null 
    2021-08-23T00:21:05.839Z [debug]: ssh: returned with code: null, signal: SIGMODULE_NOT_FOUND. 
    2021-08-23T00:21:05.844Z [error]: unpackCommand found on error "SyntaxError: Unexpected end of JSON input", while parsing the following string:  
    2021-08-23T00:21:05.848Z ]warn]: exportMany, failed pushing ids to the bare-scope 
    2021-08-23T00:21:05.850Z [error]: got an error from command export [remote] [id...]: SSHInvalidResponse 
    2021-08-23T00:21:05.851Z [error]: SSHInvalidResponse
        at SSH._unpack (/Users/dhruvit_r/.nvm/versions/node/v14.17.0/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:680:13)
        at /Users/dhruvit_r/.nvm/versions/node/v14.17.0/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:691:16
        at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    2021-08-23T00:21:05.945Z [error]: user gets the following error: error: received an invalid response from the remote SSH server.
    to see the invalid response, have a look at the log, located at /Users/dhruvit_r/Library/Caches/Bit/logs/debug.log
    
    run 'bit doctor' to get detailed workspace diagnosis and issue resolution. 
    2021-08-23T00:21:05.948Z [error]: [*] the command export [remote] [id...] has been terminated with an error code 1 ### Specifications* Bit version: 14.8.8
* Workspace type: harmony and legacy
* Node version: v14.17.0
* npm / yarn version: 6.14.14
* Platform: darwin

**Comment by itaymendel** [comment]
irrelevant. clsoing as can't reproduce.
