### ISSUE TITLE
React Native Jest transformIgnorePatterns Override tag failure

### ISSUE THREAD

**Issue by toticuervo-tandem** [teambit/bit#4812]
### Description
I am trying to apply a custom environment to react native components so that I may be able to pass tests and tag my components successfully. 

### Specifications
* Bit version: 0.0.494
* Node version: v14.17.3
* npm / yarn version: npm 6.14.13
* Platform: MacOS
* Bit compiler (include version): 
* Bit tester (include version):

### Context and additional information
I am making a react native component library for my team. This is my folder structure:

![Screen Shot 2021-08-26 at 9 00 11 AM](https://user-images.githubusercontent.com/72027038/130967040-52ff1b34-961d-4927-a8c9-785efc04d39a.png)

In my workspace.jsonc file, under variants I have this setup:

```
"teambit.workspace/variants": {
        /**
         * "*" is a special rule which applied on all components in the workspace.
         **/
        "*": {
            "teambit.react/react-native": {},
            "teambit.dependencies/dependency-resolver": {
                "policy": {
                    "peerDependencies": {
                        "react": "16.13.1",
                        "react-dom": "16.13.1",
                        "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz"
                    }
                }
            }
        }
    }
```

When I run: `bit tag --all --message "first version"`

I get:

```
✔ running pre install subscribers
✔ deduping dependencies for installation
...deadc15604dc5f2c246d432282bf71715d2fb |  WARN  @testing-library/react-native@7.2.0 requires a peer of react@>=16.0.0 but none was installed.
...deadc15604dc5f2c246d432282bf71715d2fb |  WARN  @testing-library/react-native@7.2.0 requires a peer of react-test-renderer@>=16.0.0 but none was installed.
...deadc15604dc5f2c246d432282bf71715d2fb |  WARN  babel-jest > babel-preset-jest > babel-preset-current-node-syntax: @babel/plugin-syntax-async-generators@7.8.4 requires a peer of @babel/core@^7.0.0-0 but none was installed.
...deadc15604dc5f2c246d432282bf71715d2fb |  WARN  babel-jest > babel-preset-jest > babel-preset-current-node-syntax: @babel/plugin-syntax-bigint@7.8.3 requires a peer of @babel/core@^7.0.0-0 but none was installed.
...deadc15604dc5f2c246d432282bf71715d2fb |  WARN  babel-jest > babel-preset-jest > babel-preset-current-node-syntax: @babel/plugin-syntax-class-properties@7.12.13 requires a peer of @babel/core@^7.0.0-0 but none was installed.
...deadc15604dc5f2c246d432282bf71715d2fb | +670 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 WARN  15 other warnings
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/toticuervo/.pnpm-store
  Virtual store is at:             ../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm
...deadc15604dc5f2c246d432282bf71715d2fb | Progress: resolved 665, reused 663, downloaded 2, added 670, done
../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/registry.npmjs.org/fsevents@1.2.13/node_modules/fsevents: Running install script, done in 4.6s
../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/registry.npmjs.org/core-js-pure@3.16.3/node_modules/core-js-pure: Running postinstall script, done in 87ms
../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/registry.npmjs.org/core-js@3.16.3/node_modules/core-js: Running postinstall script, done in 61ms
../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/registry.npmjs.org/core-js@2.6.12/node_modules/core-js: Running postinstall script, done in 70ms
  -------------------------
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
✔ teambit.component/isolator, create capsules network (completed in 19s)
  running build pipe for 1 environments, total 6 tasks
✔ teambit.component/isolator, create capsules network (completed in 9ms)
  generated graph for env "teambit.react/react-native", seeders total: 4, graph total: 4
✔ executing pre-build for all tasks
✔ env "teambit.react/react-native", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 412μs
✔ env "teambit.react/react-native", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 5s
 FAIL  ../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/tandem.library_text@0.0.1/dist/text.spec.js
  ● Test suite failed to run

    /Users/toticuervo/Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/Libraries/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (../../../../../.bvm/versions/0.0.494/bit-0.0.494/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/jest/setup.js:16:6)

 FAIL  ../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/tandem.library_button@0.0.1/dist/button.spec.js
  ● Test suite failed to run

    /Users/toticuervo/Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/Libraries/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (../../../../../.bvm/versions/0.0.494/bit-0.0.494/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/jest/setup.js:16:6)

 FAIL  ../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/tandem.library_colors@0.0.1/dist/colors.spec.js
  ● Test suite failed to run

    /Users/toticuervo/Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/Libraries/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (../../../../../.bvm/versions/0.0.494/bit-0.0.494/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/jest/setup.js:16:6)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        0.076 s
Ran all test suites.
✖ env: teambit.react/react-native, task "teambit.defender/tester:TestComponents" has failed
✔ env "teambit.react/react-native", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 61μs
✔ env "teambit.react/react-native", task "teambit.pkg/pkg:PublishDryRun" has completed successfully in 2s
✔ env "teambit.react/react-native", task "teambit.preview/preview:GeneratePreview" has completed successfully in 32s
✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running build pipe for 1 environments, total 6 tasks (completed in 40s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.defender/tester:TestComponents" of env "teambit.react/react-native"
component: tandem.library/button@0.0.1
  ● Test suite failed to run

    /Users/toticuervo/Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/Libraries/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (../../../../../.bvm/versions/0.0.494/bit-0.0.494/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/jest/setup.js:16:6)


component: tandem.library/colors@0.0.1
  ● Test suite failed to run

    /Users/toticuervo/Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/Libraries/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (../../../../../.bvm/versions/0.0.494/bit-0.0.494/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/jest/setup.js:16:6)


component: tandem.library/text@0.0.1
  ● Test suite failed to run

    /Users/toticuervo/Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/Libraries/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (../../../../../.bvm/versions/0.0.494/bit-0.0.494/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/.pnpm/@github.com/expo/react-native/archive@sdk-39.0.0.tar.gz/node_modules/react-native/jest/setup.js:16:6)


Found 3 errors in 3 components


✖ Total 6 tasks. 5 succeeded. 1 failed. 0 skipped. Total errors: 3.

```

Looking up this error: `type ErrorHandler = (error: mixed, isFatal: boolean) => void;` landed me [here](https://stackoverflow.com/questions/66652403/jest-config-is-throwing-type-errorhandler-error-mixed-isfatal-boolean)

After doing research on how I can use the jest transformIgnorePatterns with bit, I found this mention inside of the bit slack
![](https://user-images.githubusercontent.com/72027038/130968469-aab35d76-56da-468c-aa45-284d2a81b058.png)

Link 1: [here](https://harmony-docs.bit.dev/aspects/react/#customize-environment)
Link 2: [here](https://github.com/teambit/harmony-demo-movies/blob/main/extensions/withPreviewReact/jest/jest.config.js)

I decided that I needed to make a react-native environment, so I followed the steps mentioned in the docs [here](https://harmony-docs.bit.dev/aspects/react-native/#create-react-native-components)

my custom react native environment:

```
import { EnvsMain, EnvsAspect } from '@teambit/envs';
import { ReactNativeAspect, ReactNativeMain } from '@teambit/react-native';

export class CustomReactNativeExtension {
    constructor(private reactNative: ReactNativeMain) {}

    static dependencies: any = [EnvsAspect, ReactNativeAspect];

    static async provider([envs, reactNative]: [EnvsMain, ReactNativeMain]) {
        const CustomReactNativeEnv = reactNative.compose([
            /*
        Use any of the "reactNative.override..." transformers to
      */
            reactNative.overrideJestConfig(require('./jest/jest.config')),
        ]);

        envs.registerEnv(CustomReactNativeEnv);

        return new CustomReactNativeExtension(reactNative);
    }
}

```

my jest override file (jest/jest.config):

```
const reactJestConfig = require('@teambit/react-native').jestconfig;

module.exports = {
    ...reactJestConfig,
    transformIgnorePatterns: [
        'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base|static-container|unimodules-permissions-interface)',
    ],
};
```

I then added this environment to my variants. Firstly, attempting to replace the `teambit.react/react-native` with my own:

```
"teambit.workspace/variants": {
        /**
         * "*" is a special rule which applied on all components in the workspace.
         **/
            // "tandem.library/extensions/custom-react-native": {},
            "teambit.dependencies/dependency-resolver": {
                "policy": {
                    "peerDependencies": {
                        "react": "16.13.1",
                        "react-dom": "16.13.1",
                        "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz"
                    }
                }
            }
        }
    }
```

when I test any component using this environment it passes:

```
toticuervo@Totis-MacBook-Pro library2 % bit test button                        
testing total of 1 components in workspace 'my-workspace-name'
testing 1 components with environment teambit.harmony/node

 PASS  library/button/button.spec.tsx
  ✓ should render with the correct text (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.449 s
Ran all test suites.
tested 1 components in 3.036 seconds.

```

but then when I try to tag all of the components I now get a new error:

```
toticuervo@Totis-MacBook-Pro library2 % bit tag --all --message "first version"
✔ running pre install subscribers
✔ deduping dependencies for installation
...deadc15604dc5f2c246d432282bf71715d2fb |  WARN  @testing-library/react-native@7.2.0 requires a peer of react-test-renderer@>=16.0.0 but none was installed.
...deadc15604dc5f2c246d432282bf71715d2fb |  WARN  @testing-library/react@12.0.0 requires a peer of react-dom@* but none was installed.
...deadc15604dc5f2c246d432282bf71715d2fb | +612 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/toticuervo/.pnpm-store
  Virtual store is at:             ../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm
...deadc15604dc5f2c246d432282bf71715d2fb | Progress: resolved 612, reused 612, downloaded 0, added 612, done
../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/registry.npmjs.org/fsevents@1.2.13/node_modules/fsevents: Running install script, done in 2.4s
../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/registry.npmjs.org/core-js-pure@3.16.3/node_modules/core-js-pure: Running postinstall script, done in 80ms
../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/node_modules/.pnpm/registry.npmjs.org/core-js@2.6.12/node_modules/core-js: Running postinstall script, done in 83ms
  -------------------------
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
✔ teambit.component/isolator, create capsules network (completed in 13s)
  running build pipe for 1 environments, total 6 tasks
✔ teambit.component/isolator, create capsules network (completed in 10ms)
  generated graph for env "teambit.harmony/node", seeders total: 4, graph total: 4
✔ executing pre-build for all tasks
✔ env "teambit.harmony/node", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 380μs
✔ env "teambit.harmony/node", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 4s
 PASS  ../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/tandem.library_text@0.0.1/dist/text.spec.js
 PASS  ../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/tandem.library_button@0.0.1/dist/button.spec.js
 PASS  ../../../../Library/Caches/Bit/capsules/8f2deadc15604dc5f2c246d432282bf71715d2fb/tandem.library_colors@0.0.1/dist/colors.spec.js

Test Suites: 3 passed, 3 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.258 s, estimated 2 s
Ran all test suites.
✔ env "teambit.harmony/node", task "teambit.defender/tester:TestComponents" has completed successfully in 2s
✔ env "teambit.harmony/node", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 53μs
✔ env "teambit.harmony/node", task "teambit.pkg/pkg:PublishDryRun" has completed successfully in 2s
✖ env: teambit.harmony/node, task "teambit.preview/preview:GeneratePreview" has failed
✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running build pipe for 1 environments, total 6 tasks (completed in 38s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.harmony/node"
component: tandem.library/button@0.0.1
Module parse failed: Unexpected token (13:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict';
| 
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';

component: tandem.library/colors@0.0.1
Module parse failed: Unexpected token (13:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict';
| 
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';

component: tandem.library/extensions/custom-react-native@0.0.1
Module parse failed: Unexpected token (13:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict';
| 
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';

component: tandem.library/text@0.0.1
Module parse failed: Unexpected token (13:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict';
| 
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';

Found 4 errors in 4 components


✖ Total 6 tasks. 5 succeeded. 1 failed. 0 skipped. Total errors: 4.
```

I believe that this is because I need to combine or stack the environments. The `teambit.react/react-native` has things that my `custom-react-native` environment does not have. 

How can I make this work?

**Comment by toticuervo-tandem** [comment]
Closing because I have updated my findings in this ticket: https://github.com/teambit/bit/issues/4818
