### ISSUE TITLE
Issue with `bit link --target` in Next.js

### ISSUE THREAD

**Issue by LiamWalshWeb** [teambit/bit#4905]
### Description
We're trying to use the link command to test components locally in a project without having to tag and publish them first. Currently trying to link into a Next.js project and getting errors that look like duplicate React instances?

### Specifications
* Bit version: 0.0.512
* Node version: v14.16.1
* npm version: 6.14.12
* Platform: Mac
* Bit compiler (include version): 
* Bit tester (include version):

### Context and additional information
The link command creates the symlinks fine, the `node_modules` folder does have the linked code but we're getting errors that won't let us launch the page.

**Error log from the console:**

```
GET http://localhost:3003/ 500 (Internal Server Error)
handleApplyUpdates @ webpack-internal:///…t-dev-client.js:271
eval @ webpack-internal:///…t-dev-client.js:302
Promise.then (async)
tryApplyUpdates @ webpack-internal:///…t-dev-client.js:301
handleSuccess @ webpack-internal:///…ot-dev-client.js:79
processMessage @ webpack-internal:///…t-dev-client.js:212
eval @ webpack-internal:///…ot-dev-client.js:42
eval @ webpack-internal:///…y/eventsource.js:48
handleMessage @ webpack-internal:///…y/eventsource.js:46
index.js?20a9:314 Uncaught     at resolveDispatcher (file:///Users/liamwalsh/Development/design-system/node_modules/.pnpm/registry.npmjs.org/react@17.0.2/node_modules/react/cjs/react.development.js:1476:13)
    at Object.useContext (file:///Users/liamwalsh/Development/design-system/node_modules/.pnpm/registry.npmjs.org/react@17.0.2/node_modules/react/cjs/react.development.js:1484:20)
    at exports.ThemeProvider (file:///Users/liamwalsh/Development/design-system/node_modules/.pnpm/registry.npmjs.org/styled-components@5.2.3_281a4fa50a045c9112baf635f3bc27a7/node_modules/styled-components/dist/styled-components.cjs.js:1:24002)
    at processChild (file:///Users/liamwalsh/Development/search-mfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (file:///Users/liamwalsh/Development/search-mfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (file:///Users/liamwalsh/Development/search-mfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (file:///Users/liamwalsh/Development/search-mfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (file:///Users/liamwalsh/Development/search-mfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (file:///Users/liamwalsh/Development/search-mfe/node_modules/next/dist/server/render.js:596:45)
    at Object.ctx.renderPage (webpack-internal:///./src/pages/_document.tsx:29:30)
getNodeError @ nodeStackFrames.js?aca3:40
eval @ index.js?20a9:313
setTimeout (async)
_callee$ @ index.js?20a9:301
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:294
eval @ runtime.js?96cf:119
asyncGeneratorStep @ index.js?20a9:28
_next @ index.js?20a9:46
Promise.then (async)
asyncGeneratorStep @ index.js?20a9:37
_next @ index.js?20a9:46
eval @ index.js?20a9:51
eval @ index.js?20a9:43
_initNext @ index.js?20a9:363
initNext @ index.js?20a9:366
eval @ next-dev.js?3346:38
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1632905741877:860
options.factory @ webpack.js?ts=1632905741877:685
__webpack_require__ @ webpack.js?ts=1632905741877:37
__webpack_exec__ @ main.js?ts=1632905741877:1454
(anonymous) @ main.js?ts=1632905741877:1455
webpackJsonpCallback @ webpack.js?ts=1632905741877:1268
(anonymous) @ main.js?ts=1632905741877:9
:3003/_next/webpack-hmr?page=%2F_error:1 GET http://localhost:3003/_next/webpack-hmr?page=%2F_error net::ERR_CONNECTION_REFUSED
:3003/_next/webpack-hmr?page=%2F_error:1 GET http://localhost:3003/_next/webpack-hmr?page=%2F_error net::ERR_CONNECTION_REFUSED
:3003/_next/webpack-hmr?page=%2F_error:1 GET http://localhost:3003/_next/webpack-hmr?page=%2F_error net::ERR_CONNECTION_REFUSED
:3003/_next/webpack-hmr?page=%2F_error:1 GET http://localhost:3003/_next/webpack-hmr?page=%2F_error net::ERR_CONNECTION_REFUSED
:3003/_next/webpack-hmr?page=%2F_error:1 GET http://localhost:3003/_next/webpack-hmr?page=%2F_error net::ERR_CONNECTION_REFUSED
:3003/_next/webpack-hmr?page=%2F_error:1 GET http://localhost:3003/_next/webpack-hmr?page=%2F_error net::ERR_CONNECTION_REFUSED
:3003/_next/webpack-hmr?page=%2F_error:1 GET http://localhost:3003/_next/webpack-hmr?page=%2F_error net::ERR_CONNECTION_REFUSED
```

![image](https://user-images.githubusercontent.com/4707277/135237070-4eacf9c7-1eb0-436a-aed2-f54886f7129a.png)

**Comment by itaymendel** [comment]
please read explanation here
https://github.com/teambit/bit/issues/5842
