### ISSUE TITLE
bit tag command fails on circle-ci with typescript error that doesn't occur on the local env

### ISSUE THREAD

**Issue by ItayTur** [teambit/bit#5013]
### Describe the bug
I develop to a components lib, deployed to bit.

When i update components props that relay on each other, i get this typescript error in the circle-ci (but NOT LOCALLY). this error is when circle-ci run the command `bit tag`.

> Property 'ref' does not exist on type 'IntrinsicAttributes & TagsProps'

on this instance i added ref with forwardRef to `<Tags/>` which `<Dropdown/>` is it's parent. `<Dropdown />` pass a ref to `<Tags />`.

Usually, I delete the components involve in the issue from the `.Bitmap` file, and it solves it. But this time, when cirecle-ci run with the updated `.Bitmap` bit stills throws the error. 

This is the code for the Tags:

```
export const Tags = React.forwardRef<HTMLDivElement, TagsProps>(
  (
    {
      values,
      onRemoveTag,
      onClickTag,
      tagClassName,
      onMouseEnterTag,
      onMouseLeaveTag,
      id,
      ['data-testid']: dataTestId,
    },
    ref
  ) => {
    return (
      <StyledTags data-testid={dataTestId} ref={ref} id={id}>
        {values.map((value, index) => {
```

this is the Tags being used by the Dropdown:

```
<Tags
            data-testid={generateTestId('-tags')}
            ref={tagsRef}
            values={selectionsToShow as string[]}
            onRemoveTag={onRemoveTag}
            onClickTag={onRemoveTag}
          />
```

**The bit .sh file that cirecle-ci run, and bit throws and error on**

```
#! /bin/bash
echo "untag all"
node_modules/.bin/bit untag -a
PACKAGE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4)
echo "bit tag $PACKAGE_VERSION"
node_modules/.bin/bit tag --all $PACKAGE_VERSION
```

### Expected Behavior
Bit will use the updated component, with the new props. not the old ones that doesn't hold the current props.

### Screenshots, exceptions and logs
**circle-ci logs**

```
$ . ./bit-add.sh
running bit add
warning: files src/components/tailwind.css already used by component: capitolis.common-ui/tailwind@2.1.4
warning: files src/components/tailwind-velocity.css already used by component: capitolis.common-ui/tailwind-velocity@2.1.1
tracking 46 new components
Done in 1.46s.
yarn run v1.22.5
$ node_modules/.bin/bit status
- fetching status
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > date-picker ... ok
     > dropdown ... ok
     > filter ... ok
     > icons ... ok
     > menu-item ... ok
     > svg ... ok
     > tag ... ok
     > tags ... ok
                         

components pending to be tagged automatically (when their dependencies are tagged)
     > capitolis.common-ui/back-arrow-icon ... ok
     > capitolis.common-ui/bell-icon ... ok
     > capitolis.common-ui/chartcon ... ok
     > capitolis.common-ui/circle-check-icon ... ok
     > capitolis.common-ui/circle-error-icon ... ok
     > capitolis.common-ui/clock-icon ... ok
     > capitolis.common-ui/close-icon ... ok
     > capitolis.common-ui/dashboard-icon ... ok
     > capitolis.common-ui/date-picker-group ... ok
     > capitolis.common-ui/date-range-icon ... ok
     > capitolis.common-ui/document-icon ... ok
     > capitolis.common-ui/download-icon ... ok
     > capitolis.common-ui/dropdown-button ... ok
     > capitolis.common-ui/envelop-icon ... ok
     > capitolis.common-ui/event-icon ... ok
     > capitolis.common-ui/expand-less ... ok
     > capitolis.common-ui/expand-more ... ok
     > capitolis.common-ui/multi-select ... ok
     > capitolis.common-ui/options-menu ... ok
     > capitolis.common-ui/parameters-icon ... ok
     > capitolis.common-ui/refresh-icon ... ok
     > capitolis.common-ui/single-select ... ok
     > capitolis.common-ui/table-icon ... ok
     > capitolis.common-ui/today-icon ... ok
     > capitolis.common-ui/trash-icon ... ok
     > capitolis.common-ui/update-icon ... ok
     > capitolis.common-ui/upload-icon ... ok
Done in 7.41s.
yarn run v1.22.5
$ . ./bit-tag.sh
untag all
no components found with version to untag on your workspace
bit tag 2.2.0
- importing components
- building components
  building components...
- building component - capitolis.common-ui/date-picker@1.0.3
✔ isolating component - date-picker
- building component - capitolis.common-ui/dropdown@2.1.4
Dropdown/Dropdown.tsx:414:13 - error TS2322: Type '{ "data-testid": string; ref: MutableRefObject<HTMLDivElement>; values: string[]; onRemoveTag: (event: MouseEvent<HTMLDivElement, MouseEvent>, index: number) => void; onClickTag: (event: MouseEvent<...>, index: number) => void; }' is not assignable to type 'IntrinsicAttributes & TagsProps'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & TagsProps'.

414             ref={tagsRef}
                ~~~

Dropdown/Dropdown.tsx:431:7 - error TS2322: Type '{ "data-testid": string; ref: (htmlElement: HTMLElement) => void; id: string; }' is not assignable to type 'IntrinsicAttributes & IconProps'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & IconProps'.

431       ref={arrowWidthCalbackRef}
          ~~~


Found 2 errors.


error: bit failed to build capitolis.common-ui/dropdown@2.1.4 with the following exception:
Command failed with exit code 2: /home/circleci/project/.git/bit/components/compilers/react-typescript/bit.envs/4.0.0/components/.dependencies/compilers/typescript/bit.envs/3.1.53/node_modules/typescript/bin/tsc --declaration
Error: Command failed with exit code 2: /home/circleci/project/.git/bit/components/compilers/react-typescript/bit.envs/4.0.0/components/.dependencies/compilers/typescript/bit.envs/3.1.53/node_modules/typescript/bin/tsc --declaration
    at makeError (/home/circleci/project/.git/bit/components/compilers/react-typescript/bit.envs/4.0.0/components/.dependencies/compilers/typescript/bit.envs/3.1.53/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/circleci/project/.git/bit/components/compilers/react-typescript/bit.envs/4.0.0/components/.dependencies/compilers/typescript/bit.envs/3.1.53/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Specifications
* Bit version: 14.8.8
* Workspace type: legacy
* Node version: 14.15.0
* yarn version: 1.22.10
* Platform: Mac

**Comment by itaymendel** [comment]
Hi,

We're adding type-checking to workspace-commands (`compile`, `start` and `watch`).
Right now type-checking happens during component versioning, when the component's build process runs. You can trigger it locally via `bit build`.

You can also run `bit watch --check-types` (experimental feature), to have Bit do type-checking in your workspace.

**Comment by ItayTur** [comment]
i run `bit build` locally and got the same error. is there another way ? when running `bit watch --check-types` i get `error: unknown option --check-types'`.
I tried adding the `-f` flag to the tag, but it also failed on the type check.

**Comment by itaymendel** [comment]
my bad, you want to run `bit check-types`, the `watch --check-types` is not yet implemented.
this allows a quicker way to get type-checks done for the entire project.
