### ISSUE TITLE
Quick start React guide fails on bit start command

### ISSUE THREAD

**Issue by jazztec** [teambit/bit#5075]
Following the quick start guide.  When you execute the bit start step Webpack fails with 412 errors.

### Steps to Reproduce
1. npm i -g teambit/bvm
1. bvm install
1. bit new react ui-library
1. cd ui-library
1. bit install
1. bit compile
1. bit start

### Expected Behavior
Bit dev server to start correctly.

### Screenshots, exceptions and logs
`ERROR in ./node_modules/@company/scope.ui.text/dist/text.module.scss (../../../.bvm/versions/0.0.565/bit-0.0.565/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!../../../.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/react/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!../../../.bvm/versions/0.0.565/bit-0.0.565/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[5].use[3]!../../../.bvm/versions/0.0.565/bit-0.0.565/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[4]!./node_modules/@company/scope.ui.text/dist/text.module.scss)
Module build failed (from ../../../.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/react/node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/ollyj/.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/react/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.module.constructor.require (/Users/ollyj/.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/ollyj/.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:37:28)
    at Object.<anonymous> (/Users/ollyj/.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/react/node_modules/postcss-loader/dist/index.js:12:39)
    at Module._compile (/Users/ollyj/.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:62:36)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.module.constructor.require (/Users/ollyj/.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/ollyj/.bvm/versions/0.0.565/bit-0.0.565/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:37:28)
 @ ./node_modules/@company/scope.ui.text/dist/text.module.scss 2:12-605 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29 47:4-60:5
 @ ./node_modules/@company/scope.ui.text/dist/text.js 24:43-72
 @ ./node_modules/@company/scope.ui.text/dist/text.docs.mdx 19:0-30 31:12-16
 @ ./node_modules/.cache/bit/teambit.preview/preview/teambit.harmony/aspect/__overview-1637331829661.js 11:12-126
`

### Specifications
* Bit version: 0.0.565
* Workspace type: (harmony)
* Node version: lts (17.0.1)
* npm / yarn version: (8.1.0)
* Platform: OS X Monterey

All the errors are failing with the error code: ERR_PACKAGE_PATH_NOT_EXPORTED

I also get this error when I run bit install
`✖ error: unable to load the extension "company.scope/envs/my-react", please use the '--log' flag for the full error.`

**Comment by jazztec** [comment]
I believe this to be an issue with my node version 17.0.1.  I changed to lts (16.13.0) and it worked.  Might be worth adding this to the quick start guide. Close this if you want or keep open to fix 17.x.x version.

**Comment by artem-tarasenko** [comment]
I've got a pretty similar error. I followed the docs as well and tried to start the dev server. Here is the error (or rather a small bit of it, the whole log of the error so huge I cannot even scroll to the top).

Node: v16.13.0 

```console
(@D:\Pixel\Desktop\DEV\bit\macro\node_modules\@company\scope.ui.heading\dist\heading.module.scss)
    at Object.emitError (C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\webpack\lib\NormalModule.js:570:6)
    at getPostcssOptions (C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\node_modules\postcss-loader\dist\utils.js:224:19)
    at Object.loader (C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\node_modules\postcss-loader\dist\index.js:65:42)

Module Error (from C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\node_modules\postcss-loader\dist\cjs.js):
Loading PostCSS "tailwindcss" plugin failed: Cannot find module 'tailwindcss'
Require stack:
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\node_modules\postcss-loader\dist\utils.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\node_modules\postcss-loader\dist\index.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\node_modules\postcss-loader\dist\cjs.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\webpack\lib\Compiler.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\webpack\lib\webpack.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\webpack\lib\index.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\dist\webpack\webpack.config.base.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\dist\react.env.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\react\dist\react.main.runtime.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\bit\dist\load-bit.js
- C:\Users\Pixel\AppData\Local\.bvm\versions\0.0.575\bit-0.0.575\node_modules\@teambit\bit\dist\app.js
```

**Comment by MaisonnatM** [comment]
Up !  Not being able to use Bit directly at installation seems to me to be a critical problem, don't you think ?

**Comment by itaymendel** [comment]
docs have been migrated since. please use latest guide.
