### ISSUE TITLE
Installing font awesome fails build with Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.harmony/node"

### ISSUE THREAD

**Issue by patrickehansen** [teambit/bit#5182]
### Describe the bug
Installing some packages fails, font awesome in particular is a simple example.

### Steps to Reproduce
1. Initialize a new workspace
1. Install react, react-dom, @testing-library/react
1. `bit install @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome`
1. `bit create react-component test/icon`
1. Place the following code in icon.tsx:
 
```
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'

export function Icon({}: IconProps) {
  return (
    <FontAwesomeIcon icon={faCoffee} />
  );
}

```

1. `bit compile`, `bit build`

### Expected Behavior
Compile and build should succeed, `bit start` should come up and display the font awesome icon correctly.

### Screenshots, exceptions and logs

```
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.harmony/node"
component: company.scope/test/icon
ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in 'C:\Users\User\AppData\Local\Bit\capsules\f90384813bb1a6bc3d3ef580b011bd4ef73eb978\node_modules\.pnpm\registry.npmjs.org+@fortawesome+react-fontawesome@0.1.16_react@17.0.2\node_modules\@fortawesome\react-fontawesome'
ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in 'C:\Users\User\AppData\Local\Bit\capsules\f90384813bb1a6bc3d3ef580b011bd4ef73eb978\node_modules\.pnpm\registry.npmjs.org+@fortawesome+react-fontawesome@0.1.16_react@17.0.2\node_modules\@fortawesome\react-fontawesome'
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\Compilation.js:1773:28
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\NormalModuleFactory.js:811:13
    at eval (eval at create (C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\NormalModuleFactory.js:286:22
    at eval (eval at create (C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\NormalModuleFactory.js:442:22
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\NormalModuleFactory.js:124:11
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\NormalModuleFactory.js:673:25
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\NormalModuleFactory.js:882:8
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\NormalModuleFactory.js:1002:5
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\neo-async\async.js:6883:13
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\lib\NormalModuleFactory.js:985:45
    at finishWithoutResolve (C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\User\AppData\Local\.bvm\versions\0.0.595\bit-0.0.595\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)

Found 1 errors in 1 components

```

### Specifications
* Bit version:0.0.595
* Workspace type: harmony
* Node version: 14.18.2
* npm / yarn version: 6.14.15
* Platform: Windows 10

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

### Additional context
This seems to occur frequently and with several different packages. This includes material-ui.

**Comment by patrickehansen** [comment]
This happens when a dependency should be a peer dependency. Use bit install --type peer for these.
