### ISSUE TITLE
mdx compile fails with aspect yarn enabled

### ISSUE THREAD

**Issue by pkhodaveissi** [teambit/bit#5399]
if I choose `yarn` as dependency manager,

I get this error while executing: `bit start`

```ERROR in ./node_modules/@pkhodaveissi/test-vhs.linear-progress/dist/LinearProgress.docs.mdx 1:2
Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ---
| description: A Button component.
| ---
 @ ./node_modules/.cache/bit/teambit.preview/preview/teambit.react/react/__overview-1644856218315.js 6:22-163

webpack 5.51.1 compiled with 1 error in 6727 ms
Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ---
| description: A Button component.
| ---
ModuleParseError: Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ---
| description: A Button component.
| ---
    at handleParseError (/Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/webpack/lib/NormalModule.js:941:19)
    at /Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/webpack/lib/NormalModule.js:1045:5
    at processResult (/Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/webpack/lib/NormalModule.js:763:11)
    at /Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at Array.<anonymous> (/Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/loader-runner/lib/LoaderRunner.js:223:4)
    at runCallbacks (/Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/pierreveissi/.bvm/versions/0.0.649/bit-0.0.649/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

note that the commands listed below execute with no error:
bit compile
bit build
bit install

ENV:

``` bit version   : 0.0.649
  node version  : v16.14.0
  npm version   : 8.3.1
  yarn version  : 1.22.17
  platform      : darwin
  user details  : Pierre<pooria.khodaveissi@gmail.com>


╔════════════════════╤═════════════════════════════════╤════════════════════════════════════════════════════════╤════════╗
║ category           │ name                            │ description                                            │ status ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ configuration      │ validate workspace's bit config │ validate workspace configuration object                │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate git exec               │ validate that git executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ internal store     │ check orphan refs               │ checks for empty internal refs in local workspace      │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ local environments │ check environment symlinks      │ validate generated symlinks for workspace environments │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate npm exec               │ validate that npm executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate yarn exec              │ validate that yarn executable found                    │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ core               │ validate bit version            │ validate that bit version is up to date                │ passed ║
╚════════════════════╧═════════════════════════════════╧════════════════════════════════════════════════════════╧════════╝

```

**Comment by itaymendel** [comment]
hi,
please ensure you run `bit link` after installing dependencies with yarn and then run `start`
