### ISSUE TITLE
Unable to start bit

### ISSUE THREAD

**Issue by renanbronchart** [teambit/bit#5503]
### Describe the bug

After installing bmv and bit in existing react-native project, when I tried to launch `bit start`, I have some many errors with webpack.

```
ERROR in ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace.ui.workspace-component-card/dist/workspace-component-card.module.scss
Module build failed (from ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.module.constructor.require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
    at Object.<anonymous> (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss-loader/dist/index.js:12:39)
    at Module._compile (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:64:36)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.module.constructor.require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
    at processResult (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:721:19)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:185:11
    at loadLoader (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:33:11)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:178:10)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:189:18
    at handleResult (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:53:2)
    at loadLoader (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule.doBuild (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:781:3)
    at NormalModule.build (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:928:15)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/Compilation.js:1322:12
    at NormalModule.needBuild (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:1200:32)
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace.ui.workspace-component-card/dist/workspace-component-card.js 1:1645-1694
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace.ui.workspace-component-card/dist/index.js 1:139-176
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/lanes.ui.lanes/dist/overview/lanes-overview.js 1:1258-1315
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/lanes.ui.lanes/dist/overview/index.js 1:189-216
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/lanes.ui.lanes/dist/index.js 1:1311-1332
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/lanes/dist/lanes.ui.runtime.js 1:891-925
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/dist/ui.root7465439d9f6f1510817c06966efdd329884ccb0f.js 1:7052-7187

ERROR in ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace-components-drawer/workspace-components-drawer.module.scss
Module build failed (from ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.module.constructor.require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
    at Object.<anonymous> (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss-loader/dist/index.js:12:39)
    at Module._compile (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:64:36)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.module.constructor.require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
    at processResult (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:721:19)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:185:11
    at loadLoader (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:33:11)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:178:10)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:189:18
    at handleResult (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:53:2)
    at loadLoader (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule.doBuild (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:781:3)
    at NormalModule.build (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:928:15)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/Compilation.js:1322:12
    at NormalModule.needBuild (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:1200:32)
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace-components-drawer/workspace-components.drawer.js 1:1580-1632
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace-components-drawer/index.js 1:263-303
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/workspace.ui.runtime.js 1:1856-1899
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/dist/ui.root7465439d9f6f1510817c06966efdd329884ccb0f.js 1:3216-3363

ERROR in ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace/workspace-overview/workspace-overview.module.scss
Module build failed (from ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.module.constructor.require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
    at Object.<anonymous> (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss-loader/dist/index.js:12:39)
    at Module._compile (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:64:36)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.module.constructor.require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
    at processResult (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:721:19)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:185:11
    at loadLoader (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:33:11)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:178:10)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:189:18
    at handleResult (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:53:2)
    at loadLoader (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule.doBuild (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:781:3)
    at NormalModule.build (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:928:15)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/Compilation.js:1322:12
    at NormalModule.needBuild (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:1200:32)
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace/workspace-overview/workspace-overview.js 1:945-988
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace/workspace-overview/index.js 1:243-274
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace/workspace.js 1:1915-1946
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace/index.js 1:85-107
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/index.js 1:211-233
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/workspace.ui.runtime.js 1:2119-2134
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/dist/ui.root7465439d9f6f1510817c06966efdd329884ccb0f.js 1:3216-3363

ERROR in ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace/workspace.module.scss
Module build failed (from ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.module.constructor.require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
    at Object.<anonymous> (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/node_modules/postcss-loader/dist/index.js:12:39)
    at Module._compile (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:64:36)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.module.constructor.require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/bit/dist/hook-require.js:17:29)
    at require (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
    at processResult (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:721:19)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:185:11
    at loadLoader (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:33:11)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:178:10)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:189:18
    at handleResult (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:53:2)
    at loadLoader (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule.doBuild (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:781:3)
    at NormalModule.build (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:928:15)
    at /Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/Compilation.js:1322:12
    at NormalModule.needBuild (/Users/renanbronchart/.bvm/versions/0.0.667/bit-0.0.667/node_modules/webpack/lib/NormalModule.js:1200:32)
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace/workspace.js 1:2196-2230
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/workspace/index.js 1:85-107
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/ui/index.js 1:211-233
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/workspace/dist/workspace.ui.runtime.js 1:2119-2134
 @ ../../.bvm/versions/0.0.667/bit-0.0.667/node_modules/@teambit/ui/dist/ui.root7465439d9f6f1510817c06966efdd329884ccb0f.js 1:3216-3363

236 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.51.1 compiled with 472 errors and 1 warning in 46797 ms
```

### Steps to Reproduce

`npm i -g @teambit/bvm`

Once the installation is complete, BVM can be used to install Bit using the command:

`bvm install`

If you have some problems you ca follow the official doc: [https://harmony-docs.bit.dev/getting-started/installing-bit](https://harmony-docs.bit.dev/getting-started/installing-bit)

Login on cli

`bit login`

`bit add my-component`

`bit install`

`bit link`

`bit start`

### Expected Behavior

A success with `bit start` command

### Specifications

- Bit version: 0.0.667
- Workspace type: harmony
- Node version: v17.4.0
- yarn version: 1.22.17
- Platform: react-native

*for harmony workspace*
```
// workspace.jsonc

/**
 * this is the main configuration file of your bit workspace.
 * for full documentation, please see: https://harmony-docs.bit.dev/workspace/configurations
 **/ {
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  /**
   * main configuration of the Bit workspace.
   **/
  "teambit.workspace/workspace": {
    /**
     * the name of the component workspace. used for development purposes.
     **/
    "name": "ui-kit",
    /**
     * set the icon to be shown on the Bit server.
     **/
    "icon": "https://static.bit.dev/bit-logo.svg",
    /**
     * default directory to place a component during `bit import` and `bit create`.
     * the following placeholders are available:
     * name - component name includes namespace, e.g. 'ui/button'.
     * scopeId - full scope-id includes the owner, e.g. 'teambit.compilation'.
     * scope - scope name only, e.g. 'compilation'.
     * owner - owner name in bit.dev, e.g. 'teambit'.
     **/
    "defaultDirectory": "{scope}/{name}",
    /**
     * default scope for all components in workspace.
     **/
    "defaultScope": "gymlib.ui-kit"
  },
  /**
   * main configuration for component dependency resolution.
   **/
  "teambit.dependencies/dependency-resolver": {
    /**
     * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
     */
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {},
      "peerDependencies": {}
    }
  },
  /**
   * workspace variants allow to set different subsets of configuration for components in your
   * workspace. this is extremely useful for upgrading, aligning and building components with a new
   * set of dependencies. a rule can be a directory or a component-id/namespace, in which case,
   * wrap the rule with curly brackets (e.g. `"{ui/*}": {}`)
   * see https://harmony-docs.bit.dev/aspects/variants for more info.
   **/
  "teambit.workspace/variants": {
    /**
     * "*" is a special rule which applied on all components in the workspace.
     **/
    "*": {
      "teambit.react/react-native": {},
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "peerDependencies": {
            "react": "^17.0.2",
            "react-dom": "^17.0.2"
          }
        }
      }
    }
  }
}
```

**Comment by GiladShoham** [comment]
Can you try please with node16?

**Comment by renanbronchart** [comment]
It's working with node16, but do you know when bit harmony could support node17 ?

**Comment by itaymendel** [comment]
closing this issue. on the teambit/bvm repo we're adding a capability to decouple bit from the node version installed on the local system.
