### ISSUE TITLE
Bit version 0.0.695 requires "esbuild-darwin-arm64" to build on Apple M1

### ISSUE THREAD

**Issue by Tommoore96** [teambit/bit#5620]
### Describe the bug
I recently upgraded Bit from `0.0.682` to `0.0.695` because `bit snap` was not showing me any preview on the Bit Cloud.   When trying the same command on `0.0.695` I got an error message I've never seen before.  I realised that it happens during the build

### Steps to Reproduce
1. Update bit to 0.0.695
1. `bit install`
1. `bit compile`
1. `bit build`

### Expected Behavior
I expect my workspace to build without any problems.

### Screenshots, exceptions and logs
```txt
Error: 
You installed esbuild on another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "esbuild-darwin-64" package is present but this platform
needs the "esbuild-darwin-arm64" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
Windows and WSL environments.

If you are installing with npm, you can try not copying the "node_modules"
directory when you copy the files over, and running "npm ci" or "npm install"
on the destination platform after the copy. Or you could consider using yarn
instead which has built-in support for installing a package on multiple
platforms simultaneously.

If you are installing with yarn, you can try listing both this platform and the
other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.

    at generateBinPath (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/esbuild/lib/main.js:1784:17)
    at esbuildCommandAndArgs (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/esbuild/lib/main.js:1868:31)
    at ensureServiceIsRunning (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/esbuild/lib/main.js:2030:25)
    at Object.transform (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/esbuild/lib/main.js:1925:37)
    at esbuildMinify (eval at transform (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/terser-webpack-plugin/dist/minify.js:36:3), <anonymous>:42:32)
    at minify (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/terser-webpack-plugin/dist/minify.js:21:10)
    at Object.transform (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/terser-webpack-plugin/dist/minify.js:37:10)
    at execFunction (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/threadChild.js:148:17)
    at execHelper (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/threadChild.js:127:5)
    at execMethod (/Users/thomasmoore/.bvm/versions/0.0.695/bit-0.0.695/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/threadChild.js:131:5)
message: 628.js from Terser plugin
```

### Specifications
* Bit version: 0.0.695
* Workspace type: harmony
* Node version: v16.13.2
* npm / yarn version: 1.22.17
* Platform: MacOS (Apple M1)

My workspace can be found [here](https://bit.cloud/koodoo/koomeleon/).

### Additional context
This is the `workspace.jsonc`:

```json
{
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  "teambit.workspace/workspace": {
    "name": "SPIKE-bit-ui",
    "icon": "https://static.bit.dev/bit-logo.svg",
    "defaultDirectory": "{scope}/{name}",
    "defaultScope": "koodoo.koomeleon"
  },
  "teambit.dependencies/dependency-resolver": {
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {
        "@teambit/design.ui.external-link": "0.0.344",
        "@teambit/documenter.theme.theme-compositions": "4.1.1",
        "@teambit/documenter.ui.copy-box": "4.1.1",
        "@teambit/eslint-config-bit-react": "~0.0.367",
        "@types/styled-components": "5.1.23",
        "@typescript-eslint/eslint-plugin": "4.29.3",
        "eslint-import-resolver-node": "0.3.6",
        "eslint-plugin-import": "2.22.1",
        "eslint-plugin-jest": "24.4.0",
        "eslint-plugin-jsx-a11y": "6.4.1",
        "eslint-plugin-mdx": "1.15.0",
        "eslint-plugin-react": "7.25.1",
        "jest-styled-components": "7.0.8",
        "react-is": "17.0.2",
        "sass": "1.43.4",
        "styled-components": "5.3.3",
        "uuid": "8.3.2"
      },
      "peerDependencies": {
        "@testing-library/dom": "8.11.1",
        "@testing-library/react": "12.0.0",
        "@testing-library/user-event": "13.5.0",
        "jest-styled-components": "7.0.8",
        "react": "17.0.2",
        "react-dom": "17.0.2",
        "react-is": "17.0.2",
        "styled-components": "5.3.3"
      }
    },
    "packageManagerArgs": [],
    "devFilePatterns": [
      "**/*.spec.ts"
    ],
    "strictPeerDependencies": true,
    "installFromBitDevRegistry": true,
    "savePrefix": ""
  },
  "teambit.workspace/variants": {
    "{ui/**}, !{ui/theme-provider}": {
      "koodoo.koomeleon/extensions/react-env": {}
    },
    "{ui/theme-provider}": {
      "teambit.react/react": {}
    },
    "{content/**}": {
      "teambit.mdx/mdx": {}
    },
    "{theming/**}": {
      "defaultScope": "koodoo.koomeleon"
    },
    "{extensions/**}, {aspects/**}, {apps/**}": {
      "teambit.harmony/aspect": {}
    }
  },
  "teambit.generator/generator": {
    "aspects": [
      "tommoore96.bit-spike/generator/theme-json"
    ]
  },
  "tommoore96.bit-spike/generator/theme-json": {}
}
```

**Comment by GiladShoham** [comment]
fixed
you will have to install bvm in version 0.0.37 (or higher) to be able to install the darwin-arm64 version
