### ISSUE TITLE
Creating from template: export mdx was not found

### ISSUE THREAD

**Issue by mateonunez** [teambit/bit#5876]
### Describe the bug
After installing `bit v0.0.7.44` i tried to create a new app from a template.

When starting the app all my components reports the following error:

```bash
ModuleDependencyError: export 'mdx' (imported as 'mdx') was not found in '@mdx-js/react' (possible exports: MDXContext, MDXProvider, useMDXComponents, withMDXComponents)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/webpack/lib/Compilation.js:2600:21)
    at /Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/webpack/lib/Compilation.js:2204:10
    at eval (eval at create (/Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:29:1)
    at /Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:376:11
    at /Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/neo-async/async.js:2830:7
    at Object.each (/Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/neo-async/async.js:2850:39)
    at /Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:355:18
    at /Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/neo-async/async.js:2830:7
    at Object.each (/Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/neo-async/async.js:2850:39)
    at /Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:48:16
    at Hook.eval [as callAsync] (eval at create (/Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.finish (/Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/webpack/lib/Compilation.js:2196:28)
    at /Users/mateonunez/.bvm/versions/0.0.744/bit-0.0.744/node_modules/webpack/lib/Compiler.js:1104:19
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

### Steps to Reproduce
1. bit new react-design-system design-system
1. cd design-system
1. bit start

### Expected Behavior
Start the application with my components.

### Screenshots, exceptions and logs
![Design System](https://i.ibb.co/cL3KSP2/Screenshot-2022-05-27-at-08-57-57.png)

### Specifications
* Bit version: 0.0.7.44 
* Workspace type: harmony 
* Node version: v14.18.3
* npm / yarn version: npm: 6.14.15 / yarn: 1.22.11
* Platform:

```
    System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: M1

    Hardware Overview:

      Model Name: Mac mini
      Model Identifier: Macmini9,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 7459.121.3
      OS Loader Version: 7459.121.3
```

**Comment by GiladShoham** [comment]
what is the env used by that sample-app component?
(you can see it by hovering over the react icon in the tree)

**Comment by mateonunez** [comment]
@GiladShoham 

This is the ouptut of `bit env` command:

```bash
❯ bit env
┌──────────────────────────────────────┬────────────────────────────────────────────────┐
│ component                            │ env                                            │
├──────────────────────────────────────┼────────────────────────────────────────────────┤
│ my-org.my-scope/app/sample-app       │ teambit.community/envs/community-react@1.95.12 │
├──────────────────────────────────────┼────────────────────────────────────────────────┤
│ my-org.my-scope/themes/base-theme    │ teambit.react/react                            │
├──────────────────────────────────────┼────────────────────────────────────────────────┤
│ my-org.my-scope/themes/dark-theme    │ teambit.react/react                            │
├──────────────────────────────────────┼────────────────────────────────────────────────┤
│ my-org.my-scope/themes/light-theme   │ teambit.react/react                            │
├──────────────────────────────────────┼────────────────────────────────────────────────┤
│ my-org.my-scope/themes/theme-toggler │ teambit.react/react                            │
├──────────────────────────────────────┼────────────────────────────────────────────────┤
│ my-org.my-scope/ui/cards/card        │ teambit.community/envs/community-react@1.95.12 │
├──────────────────────────────────────┼────────────────────────────────────────────────┤
│ my-org.my-scope/ui/heading           │ teambit.design/envs/react@2.0.0                │
└──────────────────────────────────────┴────────────────────────────────────────────────┘
```

I also created a public repository to better analyze everything: [here](https://github.com/mateonunez/bit-harmony-mdx-error)

**Comment by GiladShoham** [comment]
This version of the env is broken, I'm working on it
