### ISSUE TITLE
bit status fails with component missing data. Parent was not found

### ISSUE THREAD

**Issue by sbland** [teambit/bit#5879]
Running `bit status` or `bit tag` fail with the following error: 
`component scope.component missing data. parent 3d94c334918e7c6c143a01e299092713dd376d16 of version e9de744ef9a263a088b439b264db2615e852b98c was not found.`

Reverting to a previous git commit where there wasn't an issue doesn't resolve the problem. I have also tried running `bit install` and `bit clear-cache`.

I recently moved the code from the component in the error but tried moving this code back but it made no difference.

### Specifications
* Bit version:0.0.726
* Workspace type: harmony
* Node version: v10.19.0
* npm / yarn version:8.1.0
* Platform: Ubuntu

**Comment by sbland** [comment]
Additional error trace from `bit status --log trace`

```
...
ComponentLoader, loading consumer-components from the file-system, ids: user.scope/helpers/component
ComponentLoader, the following 1 components have been already loaded, get them from the cache. user.scope/helpers/component@0.1.3
⡋⠀ fetching statusFailed finding a ref file /home/user/scope/.git/bit/objects/3d/94c334918e7c6c143a01e299092713dd376d16.
got an error from command status: ParentNotFound
ParentNotFound
    at /home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/scope/component-ops/get-diverge-data.js:122:15
    at async Promise.all (index 0)
    at async addParentsRecursively (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/scope/component-ops/get-diverge-data.js:116:5)
    at async /home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/scope/component-ops/get-diverge-data.js:120:9
    at async Promise.all (index 0)
    at async addParentsRecursively (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/scope/component-ops/get-diverge-data.js:116:5)
    at async getDivergeData (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/scope/component-ops/get-diverge-data.js:135:3)
    at async Component.setDivergeData (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/scope/models/model-component.js:527:26)
    at async ComponentStatusLoader.getStatus (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/consumer/component-ops/component-status-loader.js:180:5)
    at async ComponentStatusLoader.getComponentStatusById (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/consumer/component-ops/component-status-loader.js:136:52)
    at async /home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/consumer/component-ops/component-status-loader.js:112:22
    at async pMapSeries (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/p-map-series/index.js:9:15)
    at async ComponentStatusLoader.getManyComponentsStatuses (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/consumer/component-ops/component-status-loader.js:111:5)
    at async ComponentsList.listModifiedComponents (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/legacy/dist/consumer/component/components-list.js:206:33)
    at async StatusMain.status (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/status/dist/status.main.runtime.js:170:31)
    at async StatusCmd.report (/home/user/.bvm/versions/0.0.726/bit-0.0.726/node_modules/@teambit/status/dist/status-cmd.js:196:9)
```

**Comment by sbland** [comment]
Running `bit cat-object -p 3d94c334918e7c6c143a01e299092713dd376d16` also returns the error: `ENOENT: no such file or directory, open '/home/user/scope/.git/bit/objects/3d/94c334918e7c6c143a01e299092713dd376d16'`

**Comment by sbland** [comment]
Possibly fixed by doing a fresh clone of the repo then running `bit import`, `bit install`, `bit compile`.
Is there a reason the .git directory could be getting corrupted?

**Comment by sbland** [comment]
After trying to go back to an early git commit and retake my steps I got past the above error by reverting all changes to the versions in the .bitmap file. This seemed to work until I tried to tag again and the deployment failed. 
I now cannot run any bit commands due to the following error: 
```
fatal: local and remote of "user.scope/component" could not be diverged as they don't have any snap in common.
In other words, traversing the hashes of these components indicating that they are not related.
If this component was exported before, it might happen when the objects were missing locally.
In this case, the suggested solution is to untag the local tags, run "bit import" to fetch all objects and then tag and export.
Another case of this error is when locally this component was created for the first time and the remote already has a component with the same name.
In this case, you might want to remove the local component and import the remote
```
I cannot run `bit untag` as it results in the same error. I tried again reverting back to an old git commit but I still get the same error.

**Comment by sbland** [comment]
I resolved this by re cloning the repo then merging in all changes except .bitmap. I'm not entirely sure why it became corrupted.
