### ISSUE TITLE
When I tag a component and start the local server component is not shown

### ISSUE THREAD

**Issue by elias2089** [teambit/bit#5893]
### Steps to Reproduce
I recently started working with bit, the steps to follow were:

1. bit new react bit-front --default-scope ......
1. bit create react ui/atoms/button
1. bit start (everything works correctly)
1. Then I stop the local server
1. Run bit tag ui/atoms/button --message "initial tag"
1. bit start
It shows me the error, when click on the component:

TypeError: a.default.addLocale is not a function
    at t.default (312.191ac65a.js:2:306438)
    at 312.191ac65a.js:195:133438
    at Object.useMemo (312.191ac65a.js:480:1992613)
    at t.useMemo (312.191ac65a.js:480:2604685)
    at t.TimeAgo (312.191ac65a.js:195:133419)
    at oo (312.191ac65a.js:480:1986648)
    at Ws (312.191ac65a.js:480:2038948)
    at Il (312.191ac65a.js:480:2026189)
    at xl (312.191ac65a.js:480:2026117)
    at Cl (312.191ac65a.js:480:2025980)
overrideMethod @ VM23 react_devtools_backend.js:4026
312.191ac65a.js:2 Uncaught (in promise) TypeError: a.default.addLocale is not a function
    at t.default (312.191ac65a.js:2:306438)
    at 312.191ac65a.js:195:133438
    at Object.useMemo (312.191ac65a.js:480:1992613)
    at t.useMemo (312.191ac65a.js:480:2604685)
    at t.TimeAgo (312.191ac65a.js:195:133419)
    at oo (312.191ac65a.js:480:1986648)
    at Ws (312.191ac65a.js:480:2038948)
    at Il (312.191ac65a.js:480:2026189)
    at xl (312.191ac65a.js:480:2026117)
    at Cl (312.191ac65a.js:480:2025980)

### Specifications
* Bit version: 0.0.739
* Workspace type: (harmony/legacy)
* Node version: 8.1.2
* yarn version: 1.22.17
* Platform: Window 10

**Comment by GiladShoham** [comment]
This should be fixed now with latest bit version (>744)
