### ISSUE TITLE
Unable to tag components due to failure in pipeline

### ISSUE THREAD

**Issue by ramkrishna757575** [teambit/bit#5917]
### Describe the bug
I was following the documentation of getting started with bit here https://harmony-docs.bit.dev , but I am facing an issue where when I try to tag a component, the build pipeline fails for all but two steps. However, everything works as expected in the local server.
All components get compiled correctly, they show up correctly in the local server without any issues. Only I am unable to tag the components and export them to the remote scope.

### Steps to Reproduce
1. Follow getting started guide and setup the workspace
1. Create a new react component using the bit create command
1. Once created, tag the component using the command `bit tag`

I have created a repo here which can be used to reproduce this issue: https://github.com/ramkrishna757575/bit-dev-test

### Expected Behavior
Component should be tagged using the `bit tag` command

### Screenshots, exceptions and logs
The following error occurs:

```
✔ running pre install subscribers
✔ deduping dependencies for installation
...8e7700bfa738ddca3598a03359b3342ef2a83 |  +78 ++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/ramkrishna/.pnpm-store/v3
  Virtual store is at:             ../../Library/Caches/Bit/capsules/c598e7700bfa738ddca3598a03359b3342ef2a83/node_modules/.pnpm
...8e7700bfa738ddca3598a03359b3342ef2a83 | Progress: resolved 78, reused 78, downloaded 0, added 0
  -------------------------
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
  running build pipe for 1 environments, total 7 tasks
  generated graph for env "teambit.react/react", originalSeedersOfThisEnv: 1, graphOfThisEnv: 1, graph total: 1
✔ executing pre-build for all tasks
✔ env "teambit.react/react", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 460μs
✔ env "teambit.react/react", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 2s
 FAIL  ../../Library/Caches/Bit/capsules/c598e7700bfa738ddca3598a03359b3342ef2a83/ram-trica.ui-library_buttons_button@0.0.1/dist/button.spec.js
  ● Test suite failed to run

    Cannot find module 'react-dom/client' from 'node_modules/.pnpm/registry.npmjs.org+@testing-library+react@13.3.0_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/pure.js'

    Require stack:
      node_modules/.pnpm/registry.npmjs.org+@testing-library+react@13.3.0_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/pure.js
      node_modules/.pnpm/registry.npmjs.org+@testing-library+react@13.3.0_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/index.js
      ram-trica.ui-library_buttons_button@0.0.1/dist/button.spec.js

      at Resolver.resolveModule (../../../../../.bvm/versions/0.0.753/bit-0.0.753/node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/.pnpm/registry.npmjs.org+@testing-library+react@13.3.0_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/pure.js:35:46)
      at Object.<anonymous> (node_modules/.pnpm/registry.npmjs.org+@testing-library+react@13.3.0_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/index.js:9:13)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.412 s
Ran all test suites.
✖ env: teambit.react/react, task "teambit.defender/tester:TestComponents" has failed
✔ env "teambit.react/react", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 669μs
✔ env "teambit.react/react", task "teambit.harmony/application:build_application" has completed successfully in 213μs
✔ env "teambit.react/react", task "teambit.preview/preview:GenerateEnvTemplate" has completed successfully in 624μs
✖ env: teambit.react/react, task "teambit.preview/preview:GeneratePreview" has failed
✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running build pipe for 1 environments, total 7 tasks (completed in 4s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.defender/tester:TestComponents" of env "teambit.react/react"
component: ram-trica.ui-library/buttons/button@0.0.1
Error: Cannot find module 'react-dom/client' from 'node_modules/.pnpm/registry.npmjs.org+@testing-library+react@13.3.0_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/pure.js'

Require stack:
  node_modules/.pnpm/registry.npmjs.org+@testing-library+react@13.3.0_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/pure.js
  node_modules/.pnpm/registry.npmjs.org+@testing-library+react@13.3.0_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/index.js
  ram-trica.ui-library_buttons_button@0.0.1/dist/button.spec.js


Found 1 errors in 1 components

Failed task 2: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react"
component: ram-trica.ui-library/buttons/button@0.0.1
ModuleNotFoundError: Module not found: Error: Can't resolve '@emotion/styled' in '/home/ramkrishna/Library/Caches/Bit/capsules/c598e7700bfa738ddca3598a03359b3342ef2a83/node_modules/.pnpm/registry.npmjs.org+@mui+styled-engine@5.8.0_react@17.0.2/node_modules/@mui/styled-engine'
ModuleNotFoundError: Module not found: Error: Can't resolve '@emotion/styled' in '/home/ramkrishna/Library/Caches/Bit/capsules/c598e7700bfa738ddca3598a03359b3342ef2a83/node_modules/.pnpm/registry.npmjs.org+@mui+styled-engine@5.8.0_react@17.0.2/node_modules/@mui/styled-engine'
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/Compilation.js:1773:28
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/NormalModuleFactory.js:811:13
    at eval (eval at create (/home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/NormalModuleFactory.js:286:22
    at eval (eval at create (/home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/NormalModuleFactory.js:442:22
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/NormalModuleFactory.js:673:25
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/NormalModuleFactory.js:882:8
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/neo-async/async.js:6883:13
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/lib/NormalModuleFactory.js:985:45
    at finishWithoutResolve (/home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/ramkrishna/.bvm/versions/0.0.753/bit-0.0.753/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

Found 1 errors in 1 components


✖ Total 7 tasks. 5 succeeded. 2 failed. 0 skipped. Total errors: 2.
```

### Specifications
* Bit version: 0.0.753
* Workspace type: harmony
* Node version: 16.15.0
* npm version: 8.5.5
* Platform: Ubuntu 22.04 LTS

_for harmony workspace_

* teambit.react/react ENV

**Comment by GiladShoham** [comment]
ok, so the problem here is with the version of `@testing-library/react`. version 13 is not compatible with react 17. only with React 18.
you need to `bit install @testing-library/react@^12.0.0 --type peer -u` then it will work.
If you want to use React18, you need to create a custom env. see here - https://bit.cloud/bit-foundations/react/react-version-envs/react-18-env

**Comment by ramkrishna757575** [comment]
Thanks @GiladShoham . This worked. I am able to tag the components successfully now.

**Comment by mrlimbani** [comment]
Thanks, @GiladShoham  and @ramkrishna757575. Now, I am able to tag the components successfully now.

**Comment by Thomas-Boi** [comment]
Just want to add: Another symptom of this problem happens when you try to tag the env. You might run into this error:
```
✖ env: teambit.envs/env, task "teambit.preview/preview:GenerateEnvTemplate" threw an error
The 'compilation' argument must be an instance of Compilation
```

Try running `bit install @testing-library/react@^12.0.0 --type peer -u` as suggested above and it should solve your problem
