### ISSUE TITLE
`bit export` to self hosted scope return 413, Request Entity Too Large

### ISSUE THREAD

**Issue by yufengwang** [teambit/bit#6183]
### Describe the bug
`bit export` 413,  Request Entity Too Large , when exporting to self hosted remote scope

### Steps to Reproduce
1. create a new bit workspace
1. create a custom env with `bit create react-env extensions/my-react`
1. `bit tag`
1. run a remote scope using docker with latest docker image 
1.  `bit remote add http://{remote-scope}`
1. `bit export`
1. error status: 413. text: Request Entity Too Large

### Expected Behavior
`bit export` successfully

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/12859005/180756409-42c1f771-2725-464f-9120-918b54ee1b21.png)

log content
```bash
*** Loading Bit *** argv:
/Users/wenhu/.bvm/nodejs/16.15.1/bin/node
/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/bit/bin/bit
export
--log=debug
workspace-config, isLegacy: false
scope.load, found scope at /Users/wenhu/me/bit-demo/.git/bit from cache
workspace-config, isLegacy: false
scope.load, found scope at /Users/wenhu/me/bit-demo/.git/bit from cache
teambit.workspace/workspace, loadAspects, loading 0 aspects.
ids:
needed-for: workspace.cli.registerOnStart
[+] CLI-INPUT: export --log=debug
[*] started a new command: "export" with the following data:
    args: [
      null
    ]
    flags: {
      "log": "debug"
    }
Checking if a migration is needed
⢀⠀ running command "export"...triggering hook pre-export
⡀⠀ exporting componentscope.exportMany, ids: extensions/my-react
export-scope-components, export to the following scopes scope "weim": extensions/my-react
repository.clearCache
⡂⠀ exporting componentthe next network configuration is used in network.http: [object Object]
⠅⠀ transferring 48 objects to the remote "weim"...the next network configuration is used in network.http: [object Object]
[-] Running pushMany on a remote, pushOptions: {"clientId":"1658747175979"}
Http.pushMany, url: http://bit-test.fe.ichoice.cc/api/scope/put  total objects 48
⡃⠀ transferring 48 objects to the remote "weim"...parsed error from HTTP, url: http://bit-test.fe.ichoice.cc/api/scope/put
exportMany, failed pushing objects to the remote
got an error from command export: UnexpectedNetworkError: url: http://bit-test.fe.ichoice.cc/api/scope/put. status: 413. text: Request Entity Too Large
UnexpectedNetworkError: url: http://bit-test.fe.ichoice.cc/api/scope/put. status: 413. text: Request Entity Too Large
    at remoteErrorHandler (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/scope/network/remote-error-handler.js:94:14)
    at Http.throwForNonOkStatus (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/scope/network/http/http.js:494:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Http.pushMany (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/scope/network/http/http.js:381:5)
    at async Remote.pushMany (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/remotes/remote.js:143:21)
    at async /Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/scope/component-ops/export-scope-components.js:564:9
    at async pMapSeries (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/p-map-series/index.js:9:15)
    at async pushRemotesPendingDir (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/scope/component-ops/export-scope-components.js:555:5)
    at async pushToRemotesCarefully (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/scope/component-ops/export-scope-components.js:537:5)
    at async exportMany (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/scope/component-ops/export-scope-components.js:291:5)
    at async exportComponents (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/api/consumer/lib/export.js:301:7)
    at async exportAction (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/legacy/dist/api/consumer/lib/export.js:245:7)
    at async ExportCmd.report (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/export/dist/export-cmd.js:110:9)
    at async CommandRunner.runReportHandler (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/cli/dist/command-runner.js:214:20)
    at async CommandRunner.runCommand (/Users/wenhu/.bvm/versions/0.0.799/bit-0.0.799/node_modules/@teambit/cli/dist/command-runner.js:142:16)
unexpected network error has occurred.
server responded with: "url: http://bit-test.fe.ichoice.cc/api/scope/put. status: 413. text: Request Entity Too Large"
```

### Specifications
* Bit version: 0.0.799
* Workspace type: harmony
* Node version: local v16.13.0
* npm / yarn version: npm version 8.1.0
* Platform: MacOs dev env, linux remote scope env

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

### Additional context
When exporting to bit.cloud, it works correctly. So this maybe a problem of self hosted  remote scope

**Comment by yufengwang** [comment]
Problem solved, It's the limitation of nginx. so increase client_max_body_size works
