### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve error when tagging a component that uses a custom env

### ISSUE THREAD

**Issue by HalahRaadSalih** [teambit/bit#6213]
### Describe the bug
I have a custom react env, the only customization done is tsconfig. This env is used for one component only. When attempting to tag the component, it throws the following error on generating preview for the custom environment 

Running bit tag ( skip the tests)  throws the error
`bit tag ui/my-welcome -m "remove theme code" --skip-tests`

```
The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "zenput-spike.bit-env-error/extensions/my-react@0.0.3"
component: zenput-spike.bit-env-error/ui/my-welcome@0.0.2
ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/halah/Library/Caches/Bit/capsules/f485181d1308a833ba45fd455b5c8f03ffad6c12/zenput-spike.bit-env-error_ui_my-welcome@0.0.2/dist/index.js' in '/Users/halah/repositories/bit-env-config-error'
ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/halah/Library/Caches/Bit/capsules/f485181d1308a833ba45fd455b5c8f03ffad6c12/zenput-spike.bit-env-error_ui_my-welcome@0.0.2/dist/index.js' in '/Users/halah/repositories/bit-env-config-error'
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/Compilation.js:1773:28
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/NormalModuleFactory.js:811:13
    at eval (eval at create (/Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/NormalModuleFactory.js:286:22
    at eval (eval at create (/Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/NormalModuleFactory.js:442:22
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/NormalModuleFactory.js:673:25
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/NormalModuleFactory.js:882:8
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/neo-async/async.js:6883:13
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/lib/NormalModuleFactory.js:985:45
    at finishWithoutResolve (/Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/halah/.bvm/versions/0.0.790/bit-0.0.790/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

Found 1 errors in 1 components


✖ Total 13 tasks. 12 succeeded. 1 failed. 0 skipped. Total errors: 1.
```

### Steps to Reproduce
1. Clone this repository https://github.com/HalahRaadSalih/bit-env-config-error
1. run `bit tag ui/my-welcome -m "remove theme code" --skip-tests`

### Expected Behavior
Error is not thrown

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version:0.0.790
* Workspace type: (harmony/legacy): Harmony
* Node version: v16.14.0
* npm / yarn version: npm 8.3.1
* Platform: react

_for harmony workspace_

* relevant env 
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

### Additional context
Original discussion thread on slack https://bit-dev-community.slack.com/archives/CCDHG0TPY/p1657670252799579

**Comment by GiladShoham** [comment]
What changes has been done to the tsconfig?

**Comment by HalahRaadSalih** [comment]
@GiladShoham 
tsconfig.ts: https://github.com/HalahRaadSalih/bit-env-config-error/blob/main/bit-env-error/extensions/my-react/typescript/tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "target": "es6",
    "allowJs": true,
    "jsx": "react-jsx",
    "lib": [
      "es6",
      "es7",
      "es2017",
      "esnext.asynciterable",
      "dom"
    ],
    "skipLibCheck": true,
    "esModuleInterop": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true
  },
  "exclude": [
    "dist",
    "node_modules",
    "package.json"
  ]
}
```

and the setup is here https://github.com/HalahRaadSalih/bit-env-config-error/blob/0f8e190361dec76be2cfa447bd381063a76e0225/bit-env-error/extensions/my-react/my-react.main.runtime.ts#L17

```
const tsconfig = require('./typescript/tsconfig.json');
const transformer: TsConfigTransformer = (config: TypescriptConfigMutator) => {
    config.setTsConfig(tsconfig).setArtifactName('declaration').setShouldCopyNonSupportedFiles(false);
    return config;
};
... 
react.useTypescript({
        buildConfig: [transformer],
        devConfig: [transformer]
    }),
```

**Comment by GiladShoham** [comment]
the webpack during generate preview is operating on the compiled files, and it seems that it didn't find the compiled index file.
is the file there? if not, we should understand why.

**Comment by HalahRaadSalih** [comment]
> the webpack during generate preview is operating on the compiled files, and it seems that it didn't find the compiled index file. is the file there? if not, we should understand why.

There is no index file in there
```
ls /Users/halah/Library/Caches/Bit/capsules/f485181d1308a833ba45fd455b5c8f03ffad6c12/zenput-spike.bit-env-error_ui_my-welcome@0.0.2/dist 

tsconfig.tsbuildinfo

```
There is no custom webpack config set up, when commenting the webpack code in main runtime file, same error appears.  This repo provided above, does not have much set up. But our our main repo uses CRA + craco, the webpak is set up by CRA.

**Comment by HalahRaadSalih** [comment]
The source of the issue was the noEmit flag in tsconfig file. Thank you! Closing this!
