### ISSUE TITLE
How to import bootstrap.css into all composition files

### ISSUE THREAD

**Issue by gtwilliams03** [teambit/bit#6600]
### Description

I am working on a library of shared react-bootstrap based components to be shared across multiple sites.  I have some basic components with compositions working.  I currently put this line into each composition file to render the react-bootstrap components with the proper css:

`import 'bootstrap/dist/css/bootstrap.min.css'`

I am sure this is not the correct process.  Is there some way to import the `bootstrap.min.css` file into the main workspace area so that all of the composition files render correctly without having to put this in each composition file? 

I apologize for the basic question, I have looked for issues, SO, and other places for the answer but I cannot figure this one basic issue out.

**Comment by gtwilliams03** [comment]
The apps I am working on all pull the `bootstrap.min.css` file in so the bit components render properly there.  This is just for previewing the compositions in my `bit start` `localhost` environment.

**Comment by benjgil** [comment]
Hi @gtwilliams03 
This is in our docs (though slightly deeper than it maybe should be):
https://bit.dev/reference/compositions/composition-context/

**Comment by benjgil** [comment]
In addition to the Providers array, you can also just module import a css file directly into the preview.runtime file and bit's bundler will add it to the bundle for component compositions and docs (of course none of this will affect how your component is consumed by applications, it's just for rendering component docs and examples in bit)

**Comment by gtwilliams03** [comment]
Ahh I will take a look.  Thank you for your gracious and quick reply!

**Comment by gtwilliams03** [comment]
I had this working, but then added some new components to the library, and now I am getting an error whenever I run `bit tag` on any existing or new component.  

The error is this: 

```
✖ env: severed-links.common/envs/my-react-bootstrap-env@0.0.2, task "teambit.preview/preview:GeneratePreview" has failed
```

And the errors repeat for every component in the library that I try to run `bit tag` on:

```
The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "severed-links.common/envs/my-react-bootstrap-env@0.0.2"
component: severed-links.common/picker@0.0.2
ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in '/Users/gtw/Library/Caches/Bit/capsules/445cda892a5d8c461f4bee154e559242aecae4f0/node_modules/@fortawesome/react-fontawesome'
ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in '/Users/gtw/Library/Caches/Bit/capsules/445cda892a5d8c461f4bee154e559242aecae4f0/node_modules/@fortawesome/react-fontawesome'
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/Compilation.js:1773:28
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/NormalModuleFactory.js:811:13
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/NormalModuleFactory.js:286:22
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/NormalModuleFactory.js:442:22
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/NormalModuleFactory.js:673:25
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/NormalModuleFactory.js:882:8
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/neo-async/async.js:6883:13
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/lib/NormalModuleFactory.js:985:45
    at finishWithoutResolve (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/AliasPlugin.js:125:14
    at next (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:14:3)
    at forEachBail (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:24:9)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/AliasPlugin.js:51:5
    at _next0 (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/gtw/.bvm/versions/0.0.867/bit-0.0.867/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

Found 1 errors in 1 components


✖ Total 14 tasks. 13 succeeded. 1 failed. 0 skipped. Total errors: 1.
```

Do you have any idea what I might have managed to do?

I tried deleting the referenced `/Bit/Capsules/` folder and seeing if a `bit install -u` would refresh it, but to no avail.

The referenced package `@fortawesome/fontawesome-svg-core` is installed, and `bit start` launches fine with previews in `localhost:3000` but the remote library on `bit.cloud` has no previews and 404 errors for any Compositions.

**Comment by gtwilliams03** [comment]
And, perhaps this goes without saying, but I can tag any component that does not have the `@fortawesome/fontawesome-svg-core` dependency just fine.

**Comment by benjgil** [comment]
I'm assuming that this was resolved in the end then :) 
Happy to help
