### ISSUE TITLE
Aspect component-todos referenced in the docs fails with "extension .json is not supported"

### ISSUE THREAD

**Issue by evelant** [teambit/bit#6889]
### Describe the bug
Per the docs here https://bit.dev/docs/workspace/workspace-json/ I attempted to add the component-todos aspect to my workspace. After adding it, `bit start` fails with `extension .json is not supported`.

### Steps to Reproduce
1. Install component-todos per docs  https://bit.dev/docs/workspace/workspace-json/ 
1. Run `bit start`
1. Observe failure `extension .json is not supported`

### Expected Behavior
It shouldn't fail

### Screenshots, exceptions and logs
verbose logs:

```
extension .json is not supported.
teambit.workspace/workspace, get whetware.taskhero/envs/taskhero-react-native-env
teambit.scope/scope, ScopeComponentLoader.get, loading whetware.taskhero/envs/taskhero-react-native-env
Failed finding a ref file /Users/imagio/dev/TaskHero/.git/bit/objects/ae/d3da84f59e20d61d4c7cea88c6242092e4ec80.
failed finding a component envs/taskhero-react-native-env with hash: aed3da84f59e20d61d4c7cea88c6242092e4ec80
Failed finding a ref file /Users/imagio/dev/TaskHero/.git/bit/objects/65/912295bda8a09e00f475dabe736696d1540917.
failed finding a component taskhero/envs/taskhero-react-native-env with hash: 65912295bda8a09e00f475dabe736696d1540917
component-loader.loadOne, failed loading envs/taskhero-react-native-env from the file-system
got an error from command start: Error: extension .json is not supported.
Error: extension .json is not supported.
    at parse (/Users/imagio/Library/Caches/Bit/capsules/4d3e4d7d7eecf68cdb784be0bb64d56f321e9630/node_modules/.pnpm/registry.npmjs.org+leasot@12.0.0/node_modules/leasot/dist/lib/parsers.js:134:15)
    at /Users/imagio/Library/Caches/Bit/capsules/4d3e4d7d7eecf68cdb784be0bb64d56f321e9630/node_modules/.pnpm/@learnbit+extending-bit.metadata.component-todos.modules.get-todos@0.0.1/node_modules/@learnbit/extending-bit.metadata.component-todos.modules.get-todos/dist/get-todos.js:13:46
    at Array.map (<anonymous>)
    at getTodos (/Users/imagio/Library/Caches/Bit/capsules/4d3e4d7d7eecf68cdb784be0bb64d56f321e9630/node_modules/.pnpm/@learnbit+extending-bit.metadata.component-todos.modules.get-todos@0.0.1/node_modules/@learnbit/extending-bit.metadata.component-todos.modules.get-todos/dist/get-todos.js:10:55)
    at /Users/imagio/Library/Caches/Bit/capsules/4d3e4d7d7eecf68cdb784be0bb64d56f321e9630/learnbit.extending-bit_metadata_component-todos_component-todos@0.0.3/dist/component-todos.main.runtime.js:95:79
    at /Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/workspace/dist/workspace-component/workspace-component-loader.js:339:26
    at Array.map (<anonymous>)
    at WorkspaceComponentLoader.executeLoadSlot (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/workspace/dist/workspace-component/workspace-component-loader.js:338:30)
    at async WorkspaceComponentLoader.get (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/workspace/dist/workspace-component/workspace-component-loader.js:207:23)
    at async Workspace.get (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/workspace/dist/workspace.js:683:23)
    at async Function._dependencyResolver.DependencyResolver.getDevFiles (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/dev-files/dist/dev-files.main.runtime.js:263:27)
    at async DependencyResolver.getDependenciesData (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/legacy/dist/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js:313:22)
    at async DependenciesLoader.getDependenciesData (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/legacy/dist/consumer/component/dependencies/dependency-resolver/dependencies-loader.js:104:30)
    at async DependenciesLoader.load (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/legacy/dist/consumer/component/dependencies/dependency-resolver/dependencies-loader.js:95:30)
    at async loadDependencies (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/legacy/dist/consumer/component/component-loader.js:275:7)
    at async ComponentLoader.loadOne (/Users/imagio/.bvm/versions/0.0.945/bit-0.0.945/node_modules/@teambit/legacy/dist/consumer/component/component-loader.js:284:7)
[+] CLI-OUTPUT: extension .json is not supported.
[*] the command "start" has been terminated with an error code 1
```

### Specifications
* Bit version: 0.0.945
* Workspace type: harmony
* Node version: 16.17.0
* npm / yarn version: pnpm 7.22.0
* Platform: macOS

_for harmony workspace_

* relevant aspects 
* learnbit.extending-bit/metadata/component-todos/component-todos

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by benjgil** [comment]
@giteden @NitsanCohen770
