### ISSUE TITLE
support all kinds of files

### ISSUE THREAD

**Issue by amir-arad** [teambit/bit#696]
## Expected Behavior
export and consume a component that is a resource, or written in any language.
## Actual Behavior
```
TypeError: Cannot read property 'replace' of undefined
 at getLinkContent (/Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/dist/links/link-generator.js:434:19)
 at linkToMainFile (/Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/dist/links/node-modules-linker.js:167:82)
 at /Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/dist/links/node-modules-linker.js:221:5
 at Array.map (<anonymous>)
 at linkComponents (/Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/dist/links/node-modules-linker.js:182:21)
 at _callee4$ (/Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/dist/api/consumer/lib/export.js:157:71)
 at tryCatch (/Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)
 at Generator.invoke [as _invoke] (/Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)
 at Generator.prototype.(anonymous function) [as next] (/Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)
 at step (/Users/amira/.nvm/versions/node/v8.7.0/lib/node_modules/bit-bin/dist/api/consumer/lib/export.js:228:191)
```

## Steps to Reproduce the Problem

  1. export a ruby file

## Specifications

  - Version: 0.12.4
  - Platform: osx

**Comment by idealley** [comment]
I might have done something wrong because it is the first time that I am using bit but I have a smilar error when I do `bit tag --all`:

```
TypeError: item.startsWith is not a function
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/build-tree.js:238:14
    at XWrap.f (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:6290:23)
    at XWrap.@@transducer/step (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:5203:46)
    at _reduce (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:5233:24)
    at reduceBy (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:6289:16)
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:586:23
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:551:35
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:52:27
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:429:80
```

It does the same error with other node versions. 

I could start tracking `.vue` component with bit add src/components/folder/*.vue They have been added to the `bit.json` but then anything else I do generates this error.

**Comment by idealley** [comment]
I might have done something wrong because it is the first time that I am using bit but I have a smilar error when I do bit tag --all:

TypeError: item.startsWith is not a function
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/build-tree.js:238:14
    at XWrap.f (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:6290:23)
    at XWrap.@@transducer/step (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:5203:46)
    at _reduce (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:5233:24)
    at reduceBy (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:6289:16)
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:586:23
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:551:35
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:52:27
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:429:80
It does the same error with other node versions.

I could start tracking .vue component with bit add src/components/folder/*.vue They have been added to the bit.json but then anything else I do generates this error.

**Comment by amitgilad3** [comment]
Hi @idealley .
Vue files are supported by bit, so i want to try and debug your issue locally.
can you please share the project with me privately so i can try to recreate this issue?

can you please provide the following info:
1. os
2. bit version
3. bit logs [docs location]( https://docs.bitsrc.io/docs/logs.html#logs-location)

thanks

**Comment by itaymendel** [comment]
@GiladShoham @davidfirst - from what i understand you have implemented it and merged to master.
please update the issue as well.

**Comment by amir-arad** [comment]
I honestly don't understand what yaal talk about here but i suspect it has nothing to do with this issue

**Comment by itaymendel** [comment]
@amir-arad , my comment was to the issue you raised. @davidfirst has implemented a behavior into Bit that it will now handle any type of file that is set as the main file. So, for example, you will be able to create a component that only has a *.md file.

as for the previous comments, I'm guessing that they are here by mistake.

I wanted him to attach his PR into this issue, for better tracking.
