### ISSUE TITLE
bvm can not install older versions

### ISSUE THREAD

**Issue by lcz1543812491** [teambit/bit#7227]
### Description

when run bvm install 0.0.846 

error is below

Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
    at GcpList.<anonymous> (/Users/liucongzhou/.config/yarn/global/node_modules/@teambit/bvm.list/dist/gcp/gcp-list.js:60:51)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/liucongzhou/.config/yarn/global/node_modules/@teambit/bvm.list/dist/gcp/gcp-list.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Specifications

- Bit version:  0.0.867.  bvm : 0.3.1
- Node version: v16.19.1
- npm / yarn version: yarn 1.22.19.   npm: 8.19.3
- Platform:  mac
- Bit compiler (include version):
- Bit tester (include version):

**Comment by NitsanCohen770** [comment]
This is resolved now
