### ISSUE TITLE
Cannot find module `typescript`

### ISSUE THREAD

**Issue by zxywftr** [teambit/bit#7927]
### Describe the bug

"Cannot find module 'typescript'".

Bit received an error loading teambit.vue/vue@0.1.37, due to the error:
"Cannot find module 'typescript'".
This is required for the component: unknown
Please use the '--log=error' flag for the full error.
try running "bit install" to fix this issue

### Steps to Reproduce

1.Use cmd.exe to open a empty folder
2.run this command

bit new vue my-workspace --env teambit.vue/vue --default-scope abc-org.abc-scope --log=error

### Expected Behavior

create a new workspace that contains a custom Vue env component. 

### Screenshots, exceptions and logs

[![pP5t5TS.md.jpg](https://z1.ax1x.com/2023/09/20/pP5t5TS.md.jpg)](https://imgse.com/i/pP5t5TS)

logs is here

.vue/vue@0.1.37, due to the error:
"Cannot find module 'typescript'".
This is required for the component: unknown
Please use the '--log=error' flag for the full error.
try running "bit install" to fix this issue

    err: {
      "type": "Error",
      "message": "Cannot find module 'typescript'\nRequire stack:\n- C:\\Users\\13942\\AppData\\Local\\Bit\\capsules\\faf92337a7139b3cbc7c3461074f98d8990e55d4\\teambit.vue_vue@0.1.37\\dist\\vue-env.bit-env.js\n- C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\aspect-loader\\dist\\plugin.js\n- C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\aspect-loader\\dist\\plugins.js\n- C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\aspect-loader\\dist\\aspect-loader.main.runtime.js\n- C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\bit\\dist\\load-bit.js\n- C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\bit\\dist\\app.js\n- C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\bit\\bin\\bit",
      "stack":
          Error: Cannot find module 'typescript'
          Require stack:
          - C:\Users\13942\AppData\Local\Bit\capsules\faf92337a7139b3cbc7c3461074f98d8990e55d4\teambit.vue_vue@0.1.37\dist\vue-env.bit-env.js
          - C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\aspect-loader\dist\plugin.js
          - C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\aspect-loader\dist\plugins.js
          - C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\aspect-loader\dist\aspect-loader.main.runtime.js
          - C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\bit\dist\load-bit.js
          - C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\bit\dist\app.js
          - C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\bit\bin\bit
              at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
              at Module._load (node:internal/modules/cjs/loader:922:27)
              at module.constructor.require (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\bit\dist\hook-require.js:27:31)
              at require (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\toolbox.performance.v8-cache\dist\v8-compile-cache.js:39:28)
              at _typescript2 (C:\Users\13942\AppData\Local\Bit\capsules\faf92337a7139b3cbc7c3461074f98d8990e55d4\teambit.vue_vue@0.1.37\dist\vue-env.bit-env.js:57:39)
              at new VueEnv (C:\Users\13942\AppData\Local\Bit\capsules\faf92337a7139b3cbc7c3461074f98d8990e55d4\teambit.vue_vue@0.1.37\dist\vue-env.bit-env.js:168:40)
              at Object.<anonymous> (C:\Users\13942\AppData\Local\Bit\capsules\faf92337a7139b3cbc7c3461074f98d8990e55d4\teambit.vue_vue@0.1.37\dist\vue-env.bit-env.js:358:16)
              at Module._compile (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\toolbox.performance.v8-cache\dist\v8-compile-cache.js:64:36)
              at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
              at Module.load (node:internal/modules/cjs/loader:1119:32)
              at Module._load (node:internal/modules/cjs/loader:960:12)
              at module.constructor.require (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\bit\dist\hook-require.js:27:31)
              at require (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\toolbox.performance.v8-cache\dist\v8-compile-cache.js:39:28)
              at Plugin.require (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\aspect-loader\dist\plugin.js:34:22)
              at Plugin.register (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\aspect-loader\dist\plugin.js:29:25)
              at Plugins.registerPluginWithTryCatch (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\aspect-loader\dist\plugins.js:67:21)
      "code": "MODULE_NOT_FOUND",
      "requireStack": [
        "C:\\Users\\13942\\AppData\\Local\\Bit\\capsules\\faf92337a7139b3cbc7c3461074f98d8990e55d4\\teambit.vue_vue@0.1.37\\dist\\vue-env.bit-env.js",
        "C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\aspect-loader\\dist\\plugin.js",
        "C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\aspect-loader\\dist\\plugins.js",
        "C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\aspect-loader\\dist\\aspect-loader.main.runtime.js",
        "C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\bit\\dist\\load-bit.js",
        "C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\bit\\dist\\app.js",
        "C:\\Users\\13942\\AppData\\Local\\.bvm\\versions\\0.2.51\\bit-0.2.51\\node_modules\\@teambit\\bit\\bin\\bit"
      ]
    }
got an error from command new: BitError: Bit received an error loading teambit.vue/vue@0.1.37, due to the error:
"Cannot find module 'typescript'".
This is required for the component: unknown
Please use the '--log=error' flag for the full error.
try running "bit install" to fix this issue

    err: {
      "type": "BitError",
      "message": "Bit received an error loading \u001b[36mteambit.vue/vue@0.1.37\u001b[39m, due to the error:\n\"Cannot find module 'typescript'\".\nThis is required for the component: \u001b[36munknown\u001b[39m\nPlease use the \u001b[36m'--log=error'\u001b[39m flag for the full error.\ntry running \u001b[36m\"bit install\"\u001b[39m to fix this issue\n",
      "stack":
          BitError: Bit received an error loading teambit.vue/vue@0.1.37, due to the error:
          "Cannot find module 'typescript'".
          This is required for the component: unknown
          Please use the '--log=error' flag for the full error.
          try running "bit install" to fix this issue

              at AspectLoaderMain.loadExtensionsByManifests (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\aspect-loader\dist\aspect-loader.main.runtime.js:725:47)
              at async AspectLoaderMain.loadAspectsFromGlobalScope (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\aspect-loader\dist\aspect-loader.main.runtime.js:573:7)
              at async GeneratorMain.getGlobalGeneratorEnvs (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\generator\dist\generator.main.runtime.js:336:9)
              at async GeneratorMain.findWorkspaceTemplateInGlobalScope (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\generator\dist\generator.main.runtime.js:359:9)
              at async GeneratorMain.getWorkspaceTemplate (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\generator\dist\generator.main.runtime.js:403:9)
              at async GeneratorMain.generateWorkspaceTemplate (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\generator\dist\generator.main.runtime.js:455:96)
              at async NewCmd.report (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\generator\dist\new.cmd.js:52:9)
              at async CommandRunner.runReportHandler (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\cli\dist\command-runner.js:163:20)
              at async CommandRunner.runCommand (C:\Users\13942\AppData\Local\.bvm\versions\0.2.51\bit-0.2.51\node_modules\@teambit\cli\dist\command-runner.js:104:16)
      "isUserError": true,
      "name": "BitError"
    }

### Specifications

- Bit version:0.2.51
- Workspace type: harmony
- Node version:20.6.1
- npm / yarn version:9.7.2
- Platform:win 11

**Comment by GiladShoham** [comment]
@Jinjiang please have a look

**Comment by zxywftr** [comment]
The command can work on my other computer. I think there could be some error with my computer env. Anywhy, I can use Bit on my other computer now.

**Comment by zxywftr** [comment]
I use my computer B to run the command and it worked. Then I upload the repo to git and  download the repo to my computer A,
then I run  ` bit create vue-env envs/my-vue-env --aspect teambit.vue/vue ` ,this command worked. Anyway, it works now
