### ISSUE TITLE
Yarn + Cannot find module './config/tsconfig.json'

### ISSUE THREAD

**Issue by giuliano-abinbev** [teambit/bit#8096]
### Description

The following error occurs in a custom env that extends `react-env` when running `bit install`.

```
✖ Bit received an error loading beertech.hexa-react-web/envs/react-component, due to the error:
"ENOENT: no such file or directory, open '/Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/.bit_roots/teambit.envs_env/node_modules/@hexa-react-web/envs.react-component/dist/react-component.bit-env.js'".
This is required for the component: beertech.hexa-react-web/theme@0.0.3
Please use the '--log=error' flag for the full error.
try running "bit install" to fix this issue

✖ Bit received an error loading beertech.hexa-react-web/envs/beertech-react@0.0.3, beertech.hexa-react-web/envs/react-component, due to the error:
"ENOENT: no such file or directory, open '/Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/.bit_roots/teambit.envs_env/node_modules/@hexa-react-web/envs.react-component/dist/react-component.bit-env.js'".
This is required for the component: beertech.hexa-react-web/ui/button
Please use the '--log=error' flag for the full error.
try running "bit install" to fix this issue
```

And this is the error after running `bit install --log=error`

```
teambit.harmony/aspect-loader, Bit received an error loading beertech.hexa-react-web/envs/beertech-react@0.0.3, beertech.hexa-react-web/envs/react-component, due to the error:
"Cannot find module './config/tsconfig.json'".
This is required for the component: beertech.hexa-react-web/ui/button
Please use the '--log=error' flag for the full error.
try running "bit install" to fix this issue

    err: {
      "type": "Error",
      "message": "Cannot find module './config/tsconfig.json'\nRequire stack:\n- /Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/.bit_roots/beertech.hexa-react-web_envs_react-component/node_modules/@hexa-react-web/envs.react-component/dist/react-component.bit-env.js\n- /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugin.js\n- /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugins.js\n- /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/aspect-loader.main.runtime.js\n- /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/dist/load-bit.js\n- /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/dist/app.js\n- /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/bin/bit",
      "stack":
          Error: Cannot find module './config/tsconfig.json'
          Require stack:
          - /Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/.bit_roots/beertech.hexa-react-web_envs_react-component/node_modules/@hexa-react-web/envs.react-component/dist/react-component.bit-env.js
          - /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugin.js
          - /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugins.js
          - /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/aspect-loader.main.runtime.js
          - /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/dist/load-bit.js
          - /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/dist/app.js
          - /Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/bin/bit
              at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
              at Function.resolve (/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:43:31)
              at new ReactComponent (/Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/.bit_roots/beertech.hexa-react-web_envs_react-component/node_modules/@hexa-react-web/envs.react-component/dist/react-component.bit-env.js:89:51)
              at Object.<anonymous> (/Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/.bit_roots/beertech.hexa-react-web_envs_react-component/node_modules/@hexa-react-web/envs.react-component/dist/react-component.bit-env.js:189:34)
              at Module._compile (/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:64:36)
              at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
              at Module.load (node:internal/modules/cjs/loader:1119:32)
              at Module._load (node:internal/modules/cjs/loader:960:12)
              at module.constructor.require (/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/dist/hook-require.js:27:31)
              at require (/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/toolbox.performance.v8-cache/dist/v8-compile-cache.js:39:28)
              at Plugin.require (/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugin.js:29:22)
              at Plugin.register (/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugin.js:24:25)
              at Plugins.registerPluginWithTryCatch (/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugins.js:71:25)
              at async Promise.all (index 0)
              at async Object.provider (/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugins.js:48:9)
      "code": "MODULE_NOT_FOUND",
      "requireStack": [
        "/Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/.bit_roots/beertech.hexa-react-web_envs_react-component/node_modules/@hexa-react-web/envs.react-component/dist/react-component.bit-env.js",
        "/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugin.js",
        "/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/plugins.js",
        "/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/aspect-loader/dist/aspect-loader.main.runtime.js",
        "/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/dist/load-bit.js",
        "/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/dist/app.js",
        "/Users/giulianomini/.bvm/versions/1.2.7/bit-1.2.7/node_modules/@teambit/bit/bin/bit"
      ]
    }
```

The current env extends `react-env version 1.0.20`.

I tried creating a brand new env, which extends `react-env version 1.0.26`, same issue.

This doesn't happen when using `pnpm`. The reason I need to use `yarn` is because of https://github.com/pnpm/pnpm/issues/5970

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by giuliano-abinbev** [comment]
Closing the issue because it looks like Bit doesn't like when `tsconfig.json` gets added in `.gitignore`
