### ISSUE TITLE
Bit Installation error:- reason: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by riyakhandelwalABInbev** [teambit/bit#8814]
I'm trying to install bit using  **npx @teambit/bvm install** command and getting the below error

request to https://bvm.bit.dev/bit/index.json?random=3340610 failed, reason: self signed certificate in certificate chainFetchError: request to https://bvm.bit.dev/bit/index.json?random=3340610 failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\Users\\AppData\Roaming\npm-cache\_npx\7192\node_modules\@teambit\bvm\node_modules\@teambit\bvm.list\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:412:35)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by djkepa** [comment]
same problem here

**Comment by djkepa** [comment]
I think it looks the same to me:
![image](https://github.com/teambit/bit/assets/45691844/db7a9e69-76ae-4994-877b-822eb8759cc1)
