### ISSUE TITLE
Cannot find module '../node_modules/@teambit/bit/dist/app'

### ISSUE THREAD

**Issue by StarHosea** [teambit/bit#8943]
### Describe the bug
cannot run any bit command in the new worksacpe created by bit

### Steps to Reproduce

1.  bit new react bit-demo-base --env bitdev.react/react-env --log=error
2. cd bit-demo-base 
3. bit install

### Expected Behavior

work ok

### Screenshots, exceptions and logs

cannot run any bit command 
```
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module '../node_modules/@teambit/bit/dist/app'
Require stack:
- /Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js'
  ]
}
muhaoxing@StarMacBook-Pro bit-demo-base % bit install
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module '../node_modules/@teambit/bit/dist/app'
Require stack:
- /Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js'
  ]
}
muhaoxing@StarMacBook-Pro bit-demo-base % bit status
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module '../node_modules/@teambit/bit/dist/app'
Require stack:
- /Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/muhaoxing/.bvm/versions/1.7.3/bit-1.7.3/node_modules/@teambit/legacy/bin/bit.js'
  ]
}

```

### Specifications

- Bit version: 1.7.3
- Workspace type:  bitdev.react/react-env
- Node version:  v16.20.2
- npm / yarn version: npm v8.19.4 
- Platform: MacOs

**Comment by GiladShoham** [comment]
Please try to re-install bit by 
Bvm install --override

**Comment by StarHosea** [comment]
Thank you for your response. I fixed it by using pnpm install, though I'm not sure why that worked.

**Comment by StarHosea** [comment]
appear again

```
muhaoxing@StarMacBook-Pro bit-demo-base % bit install
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module '../node_modules/@teambit/bit/dist/app'
Require stack:
- /Users/muhaoxing/.bvm/versions/1.7.17/bit-1.7.17/node_modules/@teambit/legacy/bin/bit.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/muhaoxing/.bvm/versions/1.7.17/bit-1.7.17/node_modules/@teambit/legacy/bin/bit.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/muhaoxing/.bvm/versions/1.7.17/bit-1.7.17/node_modules/@teambit/legacy/bin/bit.js'
  ]
}

```

**Comment by AlexanderBich** [comment]
Same thing

**Comment by itaymendel** [comment]
this issue is a result of a CSM<>ESM issue we found in node. when you update to the last version of Bit, it will use node 22.14, which solves the issue.
