### ISSUE TITLE
Export failing due to Bit version mismatch

### ISSUE THREAD

**Issue by arvola** [teambit/bit#919]
## Expected Behavior
Bit notifies that the server's version of Bit is not consistent with the client.

## Actual Behavior
Bit fails with a difficult to diagnose error `unexpected network error has occurred`.

## Steps to Reproduce the Problem

  1. Install bit on the developer machine with NPM.
  2. Install bit on the server with the Debian/Ubuntu apt package manager.
  3. Create a scope on the server and add it to remotes locally.
  4. Export a local component.

## Specifications
  - Bit version: 0.10.9 (server), 0.12.11 (client)
  - Node version: 9.11.1 (both)
  - npm / yarn version: NPM 5.6 (both)
  - Platform: Debian 9

## Notes
I see that there is an existing version difference detection logic, but it doesn't warn if the client is newer. There appears to be some kind of compatibility issue with the versions currently in the Debian package repository, and the NPM one.

After I upgraded Bit on the server to match, everything worked perfectly. Perhaps major and minor version differences should show a warning?

Here's are the log entries for the error:
```
2018-04-17T21:59:43.454Z - debug: ssh: going to run a remote command _put, path: /bit/scope
2018-04-17T21:59:43.948Z - error: ssh: got an error, {"name":"SyntaxError","message":"Unexpected token r in JSON at position 0","stack":"SyntaxError: Unexpected token r in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.manyFromString (/opt/npm-global/lib/node_modules/bit-bin/dist/scope/component-objects.js:70:19)
    at /opt/npm-global/lib/node_modules/bit-bin/dist/api/scope/lib/put.js:27:81
    at <anonymous>"}
2018-04-17T21:59:43.953Z - info: ssh: server had been exiting before closing. Exit code: 1
2018-04-17T21:59:43.954Z - debug: ssh: returned with code: 1, signal: undefined.
2018-04-17T21:59:43.955Z - error: ssh: failed parsing error as JSON, error: {"name":"SyntaxError","message":"Unexpected token r in JSON at position 0","stack":"SyntaxError: Unexpected token r in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.manyFromString (/opt/npm-global/lib/node_modules/bit-bin/dist/scope/component-objects.js:70:19)
    at /opt/npm-global/lib/node_modules/bit-bin/dist/api/scope/lib/put.js:27:81
    at <anonymous>"}
2018-04-17T21:59:43.960Z - warn: exportMany: failed pushing ids to the bare-scope
2018-04-17T21:59:43.961Z - error: got an error from command export <remote> [id...]: UnexpectedNetworkError. Error serialized: {"stack":"UnexpectedNetworkError
    at UnexpectedNetworkError.ExtendableBuiltin (/home/user/.nvm/versions/node/v9.11.1/lib/node_modules/bit-bin/dist/error/abstract-error.js:49:28)
    at UnexpectedNetworkError.AbstractError (/home/user/.nvm/versions/node/v9.11.1/lib/node_modules/bit-bin/dist/error/abstract-error.js:78:116)
    at new UnexpectedNetworkError (/home/user/.nvm/versions/node/v9.11.1/lib/node_modules/bit-bin/dist/scope/network/exceptions/unexpected-network-error.js:27:129)
    at SSH.errorHandler (/home/user/.nvm/versions/node/v9.11.1/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:227:18)
    at Channel.<anonymous> (/home/user/.nvm/versions/node/v9.11.1/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:201:54)
    at Channel.emit (events.js:185:15)
    at Channel.<anonymous> (/home/user/.nvm/versions/node/v9.11.1/lib/node_modules/bit-bin/node_modules/ssh2/lib/Channel.js:135:18)
    at Object.onceWrapper (events.js:272:13)
    at Channel.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)","name":"UnexpectedNetworkError"}
2018-04-17T21:59:43.992Z - error: User gets the following error: error: unexpected network error has occurred
2018-04-17T21:59:43.999Z - error: [*] the command export <remote> [id...] has been terminated with an error code 1
```

**Comment by GiladShoham** [comment]
Thanks @arvola !

There are few different issues you described here (see my comments inline):

1. Bit version in Debian package repository is not up to date - That's correct, we will fix it.
2. There is no notification on the client if there is a mismatch version and the client is newer - That's correct. The reason behind this is that if a user work against our server (bitsrc) (which most of the user does), and we didn't update it, all our users will get this notification all the time, without the ability to do anything about it.
But what you present is a valid use case (when you work against your own server), and we will think about a good way to show a notification in such cases.
3.  The error you got because of the mismatch is not informative enough - we will improve the output in such cases.

**Comment by itaymendel** [comment]
added proper error messages for the version mismatch issue, and I will remove the unsupported installation methods from the docs.
